### ISSUE TITLE
Error trying to import pyrfc

### ISSUE THREAD

**Issue by luisalonso97** [SAP/PyRFC#100]
Hi, I was trying to import pyrfc on the python shell running 'import pyrfc' but I get the following error:
`ImportError: DLL load failed: The specified procedure could not be found.`
I looked for a solution in the docs but there's only solution for the error `ImportError: DLL load failed: The specified module could not be found.`
I did set up the path variable to include `C:\nwrfcsdk\lib` and the directory lists as follows:
![image](https://user-images.githubusercontent.com/15828168/57170904-9eba9380-6dd5-11e9-8dbb-db91a060aa2c.png)

My path variable looks like this: 
`C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\php;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\nwrfcsdk\lib;C:\Users\portaladm\AppData\Local\Programs\Python\Python37\Lib;C:\Users\portaladm\AppData\Local\Programs\Python\Python37\libs;C:\Users\portaladm\AppData\Local\Programs\Python\Python37\Lib\nwrfcsdk\lib;C:\Users\portaladm\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\portaladm\AppData\Local\Programs\Python\Python37\;C:\Users\portaladm\AppData\Local\Microsoft\WindowsApps;C:\nwrfcsdk\lib`

**Comment by bsrdjan** [comment]
The screenshot shows the older version of SAP NW RFC SDK. It should also work but using the latest version is highly recommended.

Did you test if SAP NW RFC SDK properly installed, by running `rfcexec` for example, following the documentation: http://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation ?

If that works fine, the next problem could be missing [prerequisite](https://github.com/SAP/PyRFC#windows), see PyRFC/#19.

If none of this helps, which PyRFC version are you using and are you using the wheel from PyRFC repository, or built from source?

**Comment by luisalonso97** [comment]
@bsrdjan I asked for a newer version and now I have the latest that are currently listed for Windows 64-bit.

When I run the `rfcexec.exe` program I get an error saying that the version it's not compatible with the system and outputs a message in the console like this `C:\nwrfcsdk\bin>rfcexec.exe Access is denied.`

Trying to import in the python shell I get the following error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\portaladm\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrfc\__init__.py", line 22, in <module>
    from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
ImportError: DLL load failed: %1 is not a valid Win32 application.`

I did look for the links you commented and I do have installed [Visual C++ Redistributable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

And I have double checked the system specs, I'm running Windows Server 2016 64-bit, Python 3.7.3 64-bit and I'm using the correct wheel of the dist folder [pyrfc-1.9.94-cp37-cp37m-win_amd64.whl](https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.94-cp37-cp37m-win_amd64.whl)

My new `C:\nwrfcsdk\lib`folder lists as follows:
![image](https://user-images.githubusercontent.com/15828168/57241233-25e65200-6ff6-11e9-9743-fe76e8629969.png)

**Comment by bsrdjan** [comment]
If the `rfcexec` output differs from the documentation, no need to test pyrfc, the installation of SAP NW RFC SDK shall be fixed first.

The SAP NW RFC SDK screenshot does not look like a regular SAP NW RFC SDK, from [SAP Support Portal](https://launchpad.support.sap.com/#/softwarecenter/template/products/%20_APP=00200682500000001943&_EVENT=DISPHIER&HEADER=Y&FUNCTIONBAR=N&EVENT=TREE&NE=NAVIGATE&ENR=73555000100200006842&V=MAINT&TA=ACTUAL&PAGE=SEARCH/SAP%20NW%20RFC%20SDK%207.50). Linux SO libs and Windows DLLs are mixed up in the lib folder, which should not be the case.

Could you please re-install the latest SAP NW RFC SDK from SAP Support Portal and re-test?

Also check the authorization see [issue 75](https://github.com/SAP/PyRFC/issues/75#issuecomment-412964343).

**Comment by bsrdjan** [comment]
Was the answer of any help? Does the import works now?

**Comment by amarvin** [comment]
Similar dependency issue as #75
