### ISSUE TITLE
PyRFC maximum parameter sizes

### ISSUE THREAD

**Issue by jma24** [SAP/PyRFC#104]
Hi,

Am testing a concept with PyRFC which requires passing quite large tables as an input parameter. The one I am testing passes a table 3380 lines long and about 112KB in size into an ABAP program.

I appear to be getting truncation at exactly 16KB.

Is there a limit to the amount of data PyRFC will send, and can it be bypassed?

Thanks!

John

**Comment by jma24** [comment]
Closing this issue - turns out it was a bug in the standard SAP ABAP program being called.

**Comment by jma24** [comment]
Oops actually closing it this time

**Comment by YashGhaisas** [comment]
Hi John, 
I am getting the same issue, the value is being truncated at 16KB.
Can you please help me with it?

**Comment by YashGhaisas** [comment]
Im getting only 16KB UUID rather than getting the 32KB while fetching the data from SAP using pyrfc in python 
Example - If the value is - '005056AE436A1EE682FA84AD95D5B572', then I'm getting only - '005056AE436A1EE6'
@jma24
