### ISSUE TITLE
How to send data to SAP

### ISSUE THREAD

**Issue by yvonndjamen** [SAP/PyRFC#105]
Hello, i am really new here and i hope my problem is in the right section.
For my university project, i have some files in a server (MQTT Broker) that i read with the help of a Python code, that subscribe to that Broker. Now i want to save all the files that the python code receive into a Database (SAP).
I saw that i can use PyRFC to create a connection to SAP in my Python Code, but i want to know if there is a function that can help me send those data to SAP.
If it´s possible, how can it be done?
Thanks in advance for all your incoming responses

**Comment by bsrdjan** [comment]
There is no generic function available, for sending any data, to any SAP database table. SAP systems speak many protocols and RFC (for which PyRFC offers Python bindings) is just one of them. Over RFC protocol, you can call ABAP function module, which accepts broker data and writes them to the database. If no such module exist, you could try [SAP/PyHDB](https://github.com/SAP/PyHDB), writing direct to HANA database tables.

**Comment by yvonndjamen** [comment]
Thanks for your quick reply @bsrdjan 
i just started reading about SAP/PyHDB and i also think it will help me out solving my issue. 
But i´m also interested on knowing "how to call ABAP function module" to get broker data and write to the database, as you suggest.
Can i have more information about the process of doing it or is there any documentation that can help me out for it?

**Comment by bsrdjan** [comment]
Examples how to pass Python (broker) data to PyRFC and call ABAP function module, you may find in [README](http://sap.github.io/PyRFC/intro.html#example-usage), [unit tests](https://github.com/SAP/PyRFC/tree/master/tests), [blogs](http://wbarczynski.pl/calling-bapis-with-python-and-pyrfc/) ... 

Which function module exactly to use, depends on data sent by broker, like new invoices, orders etc. Depending on these data and the business context (why data are sent to SAP, how should be processed ...), SAP business / technical consultant may help find the right function module.

**Comment by yvonndjamen** [comment]
okay @bsrdjan i will dig into the whole documentation to see if i can find something.
Thanks again for your help
