### ISSUE TITLE
Unable to connect through SNC

### ISSUE THREAD

**Issue by aeRaRe** [SAP/PyRFC#107]
Hi,
I have been playing with pyRFC for a while now, and was trying to see if it would be possible to use the SNC information as the connection parameters, but found this error

`c = Connection(snc_partnername="p:domain\user", user="user", ashost="server.com", sysnr="00", client="540", saprouter="", trace="3")

Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    c = Connection(snc_partnername="p:domain\user",user="user",  ashost="server.com", sysnr="00", client="540", saprouter="", trace="3")

  File "src/pyrfc/_pyrfc.pyx", line 181, in pyrfc._pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 239, in pyrfc._pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 269, in pyrfc._pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host with Unicode

ERROR       SncPDLInit()==SNCERR_INIT
            Unable to load GSS-API DLL
            named "C:\Windows\sysWOW64\sncgss32.dll"
TIME        Tue Sep 03 14:51:28 2019
RELEASE     753
COMPONENT   SNC (Secure Network Communication)
VERSION     6
RC          -1
MODULE      D:/depot/bas/753_REL/src/krn/snc/sncxxdl.c
LINE        462
DETAIL      LoadLibrary("C:\Windows\sysWOW64\sncgss32.dll")
              Error 193 = "C:\Windows\sysWOW64\sncgss32.dll is no v [MSG: class=, type=, number=, v1-4:=;;;]`

I tried with User and password and thats working fine.

I also verified that I have the sncgss32.dll file in the path (the path is in the SNC_LIB).
This is working with SAP Logon (I don't need to use 'user and password' in SAP Logon), and also I saw another development in Excel that I assume connects through SNC because it doesn't require user and password, so I'm not sure if there's something wrong on my end or is it in SAP.

Any ideas what could it be?

**Comment by bsrdjan** [comment]
The system on which the PyRFC is running and SNC libraries are installed, has to be configured as a trusted system of the target SAP backend system. Also the mapping of the user PSE to ABAP user must be configured in a target SAP backend system, usually rule-based in production systems. SAP Basis/Security Consultant can help with the configuration and here couple of helpful links: [SAP SNC Help](https://help.sap.com/doc/saphelp_nwpi71/7.1/en-US/07/7bfc3d86ff492e9f2ac8a522d56161/frameset.htm) and [SAP IdM](https://wiki.scn.sap.com/wiki/display/Security/SAP+Identity+Management+7.2+Documentation).

**Comment by yaitzhan** [comment]
Hi, 
i have the almost the same troubles connecting to SAP system through SNC.
The connection with user and password works fine, the logs in the system approves that.

As @aeRaRe told, it works fine through SAP Logon too.

The piece of the trace file that i get mostly:
`LOCATION    CPIC (TCP/IP) with Unicode
ERROR       GSS-API(maj): No credentials were supplied
            Unable to establish the security context
            target="<my domain\user>"
TIME        Mon Nov 04 17:15:55 2019
RELEASE     721
COMPONENT   SNC (Secure Network Communication)
VERSION     6
RC          -4
MODULE      sncxxall.c
LINE        3604
DETAIL      SncPEstablishContext
SYSTEM CALL gss_init_sec_context
COUNTER     4`

pyRFC version 1.9.7, Python 3.6.8, OS Windows 10.
I use sapcryptolib.dll (+ SNC_LIB variable linked to .dll), which i downloaded from the SAP website.

Which input parameters should be passed when SNC is used?

**Comment by bsrdjan** [comment]
Some examples are provided in the documentation:

http://sap.github.io/PyRFC/authentication.html#snc-with-user-pse

**Comment by yaitzhan** [comment]
The problem is that i already played with the input parameters but still got the error:
` No credentials were supplied Unable to establish the security context`

The connection through SAP Logon + SNC for my user works fine.

I asked about them because it seems that they are the last thing that remains to connect through SNC...

**Comment by bsrdjan** [comment]
Is your Windows system properly configured as a trusted system of the ABAP backend system (ABAP transaction STRUST) ?

**Comment by yaitzhan** [comment]
What do you mean saying "Windows system": the laptop itself or my pyRFC client?

**Comment by bsrdjan** [comment]
Yes, the Windows system, on which Python/PyRFC is running. Here hopefully helpful blog:

https://blogs.sap.com/2006/09/29/setup-data-encryption-between-rfc-client-and-web-as-abap-with-snc/

**Comment by yaitzhan** [comment]
Is it possible to create security context with pyRFC in the Active Directory-based authentication infrastructure?

**Comment by bsrdjan** [comment]
It should be technically possible but not recommended scenario for customers. See [SAP OSS Note 2115486](2115486 - GSSKRB5.DLL & GSSNTLM.DLL Download)
