### ISSUE TITLE
White list for imported EXPORT parameters in the method call

### ISSUE THREAD

**Issue by filak-sap** [SAP/PyRFC#108]
I have stumbled upon a function module which does not initialize all its EXPORT parameters and RFC calls to this function made through PyRFC die with the message DO(410):
 `Runtime object for & could not be read`

Would it be possible to add an option for specifying which EXPORT parameters I want to import?

**Comment by bsrdjan** [comment]
The list of unwanted parameters can be passed as `not_requested` option, like in this unit test [example](https://github.com/SAP/PyRFC/blob/master/tests/test_connection.py#L158). Hope this helps.
