### ISSUE TITLE
Create dimension members in SAP BPC

### ISSUE THREAD

**Issue by knguyen1794** [SAP/PyRFC#110]
Hi everyone,

I have just come to find out about PyRFC.

I'm fairly new to SAP so I really hope I'm posting a valid question here. Hopefully I will get used of PyRFC and will be able to help the community up here too.

We are currently using SAP BPC (Business Planning & Consolidation) and I'm looking to automate some workflows an application (written in Python) that can talk to BPC. PyRFC seems to be the right tool for that.

Specifically what I'm trying to achieve is to create a new member for an existing dimension. Is there a standard ABAP function that I can call to do so?

![image](https://user-images.githubusercontent.com/45927236/65342075-86240c00-dc04-11e9-84d8-9f1ce2c941cf.png)

**What I have achieved so far...**

- Installed SAP NW RFC SDK
- Installed PyRFC
- Making a connection to the system
- Making a simple call

...as below: 

```python
from pyrfc import Connection
import re
from pprint import PrettyPrinter

class main():
    def __init__(self):
        ASHOST='xxx.xxx.xxx.xxx'
        CLIENT='xxx'
        SYSNR='xx'
        USER='xxxxxxxxxx'
        PASSWD='xxxxxxxxxx'
        self.conn = Connection(ashost=ASHOST, sysnr=SYSNR, client=CLIENT, user=USER, passwd=PASSWD)



# Init the class and connect
# I find this can be very slow to do...
s = main()
conn = main().conn
print("Is connection successful: ", conn.alive, "\n")

# Example
result = conn.call('STFC_CONNECTION', REQUTEXT=u'Hello SAP!')
print(result)
```

Result:
```
Is connection successful:  True 

{'ECHOTEXT': 'Hello SAP!', 'RESPTEXT': 'SAP R/3 Rel. 750   Sysid: xxx      Date: 20190921   Time: 002528   Logon_Data: xxx/xxxxxxxxxxx/x'}
```

**Is it possible to achieve what I'm planning to do here? Hope someone can shed some light. Thanks!**

**Comment by knguyen1794** [comment]
I asked this on SAP community as well.

Someone commented on it but I'm still not clear how to go about yet.

https://answers.sap.com/questions/12867815/create-dimension-members-in-sap-bpc-with-pyrfc.html?childToView=12869389#answer-12869389

**Comment by bsrdjan** [comment]
As answered in SAP Community, ABAP remote enabled function module can be created and called from Python.
