### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#111]
There is a typo in the docs at https://sap.github.io/PyRFC/client.html

The example source code starts with these two lines:

```
except ModuleNotFoundError as e:
    from configparser import ConfigParser
```

This does not make any sense.

Maybe something like this would make sense to support Python2 and Python3 (untested)

```
try:
    from ConfigParser import ConfigParser
except ImportError:
    from configparser import ConfigParser
```

**Comment by bsrdjan** [comment]
Fixed in 1.9.98
