### ISSUE TITLE
Binary data (python wheel packages) in git repo?

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#113]
It is very strange that you include the python wheel packages in the git repo:

https://github.com/SAP/PyRFC/tree/master/dist

This slows down cloning the git repo.

Related: https://github.com/guettli/programming-guidelines/blob/master/README.rst#dont-put-generated-code-into-version-control

**Comment by bsrdjan** [comment]
Thank you for the tip. Binaries are now moved to releases and the `dist/` folder is removed.
