### ISSUE TITLE
TypeError: 'name' (string) should be from 1-30 chars.

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#115]
I use [clientPrintDescription.py](https://github.com/SAP/PyRFC/blob/master/examples/clientPrintDescription.py) for introspection a RFC function module.

But I get this result:

```
 python clientPrintDescription.py /FOO/BAR

Traceback (most recent call last):
  File "clientPrintDescription.py", line 84, in <module>
    main(sys.argv[1])
  File "clientPrintDescription.py", line 26, in main
    func_desc = connection.get_function_description(function_name)
  File "src/pyrfc/_pyrfc.pyx", line 360, in pyrfc._pyrfc.Connection.get_function_description
  File "src/pyrfc/_pyrfc.pyx", line 1943, in pyrfc._pyrfc.wrapFunctionDescription
  File "src/pyrfc/_pyrfc.pyx", line 1904, in pyrfc._pyrfc.wrapTypeDescription
  File "src/pyrfc/_pyrfc.pyx", line 1011, in pyrfc._pyrfc.TypeDescription.add_field
TypeError: 'name' (string) should be from 1-30 chars.

```

The script works fine for several other RFC function modules.

What could be wrong here?

I guess the client code is all right, but there is something broken with this rfc function module.

**Comment by bsrdjan** [comment]
It looks like the field name empty or longer than 30 chars is detected in function module metadata, [triggering the exception]:(https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L1025).

Could you please try to find the suspicious field in function module parameters ? Is it a big function module, could you eventually somehow post/dump the structure here?

**Comment by guettli** [comment]
Thank you for your fast reply. Is there an equivalent to `python clientPrintDescription.py /FOO/BAR` which I can execute **inside** SAP?

Here is the head of the function module:

```
FUNCTION /MLK/TABLES_OF_CURRENT_USER.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"  EXPORTING
*"     VALUE(ALLOWED_TABLES) TYPE  /MLK/TT_TABNAME
*"----------------------------------------------------------------------
```
Details of /MLK/TT_TABNAME

![grafik](https://user-images.githubusercontent.com/414336/66044081-10337500-e521-11e9-837f-8829dc0f5d56.png)

![grafik](https://user-images.githubusercontent.com/414336/66044118-25100880-e521-11e9-95e6-fd1e87f3b078.png)

**Comment by guettli** [comment]
if the length of the name would get checked earlier, it would be possible to provide a better error message. It would be nice to see `/MLK/TT_TABNAME` in the error message.

Lines around  line number 1904
```
    rc = RfcGetTypeName(typeDesc, typeName, &errorInfo)
    if rc != RFC_OK:
        raise wrapError(&errorInfo)
    name = wrapString(typeName)
```

**Comment by bsrdjan** [comment]
Yes, the error message can be improved. I reproduced with EXPORTING TABLE TYPE parameter and need to investigate. SAP internal alternatives are two function modules:

**RFC_METADATA_GET**, for reading RFC parameters metadata (add /MLK/TABLES_OF_CURRENT_USER to FUNCTIONNAMES)

and:

**DDIF_FIELDINFO_GET** (/MLK/TT_TABNAME goes into TABNAME)

Both are strictly internal and undocumented, requiring considerable amount of try & error for any bigger use.

**Comment by guettli** [comment]
Fortunately I am not under pressure. If you are able to provide a fix in roughly one week, I can develop other stuff until next week.

Since you can reproduce it, I guess you are not far away from a fix?

**Comment by guettli** [comment]
BTW, I don't think switching the language makes much sense. Python is very popular. Java and C# share are in decline:

![grafik](https://user-images.githubusercontent.com/414336/66046189-88039e80-e525-11e9-868f-2457e3b5227c.png)

**Comment by guettli** [comment]
BTW: The example code of this project works. But, they code does not look like Python. It looks like someone translated code from a different language line-by-line to python.

I would suggest that SAP makes a contract with a python freelancer (not me) to clean up. The code could be simplified a lot.

Python developers care for beauty/simple code.

**Comment by guettli** [comment]
BTW3: I wrote down some thoughts while learning SAP+ABAP. I like the SAP platform. But I like the new development environments, too: https://github.com/guettli/why-i-like-django-and-sap/blob/master/README.md Feedback is welcome.

**Comment by bsrdjan** [comment]
Fixed in 387e946fe4e5310bd8ea3c7fdc048fa455a1938d, by removing zero length field name check: https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L1025. Will be added to next release.

**Comment by guettli** [comment]
@bsrdjan do you know when there will be a new release which contains this bug fix?

**Comment by bsrdjan** [comment]
Hopefully next week, together with DECF types added.
