### ISSUE TITLE
data_types.csv DECF16 missing

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#116]
I talk about this page:
  https://github.com/SAP/PyRFC/blob/master/doc/tables/data_types.csv

According to this page there is RFCTYPE_DECF16:
 https://help.sap.com/saphelp_nwpi711/helpdata/de/48/a8c5af51343079e10000000a42189b/content.htm?no_cache=true

But data_types.csv does not contain DECF16

**Comment by bsrdjan** [comment]
Yes, the types are missing, will be supported in next release, hopefully next week.
