### ISSUE TITLE
Not able to install PyRFC on PY 3.7.4. using pip from file

### ISSUE THREAD

**Issue by Dzokaja** [SAP/PyRFC#117]
Hi, 

I'm on Windows 10 Python 3.7.4. Downloaded version 1.9.4 from Releases to local, trying to pip install the file pyrfc-1.9.4-py3.5-win-amd64.egg. 

I'm not able to finish this - tried relating to the blob/dist folder, also to the /download folder, tried different approaches with downloading of the build, none worked. 
[pyrfc_install.log](https://github.com/SAP/PyRFC/files/3694974/pyrfc_install.log)

Log is attached.

**Comment by bsrdjan** [comment]
The version 1.9.4 is for Python 3.5. For Python 3.7.4 please use the latest release [1.9.97](https://github.com/SAP/PyRFC/releases/tag/1.9.97)

**Comment by Dzokaja** [comment]
when I run pip install on the downloaded file pyrfc-1.9.97-cp37-cp37m-win_amd64.whl

I'm getting:

ERROR: pyrfc-1.9.97-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by bsrdjan** [comment]
Reading the install log, it looks like 32 bit Python is installed and released wheels are for 64 bit only. Could you try with 64 bit Python? If you have to use the 32 bit, the wheel must be built from source.

**Comment by Dzokaja** [comment]
aaah jisas  :) Sorry for this thread, I've recently re-installed the whole machine and previously used 64 bits, I have no idea, how 32bit PY happened on my computer. 

Thanks for your help

**Comment by bsrdjan** [comment]
No worries, it happens very easy by accidental click on 32 bit instead of 64 bit Python download url, know the problem :)
