### ISSUE TITLE
Docs for params of call()

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#122]
> params (keyword arguments) – Parameter of the function module. All non optional IMPORT, CHANGING, and TABLE parameters must be provided.

Source: http://sap.github.io/PyRFC/pyrfc.html#pyrfc.Connection.call

I think it is strange, that all three ways to pass data to an RFC get merged into one dictionary/namespace.

I don't want the implementation to change.

But what happens if you RFC has an IMPORT parameter called "foo" and a CHANGING parameter called "foo"?

I think it makes sense to add one more sentence to above docs.

Maybe "All parameters of the three ways to provide data (IMPORT, CHANGING, TABLE) use the same flat namespace".

**Comment by bsrdjan** [comment]
Two ABAP function module parameters can't have the same name. ABAP editor complains and save is not possible, thus preventing naming troubles.

Nevertheless, the question came up in early versions, if the grouping at parameter type would make sense. Users did not see much value in it, preferring parameters' grouping at application level, by application logic, without more verbose IMPORTING/EXPORTING etc.

Also the IMPORTING/EXPORTING semantic was confusing for some people. The function module with IMPORTING parameter:

```abap
FUNCTION X IMPORTING Y
```
is called in ABAP using EXPORTING:

```abap
CALL FUNCTION X EXPORTING Y = 1
```

Shall IMPORTING/EXPORTING semantic in Python be like in ABAP function module, or reverted, like in ABAP client? No matter how, this ABAP convention looks does not feel natural in Python world and the majority liked a plain dictionary the most.

It could be however provided as option, backwards compatible, if really needed.

**Comment by guettli** [comment]
At first it feels strange, since you have several tabs for this in the sap-gui (se80).

I think one or two extra sentences in the docs would be enough.

Most developers love details and the "no name clash possible" information is not obvious. 

I think the implementation can stay like it is.

**Comment by bsrdjan** [comment]
To be updated in next release
