### ISSUE TITLE
Unable to download wheel file

### ISSUE THREAD

**Issue by Hemeshwar** [SAP/PyRFC#123]
In https://github.com/SAP/PyRFC, I'm unable to download wheel file from dist hyperlink in the Installation section. I need the latest wheel file for Windows. I'm new to this & I'm sorry if I'm wrong. Please help me out.
![image](https://user-images.githubusercontent.com/56714865/67073728-5802ff00-f1a5-11e9-85fd-a515e9cc277c.png)

**Comment by bsrdjan** [comment]
Moved to releases (see #118) and now fixed in README as well d8a0e6c5e31d48bf002deca41ee5e0052a68980e

**Comment by Hemeshwar** [comment]
Thank You Very Much :)

**Comment by mpf82** [comment]
@bsrdjan I noticed you have only changed the link in the "Supported platforms" section, but you did not yet change the link in the "Installation" section (the one from the screenshot in the original post).

See https://github.com/SAP/PyRFC#installation where "dist" still points to https://github.com/SAP/PyRFC/blob/master/dist

Cheers =)
