### ISSUE TITLE
Unable to find a way to call a transaction

### ISSUE THREAD

**Issue by JccSanabria** [SAP/PyRFC#124]
Hi, is there a way to call a transaction? Specifically, I need to call the MB52, this transaction is described as "List of Warehouse Stocks on Hand".

**Comment by bsrdjan** [comment]
Calling ABAP transactions direct from Python is not possible using SAP NWRFC SDK and Python PyRFC wrapper (same for Java/NodeJS). Only RFC enabled ABAP function modules can be called from Python.

To run the MB52 transaction logic from Python, the business logic of the transaction shall be exposed via RFC enabled function modules and some RFC function modules might be already available (search for "MB52 BAPI" for example, see https://answers.sap.com/questions/4047404/bapi-for-stock-report-like-mb52-or-mmbe.html ). You can ask the question on SAP Community Network for example or ABAP developer can find and expose required function modules for Python/PyRFC consumption.
