### ISSUE TITLE
Install on Python 3.8.0

### ISSUE THREAD

**Issue by rgxcustom** [SAP/PyRFC#125]
Not able to install on:
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

I tried with this:
pip install pyrfc-1.9.98-cp37-cp37m-win_amd64.whl

but I get:
ERROR: pyrfc-1.9.98-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

Thanks!

**Comment by JccSanabria** [comment]
Try using python 3.7, the number next to 'cp' indicates the python version for which the pyrfc file has been released for.

**Comment by rgxcustom** [comment]
It works using python 3.7, thanks!
