### ISSUE TITLE
Wrong behavior of RAW data type

### ISSUE THREAD

**Issue by Pentusha** [SAP/PyRFC#13]
Hello. I tried to call abap function with RAW import param IM_XSTR and piped export param EX_XSTR.
```abap
FUNCTION zsr_mp_datatypes_inout .
  DEFINE mov_fld.
    ex_&1 = im_&1.
  END-OF-DEFINITION.
  ...
  mov_fld xstr.
  ...
  REFRESH et_datatypes.
  APPEND LINES OF it_datatypes TO et_datatypes.
ENDFUNCTION.
```

```python
from pyrfc import Connection
conn = Connection(...)
response = conn.call('ZSR_MP_DATATYPES_INOUT', IM_XSTR=bytes(range(256)))
```
```
request.params['IM_XSTR'] = {bytes} b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x8
response.data['EX_XSTR'] = {bytes} b'\x00\x01\x02\x03\x04\x05\x06\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
```
I found that pyrfc got an issue with some bytes like \x08, \x12, \x21 etc.
I check value in SAP remote debugger and it confirm that is pyrfc issue.
![sap_gui_debugger](https://cloud.githubusercontent.com/assets/1904496/12780953/4b03028a-ca82-11e5-9133-de2875d652d9.png)

**Comment by bsrdjan** [comment]
I could not reproduce the issue. Here the test ABAP function I used:
```abap
FUNCTION ZSR_MP_DATATYPES_INOUT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_XSTR) TYPE  XSTRING
*"  EXPORTING
*"     VALUE(EX_XSTR) TYPE  XSTRING
*"----------------------------------------------------------------------

MOVE IM_XSTR TO EX_XSTR.

ENDFUNCTION.
```
called by test Python script:
```python

# -*- coding: utf-8 -*-
  
from abapsystems import *
  
_, c = get_connection(E1Q)
  
L = 256

instr = bytes(range(L))
outstr = c.call('ZSR_MP_DATATYPES_INOUT', IM_XSTR = instr)['EX_XSTR']

for i in range(L):
    if instr[i] != outstr[i]:
        print 'diff at %u' % i, instr[i], outstr[i]
```

Could you please test if this example works on your platform ? If the issue still occurs, could you please send me:
- The full source of the ABAP function module, including the signature
- The Python test script
- The platform on which you are testing (Windows/Linux) ?
- The versions of
  - Python
  - PyRFC 
  - SAP NW RFC Lib version - the output of 
```python
from pyrfc import *
print get_nwrfclib_version()
``` 

Thanks and regards,
srdjan

**Comment by Pentusha** [comment]
Not sure that I could use "abapsystems" module, just because I don't know where to get it, so I wrote similar code with pyrfc module.
I've got no issue with XSTRING type.
My abap function and python script:
```abap
FUNCTION ZSR_MP_ARGS_INOUT_RAW255 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_XSTR) TYPE  ZSRE_MP_RAW255
*"  EXPORTING
*"     VALUE(EX_XSTR) TYPE  ZSRE_MP_RAW255
*"----------------------------------------------------------------------
  ex_xstr = im_xstr.

ENDFUNCTION.
```
![selection_005](https://cloud.githubusercontent.com/assets/1904496/12976716/2b21f326-d0d7-11e5-94fb-684a11e4c162.png)

```python
from platform import system, release
from pyrfc import Connection, get_nwrfclib_version
from sys import version_info


conn = Connection(
    ashost='...',
    sysnr='00',
    client='001',
    user='...',
    passwd='...',
    lang='EN',
)


print('Platform:', system(), release())
print('Python version:', version_info)
print('SAP NW RFC:', get_nwrfclib_version())
print('PyRFC:', open('PyRFC/VERSION').read())


if version_info[0] == 3:
    byte_type = bytes
else:
    byte_type = bytearray


for start_range in range(256):
    input_raw = byte_type(range(start_range, 256))
    response = conn.call('ZSR_MP_ARGS_INOUT_RAW255', IM_XSTR=input_raw)
    output_raw = response['EX_XSTR']

    diff = tuple('%02X' % in_byte for in_byte, out_byte in
                 zip(input_raw, output_raw) if in_byte != out_byte)
    if diff:
        print(''.join(diff).rjust(512))
```
My system info:
```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```
python 2.7 & python 3.4 output: 
https://gist.github.com/Pentusha/74022d45d368021e760f

Screenshot of SAP GUI with same function call.
![selection_004](https://cloud.githubusercontent.com/assets/1904496/12976773/87ff7b2c-d0d7-11e5-9340-44ec43897213.png)

**Comment by bsrdjan** [comment]
Thanks for the good and detailed example. I reproduced the issue and [fixed in the master branch](https://github.com/SAP/PyRFC/commit/452d3684557cbfca96d132fd55ef7b98631bd6fe).

You may test using the Linux 64 egg I just pushed in the `/dist` folder. 

The problem was that only first 8 bytes from the input RAW parameter were copied from the RFC container and echoed back. Could you please test and let me know if the fix works in your case?

Using `bytes` type did not work as I expected for me, on Python 2.7.6, but exactly as described in this [stackoverflow question](http://stackoverflow.com/questions/5901706/the-bytes-type-in-python-2-7-and-pep-358). 

`test_issue13.py` script in `/tests` is testing therefore both the `bytes` and `bytearray` types, with both the RAW and XSTRING types.

Here my test ABAP FM:

```abap
FUNCTION zpyrfc_test_raw255.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IRAW255) TYPE  RAW255
*"     VALUE(IXSTR) TYPE  XSTRING
*"  EXPORTING
*"     VALUE(ORAW255) TYPE  RAW255
*"     VALUE(OXSTR) TYPE  XSTRING
*"----------------------------------------------------------------------

  MOVE iraw255 TO oraw255.

  MOVE ixstr TO oxstr.

ENDFUNCTION.```

**Comment by Pentusha** [comment]
I build pyrfc for python 3.4 and 2.7 and check both of them. With `bytearray` everything works as it should. Thank you.
