### ISSUE TITLE
Unable to install PyRFC

### ISSUE THREAD

**Issue by blobbybadger** [SAP/PyRFC#133]
1) The links in the README.md file are not up to date

`wget https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.97-cp37-cp37m-macosx_10_14_x86_64.whl`

2) Installation does not work

`$ python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/pyrfc
copying src/pyrfc/_exception.py -> build/lib.linux-x86_64-3.6/pyrfc
copying src/pyrfc/__init__.py -> build/lib.linux-x86_64-3.6/pyrfc
running build_ext
building 'pyrfc._pyrfc' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
creating build/temp.linux-x86_64-3.6/src/pyrfc
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -DSAPwithTHREADS -DSAPonLIN -I/usr/include/python3.6m -c src/pyrfc/_pyrfc.cpp -o build/temp.linux-x86_64-3.6/src/pyrfc/_pyrfc.o -Wall -O2 -fexceptions -funsigned-char -fno-strict-aliasing -Wall -Wno-uninitialized -Wcast-align -fPIC -pthread -minline-all-stringops -I/usr/local/sap/nwrfcsdk/include
src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_fillVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, PyObject*, RFC_TYPE_DESC_HANDLE)’:
src/pyrfc/_pyrfc.cpp:21434:22: error: ‘RfcSetInt8’ was not declared in this scope
         __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo));
                      ^~~~~~~~~~
src/pyrfc/_pyrfc.cpp:21434:22: note: suggested alternative: ‘RfcSetInt2’
         __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo));
                      ^~~~~~~~~~
                      RfcSetInt2
src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_wrapVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, unsigned int, RFC_TYPE_DESC_HANDLE, PyObject*)’:
src/pyrfc/_pyrfc.cpp:26857:18: error: ‘RfcGetInt8’ was not declared in this scope
     __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo));
                  ^~~~~~~~~~
src/pyrfc/_pyrfc.cpp:26857:18: note: suggested alternative: ‘RfcGetInt2’
     __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo));
                  ^~~~~~~~~~
                  RfcGetInt2
In file included from src/pyrfc/_pyrfc.cpp:675:0:
/usr/local/sap/nwrfcsdk/include/sapuc.h: At global scope:
/usr/local/sap/nwrfcsdk/include/sapuc.h:853:24: warning: ‘sccsidU16’ defined but not used [-Wunused-variable]
   static const SAP_UC* sccsidU16 = NULL;
                        ^~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

`$ pip3 freeze
alabaster==0.7.12
asn1crypto==1.0.1
astroid==2.3.1
atomicwrites==1.3.0
attrs==19.3.0
Automat==0.6.0
autopep8==1.4.4
Babel==2.7.0
backcall==0.1.0
bcrypt==3.1.7
blinker==1.4
cached-property==1.5.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
click==6.7
cloud-init==19.2
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.7
cx-Oracle==7.2.3
Cython==0.29.13
datashape==0.5.2
decorator==4.4.1
distro-info===0.18ubuntu0.18.04.1
docker==3.7.3
docker-compose==1.24.1
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.15.2
gitdb2==2.0.6
GitPython==3.0.3
httplib2==0.9.2
hyperlink==17.3.1
idna==2.8
imagesize==1.1.0
importlib-metadata==0.23
incremental==16.10.1
ipython==7.9.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.3
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
lazy-object-proxy==1.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.2.0
multipledispatch==0.6.0
netifaces==0.10.4
networkx==2.4
numpy==1.17.3
oauthlib==2.0.6
packaging==19.2
PAM==0.4.2
pandas==0.25.2
paramiko==2.6.0
parso==0.5.1
pbr==1.10.0
pexpect==4.7.0
pickleshare==0.7.5
pluggy==0.13.0
prompt-toolkit==2.0.10
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycodestyle==2.5.0
pycparser==2.19
pycrypto==2.6.1
Pygments==2.4.2
pygobject==3.26.1
PyJWT==1.5.3
pylint==2.4.2
PyMySQL==0.9.3
PyNaCl==1.3.0
pyodbc==4.0.27
pyOpenSSL==17.5.0
pyparsing==2.4.2
pyserial==3.4
pytest==5.2.2
python-apt==1.6.4
python-dateutil==2.8.0
python-debian==0.1.32
pytz==2019.3
pyxdg==0.25
PyYAML==3.13
requests==2.22.0
requests-unixsocket==0.1.5
SecretStorage==2.3.1
Send2Trash==1.5.0
service-identity==16.0.0
six==1.12.0
smmap2==2.0.5
snowballstemmer==2.0.0
Sphinx==2.2.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
SQLAlchemy==1.3.10
sqlalchemy-migrate==0.9.7
SQLAlchemy-Utils==0.30.9
sqlparse==0.3.0
ssh-import-id==5.7
systemd-python==234
Tempita==0.5.2
texttable==0.9.1
toolz==0.10.0
tqdm==4.36.1
traitlets==4.3.3
Twisted==17.9.0
typed-ast==1.4.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.6
wcwidth==0.1.7
websocket-client==0.56.0
wrapt==1.11.2
zipp==0.6.0
zope.interface==4.3.2`

`$ python3 --version
Python 3.6.8`

`$ uname -a
Linux USDXMCUAYR 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

`$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by bsrdjan** [comment]
Thanks, updated [Installation](https://github.com/SAP/PyRFC#installation)

**Comment by blobbybadger** [comment]
But that does not explain why my install is failing. Do I need to be on Python version 3.7 or can I stay on 3.6?

**Comment by bsrdjan** [comment]
Added Python 3.6 wheels

**Comment by blobbybadger** [comment]
Thanks. Now when I import pyrfc I get 

`$ python3 test.py
Segmentation fault (core dumped)`

`$ gdb python3
GNU gdb (Ubuntu 8.1-0ubuntu3.1) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...Reading symbols from /usr/lib/debug/.build-id/5b/7c53833c86251550093f34b4abed71d12d043d.debug...done.
done.
(gdb) run test.py
Starting program: /usr/bin/python3 test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffffb7662a9 in GlobalError::PushToStack() () from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0`

**Comment by bsrdjan** [comment]
Linux wheels are not universal and not necessarily work on each Linux platform.

Did you try cloning the current master and building from source?

**Comment by blobbybadger** [comment]
I am used to installing via pip but I have no idea how to install it from source.

**Comment by bsrdjan** [comment]
Build from source is described in the documentation, hyperlinked in the README [Installation](https://github.com/SAP/PyRFC#installation) section:

http://sap.github.io/PyRFC/build.html

**Comment by blobbybadger** [comment]
Doing what is described on the build page gives me ‘ $ python3 setup.py bdist_wheel running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-3.6 creating build/lib.linux-x86_64-3.6/pyrfc copying src/pyrfc/_exception.py -> build/lib.linux-x86_64-3.6/pyrfc copying src/pyrfc/__init__.py -> build/lib.linux-x86_64-3.6/pyrfc running build_ext building 'pyrfc._pyrfc' extension creating build/temp.linux-x86_64-3.6 creating build/temp.linux-x86_64-3.6/src creating build/temp.linux-x86_64-3.6/src/pyrfc x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -DSAPwithTHREADS -DSAPonLIN -I/usr/include/python3.6m -c src/pyrfc/_pyrfc.cpp -o build/temp.linux-x86_64-3.6/src/pyrfc/_pyrfc.o -Wall -O2 -fexceptions -funsigned-char -fno-strict-aliasing -Wall -Wno-uninitialized -Wcast-align -fPIC -pthread -minline-all-stringops -I/usr/local/sap/nwrfcsdk/include src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_fillVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, PyObject*, RFC_TYPE_DESC_HANDLE)’: src/pyrfc/_pyrfc.cpp:21434:22: error: ‘RfcSetInt8’ was not declared in this scope __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo)); ^~~~~~~~~~ src/pyrfc/_pyrfc.cpp:21434:22: note: suggested alternative: ‘RfcSetInt2’ __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo)); ^~~~~~~~~~ RfcSetInt2 src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_wrapVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, unsigned int, RFC_TYPE_DESC_HANDLE, PyObject*)’: src/pyrfc/_pyrfc.cpp:26857:18: error: ‘RfcGetInt8’ was not declared in this scope __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo)); ^~~~~~~~~~ src/pyrfc/_pyrfc.cpp:26857:18: note: suggested alternative: ‘RfcGetInt2’ __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo)); ^~~~~~~~~~ RfcGetInt2 In file included from src/pyrfc/_pyrfc.cpp:675:0: /usr/local/sap/nwrfcsdk/include/sapuc.h: At global scope: /usr/local/sap/nwrfcsdk/include/sapuc.h:853:24: warning: ‘sccsidU16’ defined but not used [-Wunused-variable] static const SAP_UC* sccsidU16 = NULL; ^~~~~~~~~ error: command 'x86_64-linux-gnu-gcc' failed with exit status 1’

**Comment by bsrdjan** [comment]
Did you clone the repository from current master and could you please check if RfcSetInt8 declared in your `src/pyrfc/csapnwrfc.pxd` at line 259, like in a master branch:

https://github.com/SAP/PyRFC/blob/master/src/pyrfc/csapnwrfc.pxd#L259

**Comment by blobbybadger** [comment]
Yes, I did pull the latest version from GitHub. And yes I do see RfcSetInt8 declared.

`src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_fillVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, PyObject*, RFC_TYPE_DESC_HANDLE)’:
src/pyrfc/_pyrfc.cpp:21434:22: error: ‘RfcSetInt8’ was not declared in this scope
         __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo));
                      ^~~~~~~~~~
src/pyrfc/_pyrfc.cpp:21434:22: note: suggested alternative: ‘RfcSetInt2’
         __pyx_v_rc = RfcSetInt8(__pyx_v_container, __pyx_v_cName, __pyx_t_22, (&__pyx_v_errorInfo));
                      ^~~~~~~~~~
                      RfcSetInt2
src/pyrfc/_pyrfc.cpp: In function ‘PyObject* __pyx_f_5pyrfc_6_pyrfc_wrapVariable(RFCTYPE, RFC_FUNCTION_HANDLE, SAP_UC*, unsigned int, RFC_TYPE_DESC_HANDLE, PyObject*)’:
src/pyrfc/_pyrfc.cpp:26857:18: error: ‘RfcGetInt8’ was not declared in this scope
     __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo));
                  ^~~~~~~~~~
src/pyrfc/_pyrfc.cpp:26857:18: note: suggested alternative: ‘RfcGetInt2’
     __pyx_v_rc = RfcGetInt8(__pyx_v_container, __pyx_v_cName, (&__pyx_v_int8Value), (&__pyx_v_errorInfo));
                  ^~~~~~~~~~
                  RfcGetInt2
In file included from src/pyrfc/_pyrfc.cpp:675:0:
/usr/local/sap/nwrfcsdk/include/sapuc.h: At global scope:
/usr/local/sap/nwrfcsdk/include/sapuc.h:853:24: warning: ‘sccsidU16’ defined but not used [-Wunused-variable]
   static const SAP_UC* sccsidU16 = NULL;
                        ^~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by bsrdjan** [comment]
Could it be you are using the older version of SAP NW RFC SDK, without INT8 support?

The latest version can be downloaded from SAP Service Portal:

https://launchpad.support.sap.com/#/softwarecenter/template/products/_APP=00200682500000001943&_EVENT=DISPHIER&HEADER=Y&FUNCTIONBAR=N&EVENT=TREE&NE=NAVIGATE&ENR=01200314690100002214&V=MAINT

**Comment by blobbybadger** [comment]
I managed to get it to work by downloading 1.9.7 https://github.com/SAP/PyRFC/releases/tag/1.9.7.

**Comment by bsrdjan** [comment]
INT8 is added with [1.9.95](https://github.com/SAP/PyRFC/releases/tag/1.9.95).

If you use the older NWRFC SDK, without INT8, the latest PyRFC which might work for you is [1.9.93](https://github.com/SAP/PyRFC/releases/tag/1.9.93).

Please feel free to close if no further questions.
