### ISSUE TITLE
Split fillVariable() into 12 methods

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#135]
I just tried to understand where `rc` gets set to a non-ok value.

But reading this method is no fun: https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L1682

Please cut this big method into smaller parts. For each type one method. I guess this will mean 12 new methods. But this would make the code more simple and easier to understand.

What do you think?

**Comment by bsrdjan** [comment]
Yes, it could make sense for future re-factorings, not planned for now.
