### ISSUE TITLE
sitecustomize.py needed?

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#136]
Why does this file exist? https://github.com/SAP/PyRFC/blob/master/sitecustomize.py

A sitecustomize file gets loaded during interpreter start up.

I library (like pyrfc is) should not provide a sitecustomize file.

If you want to execute code during interpreter start up (which is normally not needed), then you could use .pth files

**Comment by bsrdjan** [comment]
The pyrfc does not "provide" sitecustomizing, it is not a part of the wheel. The hook was used for building on specific configurations, on older Windows releases. It does not do any harm and can be removed, archived in 1.9.99 release.
