### ISSUE TITLE
ET_RETURN NUMBER (RFCTYPE_NUM) AttributeError: 'int' object has no attribute 'encode' on 

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#139]
If I use an integer (in Python) for field type RFCTYPE_NUM I get this exception:

![image](https://user-images.githubusercontent.com/414336/68023626-f912af00-fca7-11e9-9397-783daeb7f8ea.png)

```
  File "src/pyrfc/_pyrfc.pyx", line 414, in pyrfc._pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 1649, in pyrfc._pyrfc.fillFunctionParameter
  File "src/pyrfc/_pyrfc.pyx", line 1700, in pyrfc._pyrfc.fillVariable
  File "src/pyrfc/_pyrfc.pyx", line 1676, in pyrfc._pyrfc.fillTable
  File "src/pyrfc/_pyrfc.pyx", line 1661, in pyrfc._pyrfc.fillStructureField
  File "src/pyrfc/_pyrfc.pyx", line 1726, in pyrfc._pyrfc.fillVariable
  File "src/pyrfc/_pyrfc.pyx", line 1852, in pyrfc._pyrfc.fillString
AttributeError: 'int' object has no attribute 'encode'
```

After reading a bit about this I guess that RFCTYPE_NUM is a **string** which only contains numbers.

It would be very convenient if PyRFC could handle the magic conversion. If a user of pyrfc uses an integer the lib should automatically create a string from this value.

What do you think?

**Comment by bsrdjan** [comment]
The same as with None, there are users appreciating strict type check, catching integers unintentionally passed as Numerics. The PyRFC works in this "strict" mode and "magic" like integers to numerics conversion can be added at application level. Providing optional support for multiple Python types per ABAP type would increase the complexity and troubleshooting.

**Comment by guettli** [comment]
OK, I don't want magic int-to-string or string-to-int conversion, too.

But I like easy to understand error messages.

Hint: I guess for most developers (which never used ABAP), "numeric" means "integer".

A message like "A string containing only numeric characters is required. You provided type ..." would be nice.

**Comment by bsrdjan** [comment]
More informative error message added.
