### ISSUE TITLE
error in the installation guide

### ISSUE THREAD

**Issue by fjpavon** [SAP/PyRFC#14]
Hi, thanks for your job. I don't know if it's a problem but i was following the instructions to install pyrfc but seems like the egg files are not available in the packages directory. I was looking for in https://pypi.python.org/pypi but there is no package. It's build with sources the only way available to install pyrfc?
Thanks and kind regards
Francisco Pavon

**Comment by bsrdjan** [comment]
Hi Francisco,

egg files are for now available only in the `/dist` directory of this repository and `easy_install` should work as well, as [documented here](http://sap.github.io/PyRFC/install.html). 

Distributing platform specific Python extension seems to go in the direction of using `wheels` mechanism and [until that method works on Linux](http://lucumr.pocoo.org/2014/1/27/python-on-wheels/), currently supported install methods remain all we have. Building from source, following the documenation, should not be  a big challenge either. 

Hope this helps,
srdjan

**Comment by fjpavon** [comment]
Thanks for your response, was my mistake. I didn't understand well the location of the directory.
Sorry
