### ISSUE TITLE
Python 3.6 gets dropped?

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#140]
> Python 3.8 wheels added, 3.6 and 3.5 dropped
Source: https://github.com/SAP/PyRFC/releases/tag/1.9.99

The support for Python 3.6 gets dropped?

I think this a bit too fast. This version is still very wide spread. AFAIK it is supported until 2021-12.

**Comment by bsrdjan** [comment]
Yes it was, already added back per users' requests.
