### ISSUE TITLE
pyrfc.Connection failed with "Conversion error between two character sets"

### ISSUE THREAD

**Issue by georgik** [SAP/PyRFC#141]
pyRFC version 1.9.99, Python 3.7, OS Windows 10.

Invoke of Connection(**params) to some server works (e.g. miniSAP and test env) and Connection to other servers (e.g. some production) fails with following error:
```
Traceback (most recent call last):
 ...
  File "src/pyrfc/_pyrfc.pyx", line 181, in pyrfc._pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 239, in pyrfc._pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 269, in pyrfc._pyrfc.Connection._error
pyrfc._exception.ABAPRuntimeError: RFC_ABAP_RUNTIME_FAILURE (rc=3): key=RFC_CONVERSION_FIELD, message=Conversion error between two character sets. [MSG: class=, type
=, number=, v1-4:=;;;]
```

I would appreciate any hint what could be wrong.

**Comment by bsrdjan** [comment]
The error usually indicates a gap in unicode/non-unicode configuration, on client and server side.

You could compare settings on working ABAP server with settings on non-working ABAP server, like

**Extras -> System information -> Target system -> "Character set"**
<img width="470" alt="Target" src="https://user-images.githubusercontent.com/1697847/68113314-d83e9980-fef3-11e9-9455-11c1d8a63ca4.png">

and **ABAP Connection Settings**, in SM59 transaction in ABAP system:
<img width="576" alt="SM59" src="https://user-images.githubusercontent.com/1697847/68113380-03c18400-fef4-11e9-8d8e-69d87aba78c0.png">

Above figures show one standard working configuration. Perhaps changed in affected system for some reason?

**Comment by georgik** [comment]
Thank you very much for the advice. It helped a lot.
Which doc/*.rst file is the best to include this information?
I can prepare PR for that.

**Comment by bsrdjan** [comment]
Sorry for the longer waiting, a section could be added here: http://sap.github.io/PyRFC/install.html#problems

Could be helpful for more miniSAP users.

**Comment by shrirang3010** [comment]
How can we use pyrfc.connection() for python3?

**Comment by bsrdjan** [comment]
> How can we use pyrfc.connection() for python3?

https://github.com/SAP/PyRFC#getting-started
