### ISSUE TITLE
Cannot convert string value 1.1 at position 1 for the field RFCFLOAT to type RFCTYPE_FLOAT

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#142]
This snippet works:
```python
# -*- coding: utf-8 -*
from __future__ import absolute_import, division, print_function, unicode_literals

from pyrfc import Connection

conn = Connection(...)

#import django
#django.setup()

result = conn.call(b'STFC_STRUCTURE', **{"IMPORTSTRUCT": {"RFCFLOAT": 1.1}})
print(result)
```

But if I uncomment the two django-lines, then it fails with this exception:

```
Traceback (most recent call last):
  File "tmp/float-error.py", line 11, in <module>
    result = conn.call(b'STFC_STRUCTURE', **{"IMPORTSTRUCT": {"RFCFLOAT": 1.1}})
  File "src/pyrfc/_pyrfc.pyx", line 415, in pyrfc._pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 1650, in pyrfc._pyrfc.fillFunctionParameter
  File "src/pyrfc/_pyrfc.pyx", line 1700, in pyrfc._pyrfc.fillVariable
  File "src/pyrfc/_pyrfc.pyx", line 1662, in pyrfc._pyrfc.fillStructureField
  File "src/pyrfc/_pyrfc.pyx", line 1805, in pyrfc._pyrfc.fillVariable
pyrfc._exception.ExternalRuntimeError: RFC_CONVERSION_FAILURE (rc=22): key=RFC_CONVERSION_FAILURE, message=Cannot convert string value 1.1 at position 1 for the field RFCFLOAT to type RFCTYPE_FLOAT [MSG: class=, type=, number=, v1-4:=;;;]
```

Python 2.7

This is very strange, since importing django and calling `django.setup()` should not have any side-effects.

I am running the latest version of PyRFC (master from github).

**Comment by bsrdjan** [comment]
I could not reproduce with clean django settings:

```python
import django # v 1.11.26 
from django.conf import settings
settings.configure()
django.setup()

print(pyrfc.__version__)
```

Could you please check if the issue happens with default django settings, like above? 

If default settings works, I would start from activating your django application settings step by step, to localise the root cause.

**Comment by guettli** [comment]
I found what influences the way pyRFC works: **locale** 

Insteand of importing django there is a simple way to force the error:

```python
import locale
locale.setlocale(locale.LC_ALL, b'de_DE.UTF-8')
```

I hope you can reproduce it now.

I would suggest pyRFC avoids using the locale.

**Comment by guettli** [comment]
@bsrdjan  Hi Sdrjan could you reproduce the error after setting the locale?

**Comment by bsrdjan** [comment]
Could you please check if the fix, works for your use-case? Float and Decimal are always accepted and strings only when decimal separator is correct, for the application locale. Grouping separators are not supported, application should handle.

Unit tests: [test_datatypes.py#L618](https://github.com/SAP/PyRFC/blob/master/tests/test_datatypes.py#L618)

**Comment by guettli** [comment]
@bsrdjan yes, I installed pyrfc from git master and the float issue is gone now. Thank you very much!

**Comment by yscoder310** [comment]
can you @bsrdjan  please provide any example code how you input decimal value cause I am keep on geeting this error
[<class 'decimal.ConversionSyntax'>]
