### ISSUE TITLE
Connection With Saprouter Error

### ISSUE THREAD

**Issue by pmwikya** [SAP/PyRFC#149]
Hi,

Need some help, when I connect with the parameters below I get the error show below it. But When I niping with the same parameters I am successful. The connection method does not append properly the final part of the string.

**conn = Connection( mshost = '172.xx.xx.57' ,     
                   client='DS1', 
                   msserv='3201',
                   user='username',                   
                   passwd='userpassword',                  
                   saprouter='/H/19x.x.xxx.2/S/3299')**

I get the error :

CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       The message received isn't from a message server.
            Are you really connected to the message server?
            Please check your connection parameters.
            **(/H/19x.x.xxx.2/S/3299/H/172.xx.xx.57 / 3201)**
TIME        Fri Nov 29 11:40:03 2019
RELEASE     753
COMPONENT   MS (message handling interface, multithreaded)
VERSION     4
RC          -29
MODULE      D:/depot/bas/753_REL/src/krn/ms/msxxi.c
LINE        382
COUNTER     17 [MSG: class=, type=, number=, v1-4:=;;;]

For Niping I use : 
niping -c -H /H/19x.x.xxx.2/S/3299/H/172.xx.xx.57/S/3201

And I get:  connect to server o.k.

**Comment by bsrdjan** [comment]
The client parameter must be three digit numerical value.
