### ISSUE TITLE
Error: max no of 200 conversations exceeded

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#150]
I am getting this error:

    Traceback (most recent call last):
    ...
      File "/.../sap_connection.py", line 486, in get_connection
        return Connection(**get_connection_dict(contact_host))
      File "src/pyrfc/_pyrfc.pyx", line 182, in pyrfc._pyrfc.Connection.__init__
      File "src/pyrfc/_pyrfc.pyx", line 226, in pyrfc._pyrfc.Connection._open
      File "src/pyrfc/_pyrfc.pyx", line 256, in pyrfc._pyrfc.Connection._error
    pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
    LOCATION    CPIC (TCP/IP) on local host with Unicode
    ERROR       max no of 200 conversations exceeded
    TIME        Wed Dec  4 13:53:22 2019
    RELEASE     753
    COMPONENT   CPIC (TCP/IP) with Unicode
    VERSION     3
    RC          466
    MODULE      /bas/753_REL/src/krn/si/cpic/r3cpic.c
    LINE        15830
    COUNTER     201
     [MSG: class=, type=, number=, v1-4:=;;;]

Up to now I create a lot Connection instances and never explicitly close them.

If the Python process starts again (via linux cron job), then the RFC call works fine.

What should I do: 

 * close the Connection explicitly?
 * reuse the Connection?
 * something else?

**Comment by bsrdjan** [comment]
Why not close by `client.close()` method?

**Comment by mkysoft** [comment]
There are SAP notes exists about this error. It says there is limit on server side and you need to limit your client. [Note 316877](https://launchpad.support.sap.com/#/notes/316877) included server side parameter for increasing size.

**Comment by bsrdjan** [comment]
PyRFC is not "auto closing" by default and multiple RFC calls can be done from Python, within the same ABAP session. Like calling BAPI COMMIT after BAPI CREATE (stateful scenario). 

For "auto close" (stateless) scenario, a simple connection pool can be added at application level. Python application requests the connection from the pool, executes the RFC call and than returns the connection to pool, which can close (stateless) or not (stateful). Pools are available for nodejs and Java RFC connectors and could be the same way added to PyRFC. For now the application can do that.

**Comment by guettli** [comment]
I use this StatelessConnection now:

    from pyrfc import Connection
    class StatelessConnection(Connection):
        def call(self, rfc_name, **kwargs):
            try:
                return super(StatelessConnection, self).call(rfc_name, **kwargs)
            finally:
                self.close()

The performance might be a bit lower, but it makes the overall handling a lot easier.

@bsrdjan  what do you think? Is this a feasible solution?

**Comment by guettli** [comment]
... I compared the performance. How much do you loose if you close the connection after every call?

    for i in range(1000):
        #conn.close()
        print(i, conn.call('RFC_PING'))

The duration was equal on my system (with "close()" and without "close()": 28 seconds.

Maybe it would make sense to make StatelessConnection the default in PyRFC?

**Comment by bsrdjan** [comment]
PyRFC has no default mode, the ABAP RFC protocol itself preserves the ABAP session across subsequent calls (ABAP stateful). Applications or single RFC calls in ABAP stateless mode, can of course use the class like StatelessConnection (looks perfectly good to me). PyRFC makes no default here, only exposes the RFC protocol as it is and applications can easy switch to ABAP stateless, if needed. In real-life applications, Pool layer is anyway required, creating pre-defined number of open connections, ready to be consumed by application, with or without closing after RFC call completed.
That way the client gets the connection immediately, without waiting for opening handshake and auto-close optional parameter can be provided. Hope to add Pool with optional auto-close (stateless) one day, when more capacity available. Contributions however welcome. PyRFC based web applications are so far ABAP stateful, no user-requirements for stateless.

**Comment by guettli** [comment]
@bsrdjan could you please elaborate this:

> In real-life applications, Pool layer is anyway required,

Why is this required? What happens, if you don't use a pool layer?

**Comment by bsrdjan** [comment]
Non-trivial applications work with more than one connection in parallel and the number of active connections (transferring data) changes dynamically. Depending on network, a handshake while opening a connection may be slower, compared to fast data transfer later on. Applications can therefore open the number (a threshold) of connections in advance and provide already open connection immediately, when needed. Auto-close, timeouts (idle too long, call too long ...) can be added on top, also the monitoring etc. It makes sense to encapsulate/reuse this functionality across applications, calling it "pool" or anyhow. Without pool nothing critical happens, especially in single connection applications. More demanding applications benefit from pool, following [DRY rather than WET](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by guettli** [comment]
Cloud native is new to me, too. I thought in cloud native the pool are the containers. You have a pool of containers. Maybe a connection pool is not needed any more? But that's just a vague guess.

**Comment by bsrdjan** [comment]
It is up to application do decide, PyRFC makes no assumptions if needed or not. Regarding original issue, please check also [SAP OSS Note 1507034 - Max number of gateway connections / Maximum number of conversations exceeded ](https://launchpad.support.sap.com/#/notes/1507034), for how to adjust server settings.

**Comment by guettli** [comment]
I can't access the link you send me. (SAP Note 150...) It does not work for me.

**Comment by mkysoft** [comment]
@guettli you need S-ID for access SAP notes.

**Comment by guettli** [comment]
PyRFC is open source?

**Comment by mkysoft** [comment]
> PyRFC is open source?

Yes it is open source, but it is working with SAP. This PyRFC is only an interface for RFC SDK library. RFC SDK included dll files to connect SAP system with RFC protocol.   

You can get your own S-ID with company email address which is using SAP products or partner. You can ask to BASIS team for it.

The referenced SAP note said that change CPIC_MAX_CONV parameter for increasing connection limit. So there will be always a limit for connection on server side, you need to pooling it on client side.

**Comment by guettli** [comment]
I don't have a company email address which is using SAP products or partner (any more).

**Comment by bsrdjan** [comment]
Which ABAP backend do you use? [Minisap](https://go.support.sap.com/minisap/#/minisap) ?

**Comment by guettli** [comment]
@bsrdjan I moved. I am not working with SAP any more.

**Comment by SebastianSiolkowski** [comment]
In my case I just define a class where in __init__ I have a RFC connection, then a simple function inside this class just for calling RFC with parameters: table, fields to be returned, query (options). 
Then when you create a instance of above class and use the calling function you will still use only 1 connection, so the error with limit 200 will not pop-up. I hope that will help

**Comment by SebastianSiolkowski** [comment]
In my case I just define a class where in __init__ I have a RFC connection, then a simple function inside this class just for calling RFC with parameters: table, fields to be returned, query (options). 
Then when you create a instance of above class and use the calling function you will still use only 1 connection, so the error with limit 200 will not pop-up. I hope that will help

**Comment by SebastianSiolkowski** [comment]
In my case I just define a class where in __init__ I have a RFC connection, then a simple function inside this class just for calling RFC with parameters: table, fields to be returned, query (options). 
Then when you create a instance of above class and use the calling function you will still use only 1 connection, so the error with limit 200 will not pop-up. I hope that will help

**Comment by SebastianSiolkowski** [comment]
In my case I just define a class where in __init__ I have a RFC connection, then a simple function inside this class just for calling RFC with parameters: table, fields to be returned, query (options). 
Then when you create a instance of above class and use the calling function you will still use only 1 connection, so the error with limit 200 will not pop-up. I hope that will help
