### ISSUE TITLE
cannot import name 'Connection' while connecting to SAP

### ISSUE THREAD

**Issue by manu4xever** [SAP/PyRFC#154]
I am getting the following error while connecting to SAP:
ubuntu007@ubuntu:~/sap$ python sap_test2.py
Traceback (most recent call last):
  File "sap_test2.py", line 1, in <module>
    from pyrfc import Connection
ImportError: cannot import name 'Connection'

**Comment by smartexpert** [comment]
Sounds like pyrfc is not correctly installed, what do you see when you do this?

```
import pyrfc
pyrfc.get_nwrfclib_version()
```

if not check if pyrfc is installed and what version:
`pip list --format legacy | grep pyrfc`
If it given an error like cannot import, then most likely you haven't setup pyrfc correctly. Follow the instructions on http://sap.github.io/PyRFC/install.html exactly.
```

**Comment by manu4xever** [comment]
the pyrfc works perfectly for python2.7
the problem arrises when I run it on python3.6
on running pyrfc.get_nwrfclib_version() I get: "(7500, 0, 5)"

**Comment by smartexpert** [comment]
possibly you've installed pyrfc for python 2.7 but not for python 3.6
check which python you're using
`which python`
or 
`which python3`
depending on how you've setup the alias
so assuming you're using `python3` as alias in your bash
do
`python3 -m pip install pyrfc-2.0.1-cp36-cp36m-linux_x86_64.whl`

**Comment by smartexpert** [comment]
also try `from pyrfc import *`

**Comment by manu4xever** [comment]
On bash ' from pyrfc import * ' works perfectly
But when I write from 'pyrfc import Connection' it throws the above error

**Comment by bsrdjan** [comment]
Could you please try from command line and post the output:

```shell
$ python -V 
$ python -c "from pyrfc import *"
$ python -c "from pyrfc import Connection"
```

**Comment by Piyush068-png** [comment]
ImportError: cannot import name 'Connection' from 'pyrfc' . Can you help me with this issue i am stuck in this issue from long,i am using python 3 and nwrfcsdk installation s showing fine in cmd when we execute rfcexec

**Comment by sinanakbas** [comment]
hi i am having the same issue and as far as i am concerned there wasnt any solution. When i write 

$ python -V 
$ python -c "from pyrfc import *"
$ python -c "from pyrfc import Connection"

I am receiving below answers;

C:\Windows\system32>python -V
Python 3.8.3

C:\Windows\system32>python -c "from pyrfc import *"

C:\Windows\system32>python -c "from pyrfc import Connection"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Connection' from 'pyrfc' (C:\Users\tr3107\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyrfc\__init__.py)

when i drag the file in pycharm to see whats inside i display below;

#! /usr/bin/env python
# coding: utf-8
__author__ = 'meisanggou' 

thank you.
