### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by giuseppecot** [SAP/PyRFC#155]
hi,
i have a problems with installation of PyRfc.

System: Windows 10
I met a problem during importing pyrfc.
SAP NW RFC SDK is already installed, seems to be ok.

I followed the instructions.: http://sap.github.io/PyRFC/install.html#

- SAP NW RFC SDK is already installed, seems to be ok

- set the environment variables

![image](https://user-images.githubusercontent.com/37216399/72444420-4df69980-37b0-11ea-839c-bcb57cf86176.png)

**Comment by amarvin** [comment]
Deplicate of #152

**Comment by amarvin** [comment]
Why was this Issue and its duplicates closed?
