### ISSUE TITLE
connect to SAP

### ISSUE THREAD

**Issue by ouzc12358** [SAP/PyRFC#156]
I am trying to connect SAP with python, but my situation is the company has set the user also the password into the system, so usually, we only need to click the shortcut button then we can logon to the  SAP.
here is it ，so in this case, what should I do to Logon. thanks
![image](https://user-images.githubusercontent.com/7533211/73048578-90a52980-3eb4-11ea-8063-41447199dbbc.png)

**Comment by aumas** [comment]
have you tried SSO:
https://sap.github.io/PyRFC/authentication.html

**Comment by bsrdjan** [comment]
Your system is configured for secure network communication (SNC) and you can check that by looking into "Network" tab of system properties in SAP Logon client:
<img width="427" alt="Screenshot 2020-02-27 at 09 57 29" src="https://user-images.githubusercontent.com/1697847/75427888-95dc1500-5947-11ea-9cdb-1f0c327e9bf1.png">
As described in above link, Python RFC client supports SNC but configuring SNC client requires more efforts.

**Comment by bsrdjan** [comment]
Depending on crypto library used in your environment, the connection parameters may look like in example below, based on [SAP Crypto Library](https://help.sap.com/saphelp_nwpi71/helpdata/en/7c/3f443c8c06702ee10000000a11405a/frameset.htm)

```python
from pyrfc import *

ABAP_SYSTEM = {
    'snc_lib': 'C:\Program Files\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll',
    'ashost': '10.11.12.13',
    'sysnr': '33',
    'client': '001',
    'snc_partnername': 'p:CN=I64, O=SAP-AG, C=DE',
}

c = Connection(**ABAP_SYSTEM)

print(c.get_connection_attributes())
```

**Comment by bsrdjan** [comment]
Please reopen if needed.
