### ISSUE TITLE
when I start Powershell oon windows 16 server. I get the below warnings. Earlier I tried to install IBM planning and analytics on the system. Does anyone know how to resolve it? Or in future is it going to create any problem?

### ISSUE THREAD

**Issue by manu4xever** [SAP/PyRFC#159]
new-object : Exception calling ".ctor" with "1" argument(s): "Invalid URI: Invalid port specified."
At C:\Users\admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1 char:44
+ ... twebproxy = new-object system.net.webproxy('http://YourProxyHostNameG ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'BypassProxyOnLocal' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:3 char:1
+ [system.net.webrequest]::defaultwebproxy.BypassProxyOnLocal = $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

**Comment by amarvin** [comment]
This has nothing to do with PyRFC.

**Comment by manu4xever** [comment]
@amarvin  the issue is not
