### ISSUE TITLE
Is Pyrex really needed?

### ISSUE THREAD

**Issue by amarvin** [SAP/PyRFC#160]
Would be easier to maintain this repo if the codebase was Python files (`*.py`) and not Pyrex (`*.pyx`). As few people know Pyrex, it makes it harder for people to contribute.

I see that Pyrex is a Python-like language used for writing Python extension modules with C-like syntax; may contain references to existing C modules; compiles code that increases the execution time of Python programs. Is the reduction in execution time in this case significant?

**Comment by mtolksdorf** [comment]
A pure python implementation is not feasible as there are some libraries needed that require Pyrex in order to communicate with an ABAP system. Wrapping SAP NetWeaver RFC library is the way with the lowest effort and with the most code re-use.

**Comment by bsrdjan** [comment]
PyRFC is an interface to  SAP NetWeaver SDK C++ library and Pyrex/Cython makes the Python/C++ integration work at all. Therefore inevitable for the time being although pure Python approach would simplify also cloud deployments. Execution time reduction is a nice "side-effect" of the approach.

**Comment by amarvin** [comment]
Thanks for the quick feedback!
