### ISSUE TITLE
SAP NW RFC SDK 7.50 Patch-Level 6: sapuc.h and sapucx.h have been replaced

### ISSUE THREAD

**Issue by martinsimmet** [SAP/PyRFC#161]
With patch level 6 of nwrfcsdk 7.50, The two internal headers sapuc.h and sapucx.h have been replaced with the header sapucrfc.h.

Building PyRFC from code does no longer work, as the needed include files are no longer available.

Excerpt from Release Notes:
* Enhancement: Unicode processing
The two internal headers sapuc.h and sapucx.h have been replaced with the header sapucrfc.h which corresponds exactly with the functions exported from libsapucum. Also libsapucum on some platforms now exports additional functions, which have so far been missing on these platforms.

**Comment by bsrdjan** [comment]
Thanks @martinsimmet. Fix will be shipped with next release: 0f91322f492f0c8c8acf4b40eacc2846d023d8ee

**Comment by bsrdjan** [comment]
Fixed in 2.0.2
