### ISSUE TITLE
__str__ is no longer honored by RFCTYPE_CHAR and RFCTYPE_STRING

### ISSUE THREAD

**Issue by filak-sap** [SAP/PyRFC#162]
I have created a wrapper class for XFELD aka abap_bool which is STRING in ABAP. The problem with abap_bool is that True is 'X' and False is ' ' but in Python, both values are True.

My wrapper class implements __str__ to return 'X' or ' ' accordingly. However your new check for type broke my code:
https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L1717
https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L1723

Could you please reconsider this decision.

**Comment by bsrdjan** [comment]
Sorry that I could not figure out what exactly the issue is. Could you please post the source code example?

**Comment by jfilak** [comment]
```python
class RFCBool:

    def __init__(self, value):
        self._value = 'X' if value else ' ' 

    def encode(self, *args):
        return self._value.encode(*args)

    def __str__(self):
        return self._value

    def __repr__(self):
        return 'RFCBool({})'.format(self._value)

    def __eq__(self, other):
        if isinstance(other, RFCBool):
            return self._value == other._value

        if isinstance(other, str):
            return self == RFCBool(not str.isspace())

        if isinstance(other, bool):
            return self == RFCBool(other)

        raise TypeError('Cannot compare {} with {}'.format(type(slef), type(other)))


FALSE=RFCBool(' ')
TRUE=RFCBool('X')
```

In the version 1.9.96, I can use FALS and TRUE for parameters of the type STRING (abap_bool, xfeld, etc.).

**Comment by bsrdjan** [comment]
Unfortunately there is no single ABAP domain for Boolean and different domains use different value lists. For True, mostly 'X' is used. For False, some domains use blank char, some others use hyphen char. Some domains use blank char for False and hyphen for undefined, supporting three-state Booleans.

That is why PyRFC can't handle Booleans, not even as a configurable option for all 1-char ABAP CHAR and STRING types for example. No matter which logic implemented here, would be for some applications/domains incorrect. 

What the applications is actually doing, in which context is RFCBool used?

**Comment by jfilak** [comment]
@bsrdjan Can we please ignore the fact that I need to deal with Boolean that was not standardized in ABAP until recently?

Let's focus on the fact that instances of my class cannot be used for function parameters of the STRING type.

**Comment by bsrdjan** [comment]
The example looks incorrect, regardless of PyRFC.

I see `slef` instead of `self` and the test in console shows 'X' for both values: 

```python
class RFCBool:

    def __init__(self, value):
        self._value = 'X' if value else ' ' 

    def encode(self, *args):
        return self._value.encode(*args)

    def __str__(self):
        return self._value

    def __repr__(self):
        return 'RFCBool({})'.format(self._value)

    def __eq__(self, other):
        if isinstance(other, RFCBool):
            return self._value == other._value

        if isinstance(other, str):
            return self == RFCBool(not str.isspace())

        if isinstance(other, bool):
            return self == RFCBool(other)

        raise TypeError('Cannot compare {} with {}'.format(type(slef), type(other)))

FALSE=RFCBool(' ')
TRUE=RFCBool('X')

print(FALSE)
# X
print(TRUE)
#X
```

Could you please create one example with using the class and calling the STFC_CONNECTION function module, passing the value to REQUTEXT input parameter? The class echoes the result back, in ECHOTEXT parameter.

**Comment by bsrdjan** [comment]
Please reopen if still active.
