### ISSUE TITLE
cannot open input file 'sapnwrfc.lib'

### ISSUE THREAD

**Issue by Suncatcher** [SAP/PyRFC#165]
I get this error when trying to install through PIP in Python 3.8.1

    pip3 install pynwrfc --no-binary :all:

> C:\Users\user12>pip3 install pynwrfc --no-binary :all:
Collecting pynwrfc
  Using cached pynwrfc-2.0.5.tar.gz (236 kB)
Requirement already satisfied: setuptools in c:\users\user12\appdata\local\programs\python\python38\lib\site-packages (from pynwrfc) (41.2.0)
Skipping wheel build for pynwrfc, due to binaries being disabled for it.
Installing collected packages: pynwrfc
    Running setup.py install for pynwrfc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user12\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user12\\AppData\\Local\\Temp\\pip-install-c3he8gtb\\pynwrfc\\setup.py'"'"'; __file__='"'"'C:\\Users\\user12\\AppData\\Local\\Temp\\pip-install-c3he8gtb\\pynwrfc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user12\AppData\Local\Temp\pip-record-1z77e75n\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user12\appdata\local\programs\python\python38\Include\pynwrfc'
         cwd: C:\Users\user12\AppData\Local\Temp\pip-install-c3he8gtb\pynwrfc\
    Complete output (25 lines):
    FINDSTR: Cannot open c:\nwrfcsdk\lib\sapnwrfc.dll
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.8\pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\pyrfc
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\user12\appdata\local\programs\python\python38\include -Ic:\users\user12\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj -Ic:\nwrfcsdk\include -Ic:\users\user12\appdata\local\programs\python\python38\lib\inspect.py\Include -Ic:\users\user12\appdata\local\programs\python\python38\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -GL -O2 -Oy- /we4552 /we4700 /we4789
    _pyrfc.cpp
    src/pyrfc/_pyrfc.cpp(16678): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
    src/pyrfc/_pyrfc.cpp(29611): warning C4311: 'type cast': pointer truncation from 'RFC_THROUGHPUT_HANDLE' to 'unsigned long'
    src/pyrfc/_pyrfc.cpp(29611): warning C4302: 'type cast': truncation from 'RFC_THROUGHPUT_HANDLE' to 'unsigned long'
    src/pyrfc/_pyrfc.cpp(29944): warning C4311: 'type cast': pointer truncation from 'RFC_THROUGHPUT_HANDLE' to 'unsigned long'
    src/pyrfc/_pyrfc.cpp(29944): warning C4302: 'type cast': truncation from 'RFC_THROUGHPUT_HANDLE' to 'unsigned long'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\user12\appdata\local\programs\python\python38\libs /LIBPATH:c:\users\user12\appdata\local\programs\python\python38\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" sapnwrfc.lib libsapucum.lib /EXPORT:PyInit_pyrfc build\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj /OUT:build\lib.win-amd64-3.8\pyrfc\pyrfc.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\src/pyrfc\pyrfc.cp38-win_amd64.lib -LIBPATH:c:\nwrfcsdk\lib -LIBPATH:c:\users\user12\appdata\local\programs\python\python38\lib\inspect.py\PCbuild -NXCOMPAT -STACK:0x2000000 -SWAPRUN:NET -DEBUG -OPT:REF -DEBUGTYPE:CV,FIXUP -MACHINE:amd64 -nologo -LTCG
    **LINK : fatal error LNK1181: cannot open input file 'sapnwrfc.lib'**
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user12\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user12\\AppData\\Local\\Temp\\pip-install-c3he8gtb\\pynwrfc\\setup.py'"'"'; __file__='"'"'C:\\Users\\user12\\AppData\\Local\\Temp\\pip-install-c3he8gtb\\pynwrfc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user12\AppData\Local\Temp\pip-record-1z77e75n\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user12\appdata\local\programs\python\python38\Include\pynwrfc' Check the logs for full command output.

C++ VS2019 build tools are installed. Paths are set

![Untitled](https://user-images.githubusercontent.com/6388034/77999234-03120a00-733b-11ea-908a-9e018fbf30ea.png)

What's the matter?

**Comment by bsrdjan** [comment]
Could you please check:

1. Is *sapnwrfc.lib* present in `%SAPNWRFC_HOME%\lib` folder ? User has read authorisation ? If not, reinstall SAP NWRFC SDK.

2. If SAP NWRFC SDK for Windows 64 bit platform downloaded from SAP Service Portal and installed? Not for example 32 bit or for another platform?

3. cd to `%SAPNWRFC_HOME%\bin` folder and run `rfcexec.exe`. The SAP NWRFC SDK error message about arguments should be returned, not error like "DLL could not be found/loaded"

4. Clone the PyRFC repository and run the SAP NWRFC SDK version check, from the repo root. The result should be something like:

```shell
C:\src\PyRFC>ci\utils\nwrfcsdk-version.bat
750 Patch Level 6

C:\src\PyRFC>
```

**Comment by Suncatcher** [comment]
1.   
> Is sapnwrfc.lib present in %SAPNWRFC_HOME%\lib folder ?

No, Just check another time and cannot find it

![image](https://user-images.githubusercontent.com/6388034/78130349-d5ec5700-7421-11ea-8e73-301312ee0bcd.png)

it is an official archive from launchpad.support.sap.com

![image](https://user-images.githubusercontent.com/6388034/78130377-e4d30980-7421-11ea-9d2b-114d91658752.png)

what am I doing wrong?

2. 64-bit
3. No, it also throws "rfcexec is not recognized"
 4.

     C:\src\PyRFC>ci\utils\nwrfcsdk-version.bat

gives

> FINDSTR: Cannot open c:\nwrfcsdk\lib\sapnwrfc.dll

**Comment by bsrdjan** [comment]
It look like you installed SAP NWRFC SDK for Linux platform on your Windows system.

The dropdown combo just above the "File Type" on a last screenshot, shows AIX 64 bit. To download Windows 64 bit, please select the Windows platform there. The previous screenshot shows SO libs, used on Linux, not working on Windows.

**Comment by Suncatcher** [comment]
Wow, so silly. Didn't know the binaries are different for OSes.
Thanks a ton, now it worked like a charm.

**Comment by mangesh108** [comment]
can't import connection from pyrfc
![Screenshot (148)](https://user-images.githubusercontent.com/59372057/94350948-5c03f600-0071-11eb-87cf-9aabf9a6f6a7.png)

**Comment by amarvin** [comment]
Try `from pyrfc import Connection`, as Python is case sensitive.
