### ISSUE TITLE
pyrfc._exception.ABAPApplicationError: RFC_ABAP_EXCEPTION (rc=5): key=NOT_FOUND

### ISSUE THREAD

**Issue by romanknoxy** [SAP/PyRFC#166]
pyRFC version 2.0.5, Python 3.8, OS Windows 10.

Calling of Function RSZ_DB_ELT_GET 
`result = conn.call('RSZ_DB_ELT_GET', I_TEMPLATE_TYPE='NIL', I_LANGUAGE='E', I_OBJVERS='A', I_INFOCUBE='[MYINFOPROVIDER]', I_ELTUID='[SOMEUID]')`

fails with following error:
`pyrfc._exception.ABAPApplicationError: RFC_ABAP_EXCEPTION (rc=5): key=NOT_FOUND, message=ID:DA Type:E Number:300 RZD1_TH_CALC [MSG: class=DA, type=E, number=300, v1-4:=RZD1_TH_CALC;;;]`

Any idea as to why this is happening?

**Comment by bsrdjan** [comment]
Yes, I have the same idea like in similar issue: https://github.com/SAP/PyRFC/issues/167#issuecomment-609736747

Could it be that Conversion Exits are implemented for `I_INFOCUBE` structure fields ?

**Comment by bsrdjan** [comment]
Please reopen if still active.
