### ISSUE TITLE
Pyrfc /  Getting data from SAP

### ISSUE THREAD

**Issue by saberabdelhady** [SAP/PyRFC#169]
Dear all,

Greeting,,,

now i connected to sap through pyrfc connection 
i use Ubuntu 18.04 and python3 

please 
is there any training video to Getting data from SAP
like getting data from mara or matner

**Comment by bsrdjan** [comment]
No videos or trainings to my knowledge, about using Python/RFC connector for extracting data from ABAP systems. You may search for something like "read MARA BAPI", to find the RFC function module and then use PyRFC to call it and read the data. There are many PyRFC examples/blogs, in SAP Community Network and elsewhere.
