### ISSUE TITLE
Couldn't find https://pypi.python.org/simple/pyrfc/

### ISSUE THREAD

**Issue by Sven-H-x** [SAP/PyRFC#17]
I try to install it, but I get the following error: 

C:\Python-Projects\SAP>easy_install pyrfc-1.9.4-py3.5-win-amd64.egg
Processing pyrfc-1.9.4-py3.5-win-amd64.egg
removing 'c:\program files (x86)\python35-32\lib\site-packages\pyrfc-1.9.4-py3.5
-win-amd64.egg' (and everything under it)
creating c:\program files (x86)\python35-32\lib\site-packages\pyrfc-1.9.4-py3.5-
win-amd64.egg
Extracting pyrfc-1.9.4-py3.5-win-amd64.egg to c:\program files (x86)\python35-32
\lib\site-packages
pyrfc 1.9.4 is already the active version in easy-install.pth

Installed c:\program files (x86)\python35-32\lib\site-packages\pyrfc-1.9.4-py3.5
-win-amd64.egg
Processing dependencies for pyrfc==1.9.4
Searching for pyrfc==1.9.4
**Reading https://pypi.python.org/simple/pyrfc/
Couldn't find index page for 'pyrfc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pyrfc==1.9.4
error: Could not find suitable distribution for Requirement.parse('pyrfc==1.9.4'
)**

**Comment by bsrdjan** [comment]
Unfortunately could not reproduce the issue. Did you try to compile the egg from source ?

**Comment by Tset-Noitamotua** [comment]
I have the same issue. 

Following the steps described [here ](http://sap.github.io/PyRFC/install.html)I stuck on installing pyrfc itself.

```
[SAP_nwRFC] λ easy_install pyrfc-1.9.4-py3.5-win-amd64.egg
Searching for pyrfc-1.9.4-py3.5-win-amd64.egg
Reading https://pypi.python.org/simple/pyrfc-1.9.4-py3.5-win-amd64.egg/
Couldn't find index page for 'pyrfc-1.9.4-py3.5-win-amd64.egg' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pyrfc-1.9.4-py3.5-win-amd64.egg
error: Could not find suitable distribution for Requirement.parse('pyrfc-1.9.4-py3.5-win-amd64.egg')
```

Same for the 32bit version:
```
[SAP_nwRFC] λ easy_install pyrfc-1.9.3-py2.7-win32.egg
Searching for pyrfc-1.9.3-py2.7-win32.egg
Reading https://pypi.python.org/simple/pyrfc-1.9.3-py2.7-win32.egg/
Couldn't find index page for 'pyrfc-1.9.3-py2.7-win32.egg' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pyrfc-1.9.3-py2.7-win32.egg
error: Could not find suitable distribution for Requirement.parse('pyrfc-1.9.3-py2.7-win32.egg')
```

Tried other variants, too - without success:
```
C:\Users\username
[SAP_nwRFC] λ pip install pyrfc
Collecting pyrfc
  Could not find a version that satisfies the requirement pyrfc (from versions: )
No matching distribution found for pyrfc

C:\Users\username
[SAP_nwRFC] λ pip install pyrfc==1.9.3
Collecting pyrfc==1.9.3
  Could not find a version that satisfies the requirement pyrfc==1.9.3 (from versions: )
No matching distribution found for pyrfc==1.9.3

C:\Users\username
[SAP_nwRFC] λ pip install pyrfc==1.9.4
Collecting pyrfc==1.9.4
  Could not find a version that satisfies the requirement pyrfc==1.9.4 (from versions: )
No matching distribution found for pyrfc==1.9.4
```

Note: That's not a proxy issue. I can install other packages behind corporate proxy. And installation fails when not behind a proxy, too.

**Comment by Notre1** [comment]
Have you downloaded the .EGG file?  

If not, you can run it download and install it with one command like so:
`easy_install https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.4-py3.5-win-amd64.egg`

**Comment by Tset-Noitamotua** [comment]
Thanks for the hint. I've have done so right now.  (This step might be worth to mention the [documentation](http://sap.github.io/PyRFC/install.html))

I have to correct my first statement: NOW I have the same issue as Sven-H-x :-)

What should I do next?

**Comment by Tset-Noitamotua** [comment]
My system information:

Windows 7 64bit (German locale)
Python 2.7 (32bit)
Python 3.5 (32bit) default

```
λ pip list
pip (8.1.2)
pip-autoremove (0.9.0)
setuptools (24.0.2)
virtualenv (15.0.2)
virtualenvwrapper-win (1.2.1)
```

**Comment by Tset-Noitamotua** [comment]
Ok. I am somehow totally confused now. Wich version of SAP NW RFC SDK should I download from SAP Marketplace regarding my system information?

**Comment by bsrdjan** [comment]
Following the [documentation](http://sap.github.io/PyRFC/install.html#sap-nw-rfc-library-installation), the `Windows on x64 64bit` version should be fine

**Comment by Tset-Noitamotua** [comment]
Oh  I finally get it!

```
[SAP_CONNECT] λ easy_install https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.3-py2.7-win32.egg
Downloading https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.3-py2.7-win32.egg
Processing pyrfc-1.9.3-py2.7-win32.egg
creating c:\users\username\envs\sap_connect\lib\site-packages\pyrfc-1.9.3-py2.7-win32.egg
Extracting pyrfc-1.9.3-py2.7-win32.egg to c:\users\username\envs\sap_connect\lib\site-packages
Adding pyrfc 1.9.3 to easy-install.pth file

Installed c:\users\username\envs\sap_connect\lib\site-packages\pyrfc-1.9.3-py2.7-win32.egg
Processing dependencies for pyrfc==1.9.3
Finished processing dependencies for pyrfc==1.9.3

C:\Users\username
[SAP_CONNECT] λ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrfc import *
>>>
```

**Comment by Tset-Noitamotua** [comment]
Just for documentation:
- Windows 64bit + Python 3.5 32bit + NWRFC_40-20004568.SAR + pyrfc-1.9.4-py3.5-win-amd64.egg --> does NOT work
