### ISSUE TITLE
ImportError: Error relocating /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so: __strdup: symbol not found

### ISSUE THREAD

**Issue by switchell1990** [SAP/PyRFC#170]
Having issues installing this via Docker. 

When I do `from pyrfc import Connection` in my python program I am getting the following error;

 - ImportError: Error relocating /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so: __strdup: symbol not found

Please see attached my DockerFile and content files for this.

I have noticed when I run ldconfig -p | grep sap i am only getting the following back;

- libgssapi_krb5.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
- libgssapi_krb5.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so

In requirements I am installing package;

`pynwrfc --no-binary :all:`

[SAP Items.zip](https://github.com/SAP/PyRFC/files/4479605/SAP.Items.zip)

**Comment by bsrdjan** [comment]
The `ldconfig -p` only prints the list of libraries. After `nwrfcsdk.conf` added, the cache must be re-built, see [ldconfig man](http://manpages.ubuntu.com/manpages/bionic/man8/ldconfig.8.html).

Please try:

```dockerfile
RUN ldconfig && ldconfig -p | grep sap
```

**Comment by switchell1990** [comment]
Thanks for that :) 

Seems to be working now.
