### ISSUE TITLE
Call BAPI with variant

### ISSUE THREAD

**Issue by Suncatcher** [SAP/PyRFC#171]
Is it possible through PyRFC to call FM/BAPI with a variant from test directory?

![Untitled](https://user-images.githubusercontent.com/6388034/79346827-7b7fea00-7f3b-11ea-834d-f102b6350165.png)

Some modules have dozens of parameters which is more handy to call in a predefined way.

**Comment by bsrdjan** [comment]
The PyRFC does not have such functionality and there is no standard API for exporting SE37 test variant.

Reading the [Table for test data saved in SE37 (Test data directory)](https://answers.sap.com/questions/5844673/table-for-test-data-saved-in-se37-test-data-direct.html), it seems custom RFC could be created for exporting SE37 test data. That RFC could be called by PyRFC, to fill BAPI_USER_GET_DETAIL for example.

**Comment by Suncatcher** [comment]
And what about [this solution](https://answers.sap.com/answers/5844725/view.html) suggested? EXPORT statement is also not supported?

**Comment by bsrdjan** [comment]
Sorry that I can't help further here, this repository is for PyRFC issues only. The question can be discussed on SAP Community Network.
