### ISSUE TITLE
PyRFC Virtual Environment Configuration

### ISSUE THREAD

**Issue by Dan-Fishman** [SAP/PyRFC#172]
Hi There,

First of all I want to thank you for creating this module, creating many automations using it.
My Issue is configuring the virtual environment - after I created the venv, the pyrfc module doesn't find the files of the lib, although the Environment Variable SAPNWRFC_HOME=/usr/local/sap/nwrfcsdk is defined as required.

I want to emphasise, the module is working while using the global environment, but not with the venv.

maybe i should do another thing than just pip install pynwrfc - at the venv?

**Comment by bsrdjan** [comment]
`pip install pynwrfc` should work in venv as well, release testing for different Python versions works that way. Could you please uninstall the module by `pip uninstall pynwrfc` and check with `pip freeze` if eventually another `pyrfc` module installed? There is a `pyrfc` module on PyPI, not related to Python/RFC connectivity.

Could you please post the full error log?

**Comment by Dan-Fishman** [comment]
Tried to install as you said.

![Screen Shot 2020-04-21 at 13 00 43](https://user-images.githubusercontent.com/36278487/79852988-20814380-83d0-11ea-8d8d-cb83b687ff2c.png)

**Comment by Dan-Fishman** [comment]
I think the problem is more associated to vs code than the pynwrfc module.

![Screen Shot 2020-04-21 at 13 29 48](https://user-images.githubusercontent.com/36278487/79855916-4b6d9680-83d4-11ea-9359-5a7670d58f79.png)
