### ISSUE TITLE
pyrfc / SELECT TEVEN.LDATE , TEVEN.SATZA , TEVEN.LTIME 

### ISSUE THREAD

**Issue by saberabdelhady** [SAP/PyRFC#173]
Hi Experts,

In the past, I used the library hdbcli to connect sap hana and get data from sap with the below query sql

sql_query = """SELECT TEVEN.LDATE , TEVEN.SATZA , TEVEN.LTIME FROM TEVEN WHERE TEVEN.PERNR = '%s' AND TEVEN.STOKZ <> 'X' AND TEVEN.LDATE >= %s AND TEVEN.LDATE <= %s limit 120 """

but now i use pyrfc to connect sap netwaver 750

I'm using the awesome Python library - PyRFC to connect to an SAP ECC IDES

I am successfully connect with the library and get data as the below
![image](https://user-images.githubusercontent.com/39088480/79861186-47da0f80-83d4-11ea-9df0-da12ad7ad3bf.png)

but How to retrieve data through function module (se37) as I used to collect it via the library hdbcli (hana database library )

rfc

sql_query = """SELECT TEVEN.LDATE , TEVEN.SATZA , TEVEN.LTIME FROM TEVEN WHERE TEVEN.PERNR = '%s' AND TEVEN.STOKZ <> 'X' AND TEVEN.LDATE >= %s AND TEVEN.LDATE <= %s limit 120 """

**Comment by bsrdjan** [comment]
SAP hdb protocol is SQL oriented, working with database tables directly. SAP RFC protocol works with remote enabled ABAP Function Modules, exposing Business Object oriented API, like BAPI_SALESORDER_CREATE/UPDATE/CHANGE. Such Function Modules run all necessary SQL reads/updates internally, without exposing the underlying schema.

The hdb protocol is not foreseen for ABAP business logic consumption and the RFC protocol is not foreseen for table-level SQL operations. RFC_READ_TABLE and RFC_READ_TABLE2 Function Modules do offer some SQL capabilities and can be used in testing and experimenting (could probably read TEVEN) but have critical limitations for sustainable and scalable development.

For TEVEN or any other table, you can check if standard RFC API is available ("BAPI") and use it from RFC connector. The question is more for HCM/ABAP Consultant and the answer can be sometimes found on SAP forums, searching for "TEVEN BAPI" for example.

**Comment by saberabdelhady** [comment]
Thanks Eng. Bsrdjan ,,
