### ISSUE TITLE
SAP RFC_ABAP_EXCEPTION (rc=5): key=NO_DATA_FOUND

### ISSUE THREAD

**Issue by elsargan** [SAP/PyRFC#174]
I try to recieve the data from ST03N using function module "SWNC_COLLECTOR_GET_AGGREGATES" but i catch NO_DATA_FOUND:

`from pyrfc import Connection
from decimal import Decimal
from pprint import pprint
import datetime

try:
    from ConfigParser import ConfigParser
except ModuleNotFoundError as e:
    from configparser import ConfigParser

import sys

imp = dict(
    RFCINT1=0x7F,  # INT1: Integer value (1 byte)
    RFCINT2=0x7FFE,  # INT2: Integer value (2 bytes)
    RFCINT4=0x7FFFFFFE,  # INT: integer value (4 bytes)
    RFCFLOAT=1.23456789,  # FLOAT
    RFCCHAR1=u"a",  # CHAR[1]
    RFCCHAR2=u"ij",  # CHAR[2]
    RFCCHAR4=u"bcde",  # CHAR[4]
    RFCDATA1=u"k" * 50,
    RFCDATA2=u"l" * 50,  # CHAR[50] each
    RFCTIME=datetime.time(12, 34, 56),  # TIME
    RFCDATE=datetime.date(2012, 10, 3),  # DATE
    RFCHEX3=b"\x66\x67\x68",  # BYTE[3]: String with 3 hexadecimal values (='fgh')
)

def main():

    IMPORTSTRUCT = {
        "RFCFLOAT": 1.23456789,
        "RFCCHAR1": "A",
        "RFCCHAR2": "BC",
        "RFCCHAR4": "DEFG",
        "RFCINT1": 1,
        "RFCINT2": 2,
        "RFCINT4": 345,
        "RFCHEX3": bytes(b"\x01\x02\x03"),
        "RFCTIME": "121120",
        "RFCDATE": "20140101",
        "RFCDATA1": "1DATA1",
        "RFCDATA2": "DATA222",
    }

    INPUTROWS = 10
    IMPORTTABLE = []
    for i in range(INPUTROWS):
        row = IMPORTSTRUCT
        row["RFCINT1"] = i
        IMPORTTABLE.append(row)

    config = ConfigParser()
    config.read(r"C:\nwrfcsdk\PyRFC-master\PyRFC-master\tests\pyrfc.cfg")
    params_connection = config._sections["SXX"]

    conn = Connection(ashost='x.x.x.x', sysnr='00', client='100', user='user', passwd='passw')

    #result = conn.call( "STFC_STRUCTURE", IMPORTSTRUCT= IMPORTSTRUCT, RFCTABLE= IMPORTTABLE  )

    result = conn.call ("SWNC_COLLECTOR_GET_AGGREGATES", COMPONENT="TOTAL", ASSIGNDSYS="SXX", PERIODTYPE="D", PERIODSTRT="20200430" ,SUMMARY_ONLY="X", STORAGE_TYPE=" ", FACTOR=1000 )
    pprint(result)

if __name__ == "__main__":
    main()
`

**Comment by bsrdjan** [comment]
Could you please [test in ABAP system](https://github.com/SAP/node-rfc/issues/62#issuecomment-432542464), using transaction SE37, if any results returned with the same input parameters? The date in SE37 should be given in this format:`30.04.2020`.

**Comment by elsargan** [comment]
Yes, you was right. My fault in the input parameters.

Thanks
