### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dawnofnirvana** [SAP/PyRFC#175]
Hi all, after I ran this command :
python setup.py bdist_wheel

I got the following error:

750 Patch Level 6
running bdist_wheel
running build
running build_py
running build_ext
building 'pyrfc.pyrfc' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN
32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLA
TFORM_MAKENAME=ntintel -IC:\Users\dongjunyang\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\dongjunyang\AppData\Local\Programs\Python\Python38-32\incl
ude /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win32-3.8\Release\src/pyrfc/_pyrfc.obj -IC:\nwrfcsdk\nwrfcsdk\include -IC:\Users\dongjunyang\AppData\Local\Programs\P
ython\Python38-32\lib\inspect.py\Include -IC:\Users\dongjunyang\AppData\Local\Programs\Python\Python38-32\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -
GL -O2 -Oy- /we4552 /we4700 /we4789
error: command 'cl.exe' failed: No such file or directory

But I have the Microsoft visual studio C++ on my computer.

**Comment by bsrdjan** [comment]
Please check if you are maybe using the standard command prompt ?

The build process requires Microsoft [Developer Command Prompt](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019).
