### ISSUE TITLE
macOS Catalina: Version 10.15.4

### ISSUE THREAD

**Issue by Dan-Fishman** [SAP/PyRFC#179]
Hello,
After following the guide to install pynwrfc and the sapnwrfc sdk, this is the dump i get.

<img width="950" alt="first" src="https://user-images.githubusercontent.com/36278487/83004193-031b4700-a018-11ea-894e-08613a604105.png">
<img width="1435" alt="second" src="https://user-images.githubusercontent.com/36278487/83004203-06163780-a018-11ea-8860-8efde59c833e.png">

Used your Guide to install pynwrfc, tried both build from source and from wheel - both without success. 
1. Downloaded the SDK.
2. Created /usr/local/sap/nwrfcsdk and exported env var SAPNWRFC_HOME=/usr/local/sap/nwrfcsdk.
3. Unarchived the SDK into the SAPNWRFC_HOME dir.
4. Runned paths_fix.sh from the SAPNWRFC_HOME dir.
5. Added the char.h to the inlcude lib.
6. Built from source pynwrfc

My Machine Details:
Macbook Pro 2018
macOS Catalina: Version 10.15.4

**Comment by bsrdjan** [comment]
Please don't use the newest (PL6) SAP NWRFC SDK on Darwin >= 10.15.4.

The PL6 SDK is signed and after the fix applied, disallowed by Apple security policy, as the error message is telling.

Until this issue solved, please use the PL5. It is not signed and can be patched as described.

```shell
# PL5
$ codesign -dv libsapnwrfc.dylib
libsapnwrfc.dylib: code object is not signed at all
```

**Comment by Dan-Fishman** [comment]
Okay, that's a solution.
Can't find the PL5 on SAP website.
Where can I download it from?

**Comment by Dan-Fishman** [comment]
After contacting SAP support, they told me that SAP offers only the current version PL6.
Maybe you have the files of PL5

**Comment by Dan-Fishman** [comment]
???
Srdjan, can you help me find the SDK PL5 for macOS?

**Comment by bsrdjan** [comment]
Sorry, the Service Portal is the only approved channel. We work on finding the solution.

**Comment by bsrdjan** [comment]
Current solution is using PL7 or newer

**Comment by Dan-Fishman** [comment]
I will try to use PL7 this week and update you :)
