### ISSUE TITLE
No module named _pyrfc

### ISSUE THREAD

**Issue by timgogochen** [SAP/PyRFC#18]
D:\sap\PyRFC-master>python
Python 2.7.4 (default, Apr  6 2013, 19:55:15) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.

> > > from pyrfc import Connection
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyrfc__init__.py", line 22, in <module>
> > >     from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription,
> > > FunctionDescription, Server
> > > ImportError: No module named _pyrfc
> > > from pyrfc import Connection
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyrfc__init__.py", line 22, in <module>
> > >     from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription,
> > > FunctionDescription, Server
> > > ImportError: No module named _pyrfc

maybe  some error in source ,please help me solve this issue,
THanks

**Comment by bsrdjan** [comment]
Just try from another folder. `from pyrfc import *` for some reason does not work from the room PyRFC folder.
