### ISSUE TITLE
pyrfc not catching all exceptions raised by ABAP

### ISSUE THREAD

**Issue by Lejdi** [SAP/PyRFC#181]
Hi,

I'm testing pyrfc by calling EU_TAX_NUMBER_CHECK FM in SAP. The problem is: when I enter random letters instead of numbers (which is being checked by ABAP) in some cases the exception is being shown by pyrfc, and in some cases it isn't.

For example:
when I send request like
`conn.call('EU_TAX_NUMBER_CHECK' COUNTRY=u'DK', EU_AX_NUMBER=u'DKasdfghjk')` the ABAPApplicationException is catched
but when i send
`conn.call('EU_TAX_NUMBER_CHECK' COUNTRY=u'PL', EU_AX_NUMBER=u'PLasdfghjk')` the exception isn't catched.

In both cases ABAP check validity in exactly the same way.
I even checked the TCP packets in wireshark and the message with exception is being send to my host, but pyrfc doesn't see it.

Is there any workaround for this issue or should I wait for a fix?

**Comment by bsrdjan** [comment]
Not reproducible with:

```python
    try:
        conn = Connection(**ABAP)
        # result = conn.call("EU_TAX_NUMBER_CHECK", COUNTRY="DK", EU_TAX_NUMBER="DKasdfghjk")
        result = conn.call("EU_TAX_NUMBER_CHECK", COUNTRY="PL", EU_TAX_NUMBER="DKasdfghjk")
    except Exception as e:
        print(e)
```
 Could you please send the full test script and the output log?

**Comment by Lejdi** [comment]
My code is almost the same:

```
from pyrfc import *
 
with Connection(user=sap_logon, passwd=sap_pass, ashost=system_ip, sysnr=instance, client=mandant) as conn:
    try:
        res = conn.call('EU_TAX_NUMBER_CHECK', COUNTRY=u'PL', EU_TAX_NUMBER=u'DKasdfasdf')
        print(res)
    except Exception as e:
        print(e)
```

I also tried your code, and result remains the same. When I enter PL as COUNTRY, I'm getting ``` {} ``` as a result.

Log file contains only one info line:
``` C:\Users\user\Desktop\rfc\sapnwrfc.ini. ```

**Comment by bsrdjan** [comment]
Which log file you are referring to?

**Comment by Lejdi** [comment]
I'm referring to file generated when the script is run
``` dev_rfc.log ```

Did you mean other log file?

**Comment by bsrdjan** [comment]
I meant if console log redirected to log file. Could you please:

1) Delete all .trc and .log files, if currently present

2) Add trace=3 parameter to connection parameters

2) Run the test script, like python test.py

3) Post the full console output and attach `.trc` and `.log` files generated by test

**Comment by Lejdi** [comment]
The console output is just ``` {} ```
``` .trc ``` file: https://pastebin.com/wj3pQmqS
``` .log ``` file: https://pastebin.com/XC2V5xyE

**Comment by bsrdjan** [comment]
the trace of the exactly the same test, with my test ABAP system, shows:

```trace
2020-06-02 11:29:44.710634 [17128965850083098625] << RfcInvoke returned RFC_ABAP_EXCEPTION
	RFC_ERROR_INFO.key: NOT_VALID
	RFC_ERROR_INFO.message: ID:AR Type:E Number:191 DK
```

while on your system:

```trace
2020-05-29 14:44:23.283281 [12628] << RfcInvoke returned RFC_OK
```

Which `pyrfc` and NWRFC SDK versions are used and on which platform? You can trace them for example by:

```python
# -*- coding: utf-8 -*-

import pyrfc
from pyrfc import Connection

ABAP = {
    "user": "...",
    "passwd": "...",
    "ashost": "...",
    "sysnr": "...",
    "lang": "...",
    "client": "...",
    "sysid": "...",
   "trace": "3"
}

if __name__ == "__main__":
    try:
        conn = Connection(**ABAP)
        print(pyrfc.__version__, conn.version)
        # result = conn.call("EU_TAX_NUMBER_CHECK", COUNTRY="DK", EU_TAX_NUMBER="DKasdfghjk")
        result = conn.call("EU_TAX_NUMBER_CHECK", COUNTRY=u"PL", EU_TAX_NUMBER=u"DKasdfghjk")
    except Exception as e:
        print(e)
```

The function module `EU_TAX_NUMBER_CHECK` looks standard but could you check the result in ABAP system? Logon on ABAP system with the same user used in test script, open the transaction SE37 and run the function module with the "PL" parameter.

**Comment by Lejdi** [comment]
Oh... I have tested it in SE37, and it seems it's a problem with my system. The result here is the same as in pyrfc.
So I have to look for a fix here. Thank you for help.
