### ISSUE TITLE
BAPI call using RSELOPTION. SAPSQL_IN_ITAB_ILLEGAL_OPTION

### ISSUE THREAD

**Issue by rogerfn** [SAP/PyRFC#182]
I'm trying to call a BAPI that uses one input argument of type RSELOPTION. What is the actual format to be used in python? I tried the following

`results = conn.call('Z_OMA_ZL03', P_HSDAT=['I','EQ','20130717']) `

But I always get:
pyrfc._exception.ABAPRuntimeError: RFC_ABAP_RUNTIME_FAILURE (rc=3): key=SAPSQL_IN_ITAB_ILLEGAL_OPTION, message=Unzulässiger Wert in OPTION-Feld der Wertetabelle für IN-itab-Operator. [MSG: class=, type=, number=, v1-4:=;;;]

Any ideas of what I'm doing wrong?

**Comment by bsrdjan** [comment]
RSELOPTION is ABAP structure:

```shell
SIGN	Types	TVARV_SIGN	CHAR	1
OPTION	Types	TVARV_OPTI	CHAR	2
LOW	Types	RSDSSELOP_	CHAR	45
HIGH	Types	RSDSSELOP_	CHAR	45
```

Try:

```python
results = conn.call('Z_OMA_ZL03', P_HSDAT={'SIGN':'I', 'OPTION':'EQ', 'LOW':'20130717'})
```
or if P_HSDAT eventually a table:

```python
results = conn.call('Z_OMA_ZL03', P_HSDAT=[{'SIGN':'I', 'OPTION':'EQ', 'LOW':'20130717'}])
```

**Comment by rogerfn** [comment]
Huh, the second option worked. Thanks for the support! 

`P_HSDAT=[{'SIGN':'I', 'OPTION':'EQ', 'LOW':'20130717'}])`
