### ISSUE TITLE
Decimal conversion error

### ISSUE THREAD

**Issue by filak-sap** [SAP/PyRFC#183]
PyRFC-2.0.5 / Linux / Python 3.6

I use PyRFC to start STC task list exuction via the module STC_TM_SESSION_BEGIN.
I am getting the folllowing error:

```
  File "src/pyrfc/_pyrfc.pyx", line 2200, in pyrfc.pyrfc.wrapVariable
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

I changed pyrfc source codes to get the converted value:
and it is `20200609101738.9716980T` however I ABAP debugger I can see the value is ` 20200609101738.9716980`. Apparently PyRFC reads 1 more character than necessary.

**Comment by bsrdjan** [comment]
Hi Filak,

is it SAP internal system, where I could test asap?

BR, srdjan

**Comment by bsrdjan** [comment]
The only decimal parameter is EXPORTING STC_EXEC_ID, type DEC 21.7

Could not reproduce in internal test system, using 20200609101738.9716980.

Which exactly Linux platform? Please find the Ubuntu wheel attached (unzip before use :))

[pynwrfc-2.0.5-cp36-cp36m-linux_x86_64.whl.zip](https://github.com/SAP/PyRFC/files/4752577/pynwrfc-2.0.5-cp36-cp36m-linux_x86_64.whl.zip)

**Comment by filak-sap** [comment]
My apologies. It's just simply not possible to run pyrfc with the nwrfc lib from SAP kernel directories in the live system. I configured LD_LIBRARY_PATH to unpacked version of NWRFCSDK and the problem disappeared.

**Comment by filak-sap** [comment]
Thank you for your help!

**Comment by danielhillding** [comment]
Hello! I have a similar problem where I am getting the same error message (Windows/Python 3.13.0/Pyrfc 3.3.1). I have added the directory of the lib folder of nwrfc in PATH as explained before.  Have I missed something?

Thank you for the help!

Regards,
Daniel

**Comment by cauashmith** [comment]
Hello! I'm having the same issue as Daniel
https://github.com/SAP/PyRFC/discussions/378

Any help is useful.
Regards, Cauã.
