### ISSUE TITLE
Leading zeroes are not respected

### ISSUE THREAD

**Issue by Suncatcher** [SAP/PyRFC#185]
I am calling BAPI thru PyRFC like this:

    import pyrfc
    from pyrfc import Connection
    RIS=pyrfc.Connection(user='USER', passwd='PASS', ashost='host', sysid='sys', sysnr='99', client='100', lang='EN', trace='3')
    line = {u'MAT':'000000000007511093',u'QTY':'10'}
    result=RIS.call("SOME_BAPI",      
              I_DOC_TYPE='XXX', 
              I_VKORG='ZZ11', 
              I_VTWEG='01', 
              I_SPART='01', 
              I_SOLD_TO='0010366253', 
              I_PAYER='0030379445', 
              I_SHIP_TO='0029038880', 
    print(result['ERRORS'])

But it throws it cannot find this material (MAT parameter in structure with type MATNR) for this organization, however direct running of the same input via SAP and through JCo  goes fine. It seems that Jco respects leading zeroes whilst PyRFC does not.

What am I missing? Maybe it should be called another way?

**Comment by bsrdjan** [comment]
Depending on BAPI, the selection might consider more filter parameters, like SOLD_TO, SHIP_TO ..., not only MATNR and VKORG. These additional parameters might have ABAP Conversion Exits ("ALPHA" exits) implemented, which would explain not finding the material.

You can check "SOME_BAPI" parameters (which BAPI, or which BAPI used internally?), or you can set an external break-point in ABAP, run the Python script and check which parameters differ. To my knowledge, the JCo does not consider ALPHA exits, should behave in this regard the same way as other ABAP connectors.

**Comment by Suncatcher** [comment]
> These additional parameters might have ABAP Conversion Exits ("ALPHA" exits) implemented, which would explain not finding the material.

as I said in [my other issue](https://github.com/SAP/PyRFC/issues/186) I wrote this BAPI from scratch and there is no other parameters that can impact this.

I set break point in that exact line where this validation takes place and I see that the material cam without leading zeroes, It is my own validation check so I know where it happens and checks for material existence.

**Comment by bsrdjan** [comment]
When the break-point set "where the validation takes place:, the leading zeroes could be removed by ABAP logic, on a way from the BAPI entry point, to that location. Can you set the break-point at the very first executable line of the BAPI, to check if zeroes are present there?

**Comment by Suncatcher** [comment]
> Can you set the break-point at the very first executable line of the BAPI, to check if zeroes are present there?

Yes, you are right, I set the break in the very beginning of the BAPI and the leading zeroes are transferred. This was related to [caching](https://github.com/SAP/PyRFC/issues/186), closing this issue.

**Comment by bsrdjan** [comment]
Hi @Suncatcher,

just published the [rfmcall](https://www.npmjs.com/package/rfmcall) utility, helpful for catching ALPHA exits, among other things. 

It is for nodejs and the output is (for the time being) in JS but with few search/replace you can get the Python output.

Feedback welcome

Kind regards,
Srdjan

**Comment by Suncatcher** [comment]
@bsrdjan thanks, will try.
