### ISSUE TITLE
Mismatch between parameters during PyRFC call

### ISSUE THREAD

**Issue by Suncatcher** [SAP/PyRFC#186]
During testing my BAPI I noticed weird thing. Though, I call one parameter set, in the debugger I see another one when I catch my call:

![imageedit_4_8119969282](https://user-images.githubusercontent.com/6388034/85128967-04b4e500-b23b-11ea-9b6d-c9c2f5bbdde5.jpg)

Is it a problem of PyRFC caching mechanism or smth else? How to fix it?

**Comment by bsrdjan** [comment]
The PyRFC and the underlying NWRFC SDK do not cache any data, only ABAP metadata, thus it looks more like "something else". Some ABAP BAPIs however, do cache the data and some of them have the parameter to enable/disable caching, but the issue here are input data, right?

How do you catch the PyRFC call, by ABAP remote break-point ? Is it possible to reproduce by simple Python script and can you share it?

**Comment by Suncatcher** [comment]
> Some ABAP BAPIs however, do cache the data and some of them have the parameter to enable/disable caching, but the issue here are input data, right?

Yes, it is input data, and I 've written this BAPI from scratch, so I definitely know that there is no parameter chaching is implemented. 

> How do you catch the PyRFC call, by ABAP remote break-point ? 

I call it via dialog user and set an external break-point for that user. Nothing unusual

> Is it possible to reproduce by simple Python script and can you share it?

I call it like this

    import pyrfc
    from pyrfc import Connection
         RIS=pyrfc.Connection(user='USER', passwd='PASS', ashost='host', sysid='sys', sysnr='99', 
          client='100', lang='EN', trace='3')
          line = {u'MAT':'000000000007511093',u'QTY':'10'}
          result=RIS.call("SOME_BAPI",      
          I_DOC_TYPE='XXX', 
          I_VKORG='ZZ11', 
          I_VTWEG='01', 
          I_SPART='01', 
          I_SOLD_TO='0010366253', 
          I_PAYER='0030379445', 
          I_SHIP_TO='0029038880', 
         print(result['ERRORS'])

**Comment by Suncatcher** [comment]
It seems that there is some interval for cache invalidate, but where is this cache?

**Comment by Suncatcher** [comment]
Seems to be file-caching issue
