### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by nik251** [SAP/PyRFC#188]
import os
from socket import *
host = "172.17.0.2" # set to IP address of target computer
port = 13000
addr = (host, port)
UDPSock = socket(AF_INET, SOCK_DGRAM)
while True:
    msg = print(input(str("Enter message to send or type 'exit': ")))
    data = msg.encode()
    data = con.string
    if data: file.write(s.encode('utf8'))
    UDPSock.sendto(data, addr)
    if data == "exit":
        break
UDPSock.close()
os._exit(0)

how would you change the "NoneType" to a string so it cant be sent?

**Comment by mpf82** [comment]
``print(...)`` always returns ``None``. 

Change 

>  msg = print(input(str("Enter message to send or type 'exit': ")))

to 

>  msg = input(str("Enter message to send or type 'exit': "))
> print(msg)

There are several other issues with your code - and no part of your code seems to be related to pyrfc.

**Comment by nik251** [comment]
thx i figured it out after i posted and forgot take it down,
also I'm 15 so course there are errors in my code
what's pyrfc?

**Comment by nik251** [comment]
also what could i do to fix the other errors?

**Comment by bsrdjan** [comment]
Please post only pyrfc related issues here. For other errors please create issue in some other repository.
