### ISSUE TITLE
load _pyrfc.pyd in Windows also need Microsoft vs runtime

### ISSUE THREAD

**Issue by JunyanHe** [SAP/PyRFC#19]
I met a problem during importing pyrfc although I have installed SAPNWRFC before,

> > > import pyrfc
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\pyrfc-1.9.4-py2.7-win-amd64.egg\pyrfc__in
> > > it__.py", line 22, in <module>
> > >     from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription,
> > > FunctionDescription, Server
> > > ImportError: DLL load failed: The specified module could not be found.

I spent a lot of time to investigate the root cause of this. Finally, I found the _pyrfc.pyd may be compiled with MSVS, in my case, MSVS 2015. I downloaded and installed Visual C++ Redistributable for Visual Studio 2015 to resolve this problem.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

I suggest to note the version of Visual Studio to installation manual to avoid similar problem. Thanks.

**Comment by bsrdjan** [comment]
Thank you very much for the very good suggestion. I leave it open, as a reminder to add to  manual.

**Comment by bsrdjan** [comment]
Closed with README fix.

**Comment by bsrdjan** [comment]
Just a quick troubleshooting tip.

After the SAP NW RFC Library installed on Windows system and `lib` subfolder added to path, you may start the **rfcexec.exe** test program, from the `bin` subfolder, to verify the SAP NW RFC Lib installation.

If the popup comes up with an error indicating that SAPNWRFC.dll (or another DLL from the `lib` folder) is missing, although the dll is there, the most likely cause is that Microsoft redistributable is missing, or not installed properly.
