### ISSUE TITLE
ImportError: cannot import name 'Connection' from 'pyrfc'

### ISSUE THREAD

**Issue by MJQSystems** [SAP/PyRFC#191]
I am writing a code to connect to SAP ECC 6.0 using pyrfc library. I am giving following details of my environment -
1) Operating System - Windows 10
2) Python Version 3.8.2
3) PYRFC Version - 0.1.2
4) Cython Version - 0.29.21
5) Installed NWRFCSDK in folder C:\NWRFCSDK
6) Added C:\NWRFCSDK\LIB to PATH variable
7) Set SAPNWRFC_HOME = C:\NWRFCSDK
8) Installed Visual C++ Redistributable for Visual Studio 2013 

After doing all these installations and settings when I am trying to run "from pyrfc import Connection" in jupyter notebook
I am getting following error
ImportError: cannot import name 'Connection' from 'pyrfc'

However "from pyrfc import *" works well without error.

I tried to search the solution from many web sources, but not finding exact solution.
Can someone help to resolve this issue.

Thanks
MJQ

**Comment by bsrdjan** [comment]
How did you install PyRFC ? Please be aware that the correct command is `pip install pynwrfc` and not `pip install pyrfc`.

If `pyrfc` installed by mistake, please uninstall and install `pynwrfc`'.

**Comment by bsrdjan** [comment]
Check with `pip freeze` if pyrfc installed and uninstall if so.

**Comment by bsrdjan** [comment]
Looks closed
