### ISSUE TITLE
PyRFC Server error

### ISSUE THREAD

**Issue by clebersanchez** [SAP/PyRFC#193]
Hello !

I'm trying to create a PyRFC Server application and I'm using the sample file serverStfcConnection.py as a base, but I'm having some errors.

Installed versions here:

- Python 3.8.5
- Cython 0.29.21
- pynwrfc 2.0.6
- pyrfc 0.1.2

The first point I found of error was in the __init__.py file. 
In the file installed on my machine, it does not have the Server library: 

  _from .pyrfc import (
      get_nwrfclib_version,
      Connection,
      Throughput,
      TypeDescription,
      FunctionDescription,
      __VERSION__,
  )_

When I look at gitHub, I have:

  _from .pyrfc import (
      get_nwrfclib_version,
      Connection,
      Throughput,
      TypeDescription,
      FunctionDescription,
      Server,
      __VERSION__,
  )_

I changed the file and included the Server line and managed to connect and apparently the program was registered, however, when it will run the server.serve (20) line, it shows timeout as you can see below:

  _"Y:\Documents\Desenvolvimentos\Python\Estudos\pyRFC SAP\venv\Scripts\python.exe" 
  "Y:/Documents/Desenvolvimentos/Python/Estudos/pyRFC SAP/serverpy.py"
  {'user': 'csanchez', 'passwd': 'Phoenix@99', 'ashost': ‘XXX.XXX.X.XX', 'sysnr': ‘XX', 'lang': 'PT', 'client': ‘XXX', 'sysid': ‘XXX'}
  <FunctionDescription 'ZSEFAZ_TESTE' with 2 params>
  --- Server registration and serving ---
  [2020-08-31 19:11:27.719695 UTC] Server 'Registered server.'
  [2020-08-31 19:11:30.720722 UTC] Server 'timeout reached (20 sec)'

  Process finished with exit code 0_

The program I wrote is as follows:

  _from pyrfc import Server, Connection
  from configparser import ConfigParser

  config = ConfigParser()
  config.read("sapnwrfc.cfg")

  Callback function
  def my_stfc_connection(request_context, REQUTEXT=""):
      return {
          "ECHOTEXT": REQUTEXT,
          "RESPTEXT": u"Python server here. Connection attributes are: "
                      u"User '{user}' from system '{sysId}', client '{client}', "
                      u"host '{partnerHost}'".format(**request_context["connection_attributes"]),
      }

  Open a connection for retrieving the metadata of 'STFC_CONNECTION'
  params_connection = config._sections["connection"]
  print(params_connection)
  conn = Connection(**params_connection)

  func_desc_stfc_connection = conn.get_function_description("ZSEFAZ_TESTE")
  print(func_desc_stfc_connection)

  Instantiate server with gateway information for registering, and
  install a function.
  params_gateway = config._sections["gateway"]
  server = Server(**params_gateway)
  server.install_function(func_desc_stfc_connection, my_stfc_connection)
  print("--- Server registration and serving ---")
  server.serve(20)_

Can you help me ?

**Comment by bsrdjan** [comment]
The SAP NWRFC SDK server interface has changed recently, see section 5 of [SAP NWRFC SDK 7.50 Programming Guide](https://support.sap.com/content/dam/support/en_us/library/ssp/products/connectors/nwrfcsdk/NW_RFC_750_ProgrammingGuide.pdf). The old API works (backwards compatible) but the new one is recommended and the Server example is now a bit outdated. 

The error looks like a configuration issue to me, like when ABAP client can't find the Python server.

You could check the server work in progress for node-rfc, the [implementation](https://github.com/SAP/node-rfc/blob/server/src/Server.cc) and the [genericHandler](https://github.com/SAP/node-rfc/blob/server/src/Server.cc#L142) in particular. The [documentation](https://github.com/SAP/node-rfc/blob/server/doc/usage.md#server) shows one example of the working configuration, you compare with your settings.

Would you be interested in sharing the work as PyRFC contribution? There is feature request for node-rfc where Server functionality could be the part of the solution: https://github.com/SAP/node-rfc/issues/172 
It is in NodeJS context but with Python is all the same, only the implementation should be simpler.

**Comment by cleberz32** [comment]
Hi @bsrdjan !

I noticed the difference of version and even making some changes I had not managed to make it work.

I will follow your recommendation and review the Node implementation and see if I can resolve the Python implementation. 
As soon as I get it, I will certainly share it.

Thank you for now.

**Comment by bsrdjan** [comment]
The main branch is updated with server bindings, tested on macOS only for now:

* Usage example: `tests/server/server.py`
* Unit tests: `tests/test_server.py`
* Documented only [here](https://github.com/SAP/node-rfc/blob/master/doc/usage.md#server-experimental) for now

**Comment by bsrdjan** [comment]
The to-be final implementation of Server bindings is tested on Linux, Windows and macOS: df9805e

It should be shipped with the next release, after the documentation re-work completed (will take some time).

Please feel to test in the meantime and share the feedback here:

* Test example: [server.py](https://github.com/SAP/PyRFC/blob/master/tests/server/server.py)

* Documentation: check [here](https://github.com/SAP/node-rfc/blob/master/doc/usage.md#server-experimental) for now

**Comment by bsrdjan** [comment]
Server bindings are published with 2.3.0 release on PyPI, feel free to test.
