### ISSUE TITLE
Wrong result from RFC

### ISSUE THREAD

**Issue by MaaYuu** [SAP/PyRFC#197]
Hi,
Even though SAP table has some records, Python code that reach this table from RFC has different records.

Firstly, headers of SAP table are MATNR and MAKTX, in RFC code outputs can be sometimes MATNR/x01 and MAKTX/x01.

And secondly, in some records a random letter created after long spaces although nothing like this exists.

What can be the reason of this, and how can it be solved?

SAP table:

![image](https://user-images.githubusercontent.com/35421890/95436059-0e826580-095c-11eb-816c-04aa9da66e04.png)

Python output:

![image](https://user-images.githubusercontent.com/35421890/95437248-74232180-095d-11eb-8bdf-b6d10e10d01a.png)

**Comment by bsrdjan** [comment]
Error look like coder errors, reported and reproduced with NWRFC SDK 7.50 PL7, on Linux and Darwin:  #196

Are you using PL7 and can you try with PL6 ?

**Comment by MaaYuu** [comment]
How can I download NWRFC SDK 7.50 PL6 for Windows Server?
Can you share a link?
SAP specialist cannot found it versions like NWRFC SDK 7.10, 7.11, 7.20, etc.

**Comment by bsrdjan** [comment]
Only the latest NWRFC SDK version is available on Service Portal. Older version is removed as soon the latest one published. You can try with older version only if you downloaded it before and saved a local copy.

The root cause is new unicode handling logic in PL7, I am working on patch.

**Comment by MaaYuu** [comment]
I did not download it in my local, so I have to wait your work, right?
Is not there any way to reach PL6 files?

**Comment by bsrdjan** [comment]
Right, no way to reach PL6 files. The new NWRFC SDK version or patch should be installed in test environment first, before deployment in production. If any issues in test env, the older version is available in production. The latest version is fully backwards compatible and only the latest version is supported, that is why past versions not available for download.

**Comment by bsrdjan** [comment]
Please try the 2.1.0 release

**Comment by MaaYuu** [comment]
Thank you very much Srdjan, no error after pynwrfc 2.1.0 installation.

**Comment by bsrdjan** [comment]
You can also use this workaround for the PL7: #213
