### ISSUE TITLE
rfcexec.exe without output

### ISSUE THREAD

**Issue by Rahinnos** [SAP/PyRFC#198]
I'm stuck at the step to verify the correct installation of the RFC SDK. If I run rfcexec.exe there is no output at all, the prompt returns back immediately:
![image](https://user-images.githubusercontent.com/32942821/95870756-28adb080-0d6d-11eb-83e2-cb88c070f029.png)

I've completed the 4 steps from the installation guide in
https://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation

I'm running:
- Windows Server 2016 64-bit.
- SDK: 750 Patch Level 7

Any help is highly appreciated.

**Comment by bsrdjan** [comment]
Ni idea, never seen before. Can you just go ahead, install the pynwrfc and make the simple test if it works?

If any of [Windows prerequisites](https://github.com/SAP/PyRFC#windows) missing the PyRFC will complain.

**Comment by Rahinnos** [comment]
I tried that and pyrfc doesn't seem to find the SDK:
![image](https://user-images.githubusercontent.com/32942821/95888490-6d434700-0d81-11eb-812e-5cbc4dad87eb.png)

- PATH has C:\nwrfcsdk\lib included
- SAPNWRFC_HOME is set to c:\nwrfcsdk

**Comment by bsrdjan** [comment]
Which Python release is used?

Please find more detailed troubleshooting checklist:

1. The correct NWRFC SDK download and installed, not the 32-bit version, or Linux libs for example?

2. The NWRFC SDK lib folder added to Path

3. The user running Python script has read access to SDK lib folder?

4. [Windows prerequisites](https://github.com/SAP/PyRFC#windows) installed, e.g. VS 2013 C++ redistributable

If all this looks good, then another library might be missing on Windows system and you can run the Process Monitor, to find out what exactly goes wrong: https://github.com/SAP/node-rfc/issues/115#issuecomment-570248671

**Comment by Rahinnos** [comment]
VS 2013 C++ Redistributable wasn't installed because I thought the newer 2015 version would suffice. After the installation it is working just fine now, the pyrfc test is also working.

Thanks for the great support!
