### ISSUE TITLE
'utf-8' codec can't decode byte 0xab in position 2: invalid start byte

### ISSUE THREAD

**Issue by Arjun146** [SAP/PyRFC#199]
Hi Everyone, 
 
In the below code I am trying to read SAP TCURR table using RFC_READ_TABLE . I am getting ''utf-8' codec can't decode byte 0xab in position 2: invalid start byte".

****************Start of Code*************************
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError
from pprint import PrettyPrinter

conn = Connection(ashost='xxxxxx00', sysnr='00', client='000', user='xxxxx', passwd='xxxxx')

# while True:
result = conn.call('RFC_READ_TABLE', \
                                QUERY_TABLE = 'TCURR', \
                                OPTIONS = [{ 'TEXT': "FCURR = 'AED'"}] , \
                                ROWSKIPS = 0, ROWCOUNT = 20)

data = result
pp.pprint(data['DATA'])

****************End of Code*************************

**Error Message:**

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-a64e83fef356> in <module>
      6 
      7 # while True:
----> 8 result = conn.call('RFC_READ_TABLE', \
      9                                 QUERY_TABLE = 'TCURR', \
     10                                 OPTIONS = [{ 'TEXT': "FCURR = 'AED'"}] , \

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.Connection.call()

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.wrapResult()

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.wrapVariable()

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.wrapTable()

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.wrapStructure()

src\pyrfc\_pyrfc.pyx in pyrfc._pyrfc.wrapString()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 2: invalid start byte

Could you please help to fix this issue?

Thanks,
Arjun

**Comment by Arjun146** [comment]
Updated to Pyrfc 2.1.0 and this fixed the issue

**Comment by Arjun146** [comment]
The code works fine when executed from Jupyter , but I get this error ''utf-8' codec can't decode byte 0xab in position 2: invalid start byte' when trying to execute from PowerBI with PythonScript as data source. 

Could you please help if there is any connector or installation needed to make this work in Power BI

Thanks,
A

**Comment by bsrdjan** [comment]
No idea what Jupiter or Power BI could be but the build from source works on practically any platform. Especially recommended for Linux.

**Comment by Arjun146** [comment]
It works now , earlier I updated Pyrfc from Jupyter , now I executed the update from CMD and it started working in Power Bi .. Thank you for the reply

**Comment by rohitkumarsoni** [comment]
I am getting the same issue and while using the pyrfc 2.1.0 not able to resolve the issue 
help me out
