### ISSUE TITLE
Transmission too slow

### ISSUE THREAD

**Issue by loewechiu** [SAP/PyRFC#20]
Hi Gurus,

I use the PyRFC to pull workload data from SAP, it works fine.
However, when the SAP system is too big, it takes nearly half an hour to transfer.
Any way to optimize the below statement?

result = conn.call('SWNC_COLLECTOR_GET_AGGREGATES',
                           COMPONENT=u'TOTAL',
                           ASSIGNDSYS= self.sysname,
                           PERIODTYPE=u'M',        ##monthly
                           PERIODSTRT=datetime.date(year,month,01),
                           SUMMARY_ONLY=u'')

Thank you very much!

BR 
Loewe Chiu

**Comment by martinduffy** [comment]
I am not sure how many rows of data you are trying to retrieve. It has been
my experience that you want to write your code to pull say 1000 rows and
then the next 1000 rows, etc until you get all of the rows. It is much
faster. There are examples out there that I used when attempting to do
this. I will have to look in the code I was using at the time to find this.
I will reply if I can find something but look for examples that do
incremental retrieves of the data until it is all retrieved. It is much
faster.

**Comment by loewechiu** [comment]
Thanks for your fast reply.
the output "result" contains a lot of SAP tables, and I test to print one of them into a txt file, it went 21MB.
That'll be crazy if the conn.call transfers all of them...

**Comment by bsrdjan** [comment]
Perhaps to use multiple calls, with shorter periods, the PyRFC cant help here.
