### ISSUE TITLE
I don't know why it said IMPORTSTRUCT not found

### ISSUE THREAD

**Issue by rexryan** [SAP/PyRFC#201]
from pyrfc import Connection

from pprint import pprint
import datetime

try:
    from ConfigParser import ConfigParser
except ModuleNotFoundError as e:
    from configparser import ConfigParser

import sys
x = dict(
        DATAB='20150701',
        DATAI='20150709',
        LV_FLAG='1'
)

def main():
    config = ConfigParser()
    config.read("/home/yoyo/demo/sapnwrfc.ini")
    params_connection = config._sections["connection"]

    conn = Connection(**params_connection)
    result = conn.call("ZWMS_ALLOCATION_RK",IMPORTSTRUCT=x)
    pprint(result)

if __name__ == "__main__":
    main()

yoyo@yoyo:~/PyRFC/examples$ python3 clientStfcStructure.py 
Traceback (most recent call last):
  File "clientStfcStructure.py", line 33, in <module>
    main()
  File "clientStfcStructure.py", line 28, in main
    result = conn.call("ZWMS_ALLOCATION_RK",IMPORTSTRUCT=x)
  File "src/pyrfc/_pyrfc.pyx", line 421, in pyrfc.pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 1661, in pyrfc.pyrfc.fillFunctionParameter
pyrfc._exception.ExternalRuntimeError: RFC_INVALID_PARAMETER (rc=20): key=RFC_INVALID_PARAMETER, message=field 'IMPORTSTRUCT' not found [MSG: class=, type=, number=, v1-4:=;;;]

**Comment by bsrdjan** [comment]
If the following works with SAP standard function module, you need to check if the IMPORTSTRUCT parameter defined in ZWMS_ALLOCATION_RK:

```python
x = dict(
    RFCCHAR1="A"
)
result = conn.call("STFC_STRUCTURE", IMPORTSTRUCT=s)
pprint(result)
```

When in doubt, the [rfmcall](https://www.npmjs.com/package/rfmcall) can print the correct RFM call template. It is indeed for NodeJS and runs on NodeJS but helps also for Python.

**Comment by rexryan** [comment]
> If the following works with SAP standard function module, you need to check if the IMPORTSTRUCT parameter defined in ZWMS_ALLOCATION_RK:
> 
> ```python
> x = dict(
>     RFCCHAR1="A"
> )
> result = conn.call("STFC_STRUCTURE", IMPORTSTRUCT=s)
> pprint(result)
> ```
> 
> When in doubt, the [rfmcall](https://www.npmjs.com/package/rfmcall) can print the correct RFM call template. It is indeed for NodeJS and runs on NodeJS but helps also for Python.



thanks for your reply
but in ZWMS_ALLOCATION_RK, there is no IMPORTSTRUCT in this API, it just give me 3 parameters for API the input, which is DATAB, DATAI and LV_FLAG, so in conn.call what should I need to do to call this function?

**Comment by bsrdjan** [comment]
Hard to guess because the ZWMS_ALLOCATION_RK is not standard RFM and I don't know the ABAP signature, but please try:

```python
result = conn.call("ZWMS_ALLOCATION_RK", DATAB='20150701', DATAI='20150709', LV_FLAG='1')
```

or

```python
x = dict(
DATAB='20150701',
DATAI='20150709',
LV_FLAG='1'
)
result = conn.call("ZWMS_ALLOCATION_RK", **x)
```
When in doubt, the easiest way is `rfmcall`, would print the correct call syntax. I hope to find some time and port to Python.

**Comment by rexryan** [comment]
even put the parameter directly into conn.call function or make it in a dict , it prompts this error out


yoyo@yoyo:~/demo$ python3 test1.py&nbsp;
Traceback (most recent call last):
&nbsp; File "test1.py", line 10, in <module&gt;
&nbsp; &nbsp; result = conn.call("ZWMS_ALLOCATION_RK",**b)
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 438, in pyrfc.pyrfc.Connection.call
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2053, in pyrfc.pyrfc.wrapResult
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2132, in pyrfc.pyrfc.wrapVariable
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2102, in pyrfc.pyrfc.wrapTable
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2071, in pyrfc.pyrfc.wrapStructure
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2200, in pyrfc.pyrfc.wrapVariable
&nbsp; File "src/pyrfc/_pyrfc.pyx", line 2329, in pyrfc.pyrfc.wrapString
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 2: unexpected end of data





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SAP/PyRFC"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 凌晨1:04
收件人:&nbsp;"SAP/PyRFC"<PyRFC@noreply.github.com&gt;;
抄送:&nbsp;"?? 黄冠华 ??"<782125711@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SAP/PyRFC] I don't know why it said IMPORTSTRUCT not found (#201)





 
Hard to guess because the ZWMS_ALLOCATION_RK is not standard RFM and I don't know the ABAP signature, but please try:
 result = conn.call("ZWMS_ALLOCATION_RK", DATAB='20150701', DATAI='20150709', LV_FLAG='1')
 
or
 x = dict( DATAB='20150701', DATAI='20150709', LV_FLAG='1' ) result = conn.call("ZWMS_ALLOCATION_RK", **x)
 
When in doubt, the easiest way is rfmcall, would print the correct call syntax. I hope to find some time and port to Python.

**Comment by bsrdjan** [comment]
ok, parameters are now correct and the new error looks similar to #199.

If you use SAP NWRFC SDK PL7, please upgrade to PyRFC 2.1.0 and re-test. Otherwise, which NWRFC SDK and PyRFC release do you use?

**Comment by bsrdjan** [comment]
The initial issue seem to be resolved. Please reopen if further support needed.
