### ISSUE TITLE
Python Crashes when reading certain SAP tables in NetWeaver RFC SDK 7.5 PL7, but PL6 works

### ISSUE THREAD

**Issue by boringDev** [SAP/PyRFC#207]
System Info:
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32

We are unable to pull down data from TSTCT on the TTEXT field using the newest PyRFC and NetWeaver RFC SDK versions. The 7.5 PL6 version of NetWeaver RFC SDK pulls the data without issue.

Here is the data as viewed in SE16:

SPRSL | TCODE | TTEXT
------  | ------- | --------
E|/FSCAA/VC_FIELD|Structure Definition and Fld Mapping

Script that crashes:
```python
from os import environ
patch_level = '7'
environ['SAPNWRFC_HOME'] = r'C:\nwrfcsdk_7.5_PL{}'.format(patch_level)
environ['PATH'] += r'C:\nwrfcsdk_7.5_PL{}\lib;'.format(patch_level)
print(environ['SAPNWRFC_HOME'])
import pyrfc
print(pyrfc.__version__)
tcode = '/FSCAA/VC_FIELD'
data = pyrfc.Connection(**kwargs).call(
    func_name='/BODS/RFC_READ_TABLE2',
    QUERY_TABLE='TSTCT',
    OPTIONS=[{'TEXT': "TCODE EQ '{}'".format(tcode)}],
    FIELDS=[{'FIELDNAME': 'TTEXT'}],
)
print(len(data['TBLOUT128']))
```

Output (note: data length not printed, because Python completely crashed without error)
```
C:\nwrfcsdk_7.5_PL7
2.1.0
```

Using Patch Level 6, the script executes just fine:
```python
from os import environ
patch_level = '6'
environ['SAPNWRFC_HOME'] = r'C:\nwrfcsdk_7.5_PL{}'.format(patch_level)
environ['PATH'] += r'C:\nwrfcsdk_7.5_PL{}\lib;'.format(patch_level)
print(environ['SAPNWRFC_HOME'])
import pyrfc
print(pyrfc.__version__)
tcode = '/FSCAA/VC_FIELD'
data = pyrfc.Connection(**kwargs).call(
    func_name='/BODS/RFC_READ_TABLE2',
    QUERY_TABLE='TSTCT',
    OPTIONS=[{'TEXT': "TCODE EQ '{}'".format(tcode)}],
    FIELDS=[{'FIELDNAME': 'TTEXT'}],
)
print(len(data))
```

Output (note: the data length prints successfully)
```
C:\nwrfcsdk_7.5_PL6
2.1.0
8
```

Could this be a memory allocation error given the length of the data or could this be an issue with the latest NetWeaver RFC SDK?

**Comment by bsrdjan** [comment]
Yes, there is a known issue with PL7. Which logon language is used ?

Can you stay on PL6, until the fix shipped with PL8 ?

**Comment by boringDev** [comment]
Hi @bsrdjan, thanks for the quick response! Our logon language is EN for most of our use cases. We are able to workaround this until PL8 is released. Thanks again!

**Comment by bsrdjan** [comment]
You can also use this workaround for the PL7: #213
