### ISSUE TITLE
Set a different field length in a query

### ISSUE THREAD

**Issue by emskigdot** [SAP/PyRFC#208]
I wonder if it's possible to set a field length that is different from the default length. In our SAP instance the `GUID` field is 32 characters long. GUI tools return all characters, but PyRFC does not. It seems PyRFC is limited to 16 chars for the `GUID` field of interest.

Minimal example:
Our standard query looks like this

```python
from pyrfc import Connection

conn = Connection(
    user='myuser', 
    passwd='mypassword',
    ashost="server.domain.tld",
    sysnr="00",
    client="001"
)

fields = ['GUID']
Fields = [{'FIELDNAME':x} for x in fields] 

result = conn.call(
    'RFC_READ_TABLE', \
    QUERY_TABLE = 'CRMD_ORDERADM_H',\
    DELIMITER='|',\
    ROWCOUNT = 1,\
    FIELDS=Fields
)

print(result)
```

The result is:

```python
{'DATA': [{'WA': 'CExxxxxxxxxxxxEB'}],
 'FIELDS': [{'FIELDNAME': 'GUID',
   'OFFSET': '000000',
   'LENGTH': '000016',
   'TYPE': 'X',
   'FIELDTEXT': 'GUID of a CRM Order Object'}],
 'OPTIONS': []}
```

My naive approach was to try to set `OFFSET` and `LENGTH` values of the query in a similar way as they are given in the returned value.

```
offset = ['000000']
length= ['000032']
Fields = [{'FIELDNAME':x, 'OFFSET': y, 'LENGTH': z} for x,y,z in zip(fields, offset, length)] 
result = conn.call(
    'RFC_READ_TABLE', 
    QUERY_TABLE = 'CRMD_ORDERADM_H',\
    DELIMITER='|',\
    ROWCOUNT = 1,\
    FIELDS=Fields
)

print(result)
```

The server accepts the query format but unfortunately it does not seem to work. The result is still the same:

```
{'DATA': [{'WA': 'CExxxxxxxxxxxxEB'}],
 'FIELDS': [{'FIELDNAME': 'GUID',
   'OFFSET': '000000',
   'LENGTH': '000016',
   'TYPE': 'X',
   'FIELDTEXT': 'GUID of a CRM Order Object'}],
 'OPTIONS': []}
```

Does anyone have an idea what I should do different here? Thanks in advance for your answer.

Information about my system:
```
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
pynwrfc==2.1.0
```

**Comment by bsrdjan** [comment]
The main issue is using `RFC_READ_TABLE`, a function module that should not be used at all. 

Please check SAP Note [382318 - FAQ|Function module RFC_READ_TABLE](https://launchpad.support.sap.com/#/notes/382318) and this [scn answer](https://answers.sap.com/questions/12356363/rfcreadtable-with-filter-guid.html).

A standard function module or BAPI like GetList should be used instead, to get the list of order ids or GUIDs. The question is more for ABAP consultant/developer.

**Comment by emskigdot** [comment]
Dear @bsrdjan ,
Thank you very much for your answer. I have chosen the function `RFC_READ_TABLE` here for demonstration purposes, because everybody knows this function. Even with an internal customized function the issue remains - same pattern. The reason why I place the issue here is that this actual custom function works well and returns all 32 characters when used by another program.  Only if the function call is executed via PyRFC, the problem with the truncated GUID occurs. So I assumed that the issue can be fixed by adjusting parameters in PyRFC.
I would also like to add that I'm explicitly looking for a way to execute a READ_TABLE function and not a function module.
Do you have any idea why the customized function returns full GUID in another application and not via PyRFC?

**Comment by bsrdjan** [comment]
Hi @emskigdot,

the `RFC_READ_TABLE` can't return GUIDs as expected, no matter which connector used. The reason are above described restrictions of that ABAP function. PyRFC or any other connector can't help with that. On HANA systems you can try SAP Python client [hdbcli](https://pypi.org/project/hdbcli/), or the older one, pure Python [PyHDB](https://pypi.org/project/pyhdb/). Both can read HANA tables. 

If custom function works well when called from another program, is that another program an ABAP report in a same system?

Can you share the signature of that custom function, including DDIC definition of the GUID parameter data element? Or even better full ABAP source code, that I could test locally?

In general, when the RFM output is different when calling via connector, from the output when called from ABAP report, or SE37 transaction, the reasons can be [Conversion Exits, not executed in RFC channel calls](http://sap.github.io/PyRFC/remarks.html#rfc-call-results-differ-from-expected)

**Comment by emskigdot** [comment]
Hi @bsrdjan,

The custom function is designed for and used by an external software called [dab:Exporter](https://www.dab-europe.com/de-DE/dabsoftware/dabexporter), which downloads specified tables.
Unfortunately, I am not allowed to share the full ABAP code publicly. So I tried to print the signature of the function with the example code provided [here](https://github.com/SAP/PyRFC/blob/master/examples/clientPrintDescription.py). Does the output help you?

```
Parameters of function: /XVZX/PROC_DAB_RFC_READ_TABLE
NAME                 PARAMETER_TYPE    DIRECTION   NUC_LENGTH UC_LENGTH DECIMALS  DEFAULT_VALUE   OPTIONAL   TYPE_DESCRIPTION PARAMETER_TEXT       
DELIMITER            RFCTYPE_CHAR      RFC_IMPORT  1          2         0         SPACE           False      None            Text field length 1  
----------------------------------------------------------------------------------------------------------------------------------------
DISTINCT             RFCTYPE_CHAR      RFC_IMPORT  1          2         0         SPACE           False      None            Text field length 1  
----------------------------------------------------------------------------------------------------------------------------------------
FIX                  RFCTYPE_CHAR      RFC_IMPORT  1          2         0         SPACE           False      None            Text field length 1  
----------------------------------------------------------------------------------------------------------------------------------------
NO_DATA              RFCTYPE_CHAR      RFC_IMPORT  1          2         0         SPACE           False      None            Text field length 1  
----------------------------------------------------------------------------------------------------------------------------------------
QUERY_TABLE          RFCTYPE_CHAR      RFC_IMPORT  30         60        0                         False      None            Table Name           
----------------------------------------------------------------------------------------------------------------------------------------
ROWCOUNT             RFCTYPE_INT       RFC_IMPORT  4          4         0         0               False      None            SAPoffice: Type I    
----------------------------------------------------------------------------------------------------------------------------------------
ROWSKIPS             RFCTYPE_INT       RFC_IMPORT  4          4         0         0               False      None            SAPoffice: Type I    
----------------------------------------------------------------------------------------------------------------------------------------
DATA                 RFCTYPE_TABLE     RFC_TABLES  2048       4096      0                         False      TBL2048         Empty structure, width 2048 Bytes 
    -----------( Structure of TBL2048 (n/uc_length=2048/4096)--
NAME                 FIELD_TYPE        NUC_LENGTH NUC_OFFSET UC_LENGTH UC_OFFSET DECIMALS   TYPE_DESCRIPTION 
LINE                 RFCTYPE_CHAR      2048       0          4096      0         0          None            
    -----------( Structure of TBL2048 )-----------
----------------------------------------------------------------------------------------------------------------------------------------
FIELDS               RFCTYPE_TABLE     RFC_TABLES  103        206       0                         False      RFC_DB_FLD      RFC Table Read: Description of Fields to Retrieve 
    -----------( Structure of RFC_DB_FLD (n/uc_length=103/206)--
NAME                 FIELD_TYPE        NUC_LENGTH NUC_OFFSET UC_LENGTH UC_OFFSET DECIMALS   TYPE_DESCRIPTION 
FIELDNAME            RFCTYPE_CHAR      30         0          60        0         0          None            
OFFSET               RFCTYPE_NUM       6          30         12        60        0          None            
LENGTH               RFCTYPE_NUM       6          36         12        72        0          None            
TYPE                 RFCTYPE_CHAR      1          42         2         84        0          None            
FIELDTEXT            RFCTYPE_CHAR      60         43         120       86        0          None            
    -----------( Structure of RFC_DB_FLD )-----------
----------------------------------------------------------------------------------------------------------------------------------------
OPTIONS              RFCTYPE_TABLE     RFC_TABLES  72         144       0                         False      RFC_DB_OPT      RFC Table Read: Select Options / WHERE Clause 
    -----------( Structure of RFC_DB_OPT (n/uc_length=72/144)--
NAME                 FIELD_TYPE        NUC_LENGTH NUC_OFFSET UC_LENGTH UC_OFFSET DECIMALS   TYPE_DESCRIPTION 
TEXT                 RFCTYPE_CHAR      72         0          144       0         0          None            
    -----------( Structure of RFC_DB_OPT )-----------
----------------------------------------------------------------------------------------------------------------------------------------
```

Since I am not an ABAP developer, I don`t have the authorization to use SE11 or SE80 for displaying DDIC definition of the GUID parameter data element.
What a found out is that CRMT_OBJECT_GUID in table CRMD_ORDERADM_H or GUID_16  (for example in table SWW_WI2OBJ)  is used as data element for field GUID. Is there another way of retrieving DDIC definition of the GUID parameter data element?

Thank you very much for your answer in advance. I really appreciate you support.

**Comment by bsrdjan** [comment]
Yes, there is another way to get DDIC definition. You can try the [rfmcall.py](https://github.com/sap/fundamental-tools#rfmcall-and-backendpy) script, from [sap/fundamental-tools](https://github.com/sap/fundamental-tools):

The ABAP system connection parameters shall be maintained in `sapnwrfc.ini` file, in `tools` folder. Example:

**sapnwrfc.ini**
```ini
DEST=ABC
USER=demo
PASSWD=welcome
ASHOST=coevi51
SYSNR=00
CLIENT=620
LANG=EN
```


```shell
git clone https://github.com/sap/fundamental-tools
cd tools
python rfmcall.py ABC /XVZX/PROC_DAB_RFC_READ_TABLE
```

**Comment by emskigdot** [comment]
Thanks for your input. I tried your suggested approach. Unfortunately, it ended with error message `RFC_NO_AUTHORITY`. 
So, I asked a guy from our IT department and he told me that in table CRMD_ORDERADM_H the DDIC definition of GUID is CRMT_OBJECT_GUID RAW 16 Byte Sequence. 
I noticed that it is only possible to enter hex code character into the query interface. To my knowledge 16 Byte would correspond to 32 hex characters. If pyRFC interprets the hex code as ascii strings, it may stop transmitting after the 16th character. Could it be, that this is an encoding issue?

**Comment by bsrdjan** [comment]
Hi @emskigdot and sorry for the late response. The CRMD_ORDERADM_H-GUID is indeed RAW16 sequence. 

That sequence comes over RFC channel as a sequence of bytes and as such represented in Python (`bytes()`). One example is in unit tests:

[PyRFC/test/test_datatypes.py#L361](https://github.com/SAP/PyRFC/blob/master/tests/test_datatypes.py#L361)

**Comment by YashGhaisas** [comment]
Hi @emskigdot @bsrdjan 
Im facing the same issue while using the RFC_READ_TABLE.
@emskigdot can you help me with this? 
Example - If the value is - '005056AE436A1EE682FA84AD95D5B572', then I'm getting only - '005056AE436A1EE6'

**Comment by bsrdjan** [comment]
The issue is caused by `RFC_READ_TABLE` limitation. described in a first answer above: https://github.com/SAP/PyRFC/issues/208#issuecomment-737235847

It can't be fixed by PyRFC and the recommended solution is not using `RFC_READ_TABLE`.

**Comment by YashGhaisas** [comment]
@bsrdjan Thanks for the reply!
But, is there any alternative for PyRFC for getting the data which can give me complete UUID values from SAP ERP ECC tables? 
Thanks in advance!

**Comment by bsrdjan** [comment]
When the backend system is HANA system, the SAP HANA client for Python can be used. It works with tables directly: https://pypi.org/project/hdbcli/ 

When the backend system is ABAP system, the `RFC_READ_TABLE` should not be used because issues are guaranteed, sooner or later. The first step here is to check if BAPIs or other ABAP remote function modules (RFM) are already available, to read or update the tables. If not, custom RFMs should be provided (ABAP development). Then the PyRFC can consume these BAPIs/RFMs.

Which tables are in question and did you check if BAPIs/RFMs are available ?
