### ISSUE TITLE
Unable to connect SAP system from python using PYRFC, SAPGUI login works fine

### ISSUE THREAD

**Issue by rushikeshk-k** [SAP/PyRFC#212]
Hi @bsrdjan
I am working on to create connection of Python with SAP ECC using PYRFC. When I try it from SAPGUI my connection works fine, but when tried it from Python code it does not work on my PC. But again it works from my other team members pc from python

So I checked all the configuration on my pc, are identical to other members pc. So I am clueless now,

- Server details are changed to - XYZ.com

```shell
root@4a4ed54a8426:/app/models# python Check_pyrfc.py
Traceback (most recent call last):
  File "Check_pyrfc.py", line 4, in <module>
    conn = Connection(user='BOTID', passwd='XXXXX', ashost='XYZ.com', sysnr='50', client='100')
  File "src/pyrfc/_pyrfc.pyx", line 173, in pyrfc.pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 221, in pyrfc.pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 251, in pyrfc.pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host 4a4ed54a8426 with Unicode
ERROR       partner 'XYZ.com:3350' not reached
TIME        Thu Nov 26 14:11:34 2020
RELEASE     753
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      /bas/753_REL/src/base/ni/nibuf.cpp
LINE        4568
DETAIL      NiBufIConnect: connection pending after 60000ms
SYSTEM CALL connect
ERRNO       115
ERRNO TEXT  Operation now in progress
COUNTER     4
 [MSG: class=, type=, number=, v1-4:=;;;]
```

When checked with nslookup, I get proper IP of the server

```shell
C:\Program Files (x86)\SAP\FrontEnd\SAPgui>nslookup XYZ.com
Server:  XYZ.com
Address:  11.106.2.13 (ip changed)

Non-authoritative answer:
Name:    XYZ.com
Address:  192.30.33.16 (ip changed)
```

Need your urgent help to find out the exact reason and where to fix it. As per your comments in other issue I tried Niping, it also works fine. Please let me know if you need any more details.

Thank you in advance for  your help

**Comment by bsrdjan** [comment]
Perhaps the domain name resolution does not resolve the XYZ.com to ip addr. Did you try to replace the hostname with the host ip address in `ashost` connection parameter?

**Comment by rushikeshk-k** [comment]
Thank you for your response. 
I tried with both XYZ.com and with Ip directly in my python code as below. I works fine from SAPGUI, also works from my team members pc. But when I am trying to connect from my pc it does not work and I am getting same error,
--------------------------------------------
from pyrfc import Connection

conn = Connection(user='BOTID', passwd='XXXXX', ashost='XYZ.com', sysnr='50', client='100')
#conn = Connection(user='BOTID', passwd='XXXXX, ashost='192.30.33.16', sysnr='50', client='100')

result = conn.call('STFC_CONNECTION', REQUTEXT=u'Hello SAP!')
print(result)
{u'ECHOTEXT': u'Hello SAP!',
 u'RESPTEXT': u'SAP R/3 Rel. 702   Sysid: ABC   Date: 20121001   Time: 134524   Logon_Data: 100/ME/E'}
------------------------------------------

Error:
 File "src/pyrfc/_pyrfc.pyx", line 173, in pyrfc.pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 221, in pyrfc.pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 251, in pyrfc.pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host 4a4ed54a8426 with Unicode
ERROR       partner 'XYZ.com:3350' not reached
TIME        Thu Nov 26 16:34:15 2020
RELEASE     753
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      /bas/753_REL/src/base/ni/nibuf.cpp
LINE        4568
DETAIL      NiBufIConnect: connection pending after 60000ms
SYSTEM CALL connect
ERRNO       115
ERRNO TEXT  Operation now in progress
COUNTER     4
 [MSG: class=, type=, number=, v1-4:=;;;]

----------------

One thing I notices when I tried from SAPGUI it connect to "XYZ.com:sapdp50 (3250) and when I try it from Python code it connect to XYZ.com:3350.

Do I need to check on firewall setting or  add this ip and port anywhere to give network access??

Thank you in advance for your kind help.. much needed

**Comment by bsrdjan** [comment]
Looks like port for the load balancer is missing. Please check similar issues: https://github.com/SAP/node-rfc/issues/146 and https://github.com/SAP/PyRFC/issues/79, also the "Parameters for load balancing" example in `sapnwrfc.ini` file, in SAP NWRFC SDK `demo` folder.

You can try with

```ini
MSHOST=XYZ.com
MSSERV=3250
```

instead of:

```ini
ASHOST=XYZ.com
SYSNR=50
```

**Comment by rushikeshk-k** [comment]
Thank you for your response!

after trying,
MSHOST=XYZ.com
MSSERV=3250

I got below error
--------------------------------
[Thr 20400] Fri Nov 27 01:30:43:185 2020
[Thr 20400] +--------+-------------------------------------+------------------+
[Thr 20400] | Offset | Data (14 bytes)
[Thr 20400] +--------+-------------------------------------+------------------+
[Thr 20400] | 000000 | 2a2a4450 544d4d53 472a2a00 00f8     | **DPTMMSG**...   |
[Thr 20400] +--------+-------------------------------------+------------------+
Traceback (most recent call last):
  File "Check_pyrfc.py", line 3, in <module>
    conn = Connection(user='BOTID', passwd='XXXX', mshost='XYZ.com', msserv ='3250', client='100')    
  File "src\pyrfc\_pyrfc.pyx", line 173, in pyrfc.pyrfc.Connection.__init__
  File "src\pyrfc\_pyrfc.pyx", line 221, in pyrfc.pyrfc.Connection._open
  File "src\pyrfc\_pyrfc.pyx", line 251, in pyrfc.pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
ERROR       The message received isn't from a message server.
            Are you really connected to the message server?
            Please check your connection parameters.
            (XYZ.com / 3250)
TIME        Fri Nov 27 01:30:43 2020
RELEASE     753
COMPONENT   MS (message handling interface, multithreaded)
VERSION     4
RC          -29
MODULE      D:/depot/bas/753_REL/src/krn/ms/msxxi.c
LINE        382
COUNTER     1
 [MSG: class=, type=, number=, v1-4:=;;;]

I really appreciate your help on it.

**Comment by bsrdjan** [comment]
Not sure what could be the problem. Could you please share the screenshot of system connection parameters, from SAP Logon client? Example:
<img width="629" alt="SAPGUI" src="https://user-images.githubusercontent.com/1697847/100447544-15eb0300-30b1-11eb-9e0a-930fdacf7f2e.png">

**Comment by rushikeshk-k** [comment]
Hi bsrdjan

Now my connection is working from Python running on windows. but same code id I am running from Docker -Linux image it is giving same error. Do you have any idea about Docker, if any change needs to be made to make connection happen
ERROR       partner 'XYZ.com:3350' not reached
TIME        Thu Nov 26 16:34:15 2020
RELEASE     753
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      /bas/753_REL/src/base/ni/nibuf.cpp
LINE        4568
DETAIL      NiBufIConnect: connection pending after 60000ms
SYSTEM CALL connect
ERRNO       115
ERRNO TEXT  Operation now in progress
COUNTER     4
 [MSG: class=, type=, number=, v1-4:=;;;]

Thanks a ton for your response and help

**Comment by bsrdjan** [comment]
The same connection parameters should work from docker as well, no special changes required for docker.

Did you try the IP instead of XYZ.com ?

**Comment by rushikeshk-k** [comment]
bsrdjan, Thank you for your response.
I tried with IP as well, but still not working. But it works perfectly fine from Python on Windows.

**Comment by bsrdjan** [comment]
It looks like a network error. Did you try the [niping test](https://github.com/SAP/PyRFC/issues/180#issuecomment-634859449) from docker ?

You can also try with [SAP/fundamental-tools docker images](https://github.com/SAP/fundamental-tools/tree/master/docker), regularly used in testing, like the [python-39.Dockerfile](https://github.com/SAP/fundamental-tools/blob/master/docker/python-39.Dockerfile) for example.

**Comment by bsrdjan** [comment]
@rushikeshk-k ,

if it works on Windows and not on other platforms, please check this [answer](https://github.com/SAP/PyRFC/issues/220#issuecomment-777403081) and try with:

```shell
pip uninstall pynwrfc
PYRFC_BUILD_CYTHON=yes pip install pynwrfc --no-binary :all:
```

**Comment by bsrdjan** [comment]
Please try also 2.4.0: `pip install pyrfc` (package name changed and upgrade to SDK PL8 first)

**Comment by bsrdjan** [comment]
@abdullahansari00 no, all prerequisites are listed in README: https://github.com/SAP/PyRFC
