### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by tahakapadia** [SAP/PyRFC#216]
I am trying to install pyrfc and using pyrfc-2.0.2-cp37-cp37m-win_amd64.whl,
i have python version - 3.7.9
I have set Environment variable to - C:\nwrfcsdk\lib;C:\nwrfcsdk
I have SAP NW RFC SDK installed.
still i am getting below error
Traceback (most recent call last):
  File "check.py", line 1, in <module>
    import pyrfc
  File "C:\Users\TahaKapadia\Python37\lib\site-packages\pyrfc\__init__.py", line 22, in <module>
    from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
ImportError: DLL load failed: The specified module could not be found.

Can anyone help me with the solution?
I have also tried pyrfc-1.9.93-cp37-cp37m-win_amd64.whl but still the same error

**Comment by bsrdjan** [comment]
Did you check if the SAP NWRFC SDK installation, following the [documentation](http://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation) ? What is the output of `rfcexec` ?

**Comment by tahakapadia** [comment]
I am not getting any output when i run ./rfcexec it just goes to next commandline is this correct?

**Comment by bsrdjan** [comment]
That is not correct, sorry for the late reply. The output should be like described in the documentation:
http://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation

Which SAP NWRFC SDK version are you using?

Could it be you downloaded SAP NWRFC SDK 32bit instead of 64bit? Or for another platform maybe?

**Comment by bsrdjan** [comment]
Please reopen if needed
