### ISSUE TITLE
Python 3.9: error during "pip install pynwrfc --no-binary :all:"

### ISSUE THREAD

**Issue by pg74-crypto** [SAP/PyRFC#217]
Dears,
I followed instructions to install PYRFC on Windows 10 :

- Python Version 3.9.1
- Installed NWRFCSDK in folder C:\DATA\nwrfcsdk
- Added C:\DATA\nwrfcsdk\LIB and C:\Data\nwrfcsdk\bin to PATH variable
- Set SAPNWRFC_HOME = C:\DATA\NWRFCSDK
- Installed Visual C++ Redistributable for Visual Studio 2013
- Installed Microsoft C++ Build Tools

I run "pip install pynwrfc --no-binary :all:" which finished with error. Here attached the log.

```shell
**********************************************************************************
Microsoft Windows [Version 10.0.18363.1316]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Name\PycharmProjects\RFC>pip install pynwrfc --no-binary :all:
Collecting pynwrfc

Requirement already satisfied: setuptools in c:\users\User1\appdata\local\programs\python\python39\lib\site-packages (from pynwrfc) (51.3.3)
Skipping wheel build for pynwrfc, due to binaries being disabled for it.
Installing collected packages: pynwrfc
    Running setup.py install for pynwrfc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\User1\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'
C:\\Users\\User1\\AppData\\Local\\Temp\\pip-install-4br1yo9y\\pynwrfc_f5d6fba24b8f413697a82c8d8a71f0d5\\setup.py'"'"'; __file__='"'"'C:\\User
s\\User1\\AppData\\Local\\Temp\\pip-install-4br1yo9y\\pynwrfc_f5d6fba24b8f413697a82c8d8a71f0d5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"
'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\User
s\User1\AppData\Local\Temp\pip-record-6puzhs6p\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\
User1\appdata\local\programs\python\python39\Include\pynwrfc'
         cwd: C:\Users\User1\AppData\Local\Temp\pip-install-4br1yo9y\pynwrfc_f5d6fba24b8f413697a82c8d8a71f0d5\
    Complete output (22 lines):
    750 Patch Level 6
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pyrfc
    copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.9\pyrfc
    copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.9\pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    creating build\temp.win-amd64-3.9\Release\src\pyrfc
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DS
APonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -D
NDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKEUser1=ntintel -Ic
:\users\User1\appdata\local\programs\python\python39\include -Ic:\users\User1\appdata\local\programs\python\python39\include -I
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\20
19\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\incl
ude\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um
 -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpsrc/py
rfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.9\Release\src/pyrfc/_pyrfc.obj -IC:\Data\nwrfcsdk\include -Ic:\users\User1\appdata\local\programs\py
thon\python39\lib\inspect.py\Include -Ic:\users\User1\appdata\local\programs\python\python39\lib\inspect.py\Include\PC /EHs /Gy /J /MD /nolog
o /W3 /Z7 /GL /O2 /Oy- /we4552 /we4700 /we4789
    _pyrfc.cpp
    src/pyrfc/_pyrfc.cpp(3648): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
    src/pyrfc/_pyrfc.cpp(17190): error C2664: 'PyObject *__pyx_f_5pyrfc_5pyrfc_wrapString(SAP_UC *,__pyx_opt_args_5pyrfc_5pyrfc_wrapString *)': cannot conv
ert argument 1 from 'const SAP_UC *' to 'SAP_UC *'
    src/pyrfc/_pyrfc.cpp(17190): note: Conversion loses qualifiers
    src/pyrfc/_pyrfc.cpp(2141): note: see declaration of '__pyx_f_5pyrfc_5pyrfc_wrapString'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed wit
h exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\User1\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptoo
ls, tokenize; sys.argv[0] = '"'"'C:\\Users\\User1\\AppData\\Local\\Temp\\pip-install-4br1yo9y\\pynwrfc_f5d6fba24b8f413697a82c8d8a71f0d5\\setu
p.py'"'"'; __file__='"'"'C:\\Users\\User1\\AppData\\Local\\Temp\\pip-install-4br1yo9y\\pynwrfc_f5d6fba24b8f413697a82c8d8a71f0d5\\setup.py'"'"
';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'
"'"'))' install --record 'C:\Users\User1\AppData\Local\Temp\pip-record-6puzhs6p\install-record.txt' --single-version-externally-managed --com
pile --install-headers 'c:\users\User1\appdata\local\programs\python\python39\Include\pynwrfc' Check the logs for full command output.
```
[Log_Install_pynwrfc.txt](https://github.com/SAP/PyRFC/files/5867860/Log_Install_pynwrfc.txt)
****************************************************************************************

Really many thanks in advance for your help

**Comment by pg74-crypto** [comment]
Dear Srdjan, many thanks for your advices. 
I've run commands from Git. When i run "python setup.py bdist_wheel" i got the following error:

LINK : fatal error LNK1181: cannot open input file 'libsapucum.lib'

Here's the full log. Many thanks!

******************************************************************************************************************************
750 Patch Level 6
running bdist_wheel
running build
running build_py
running build_ext
building 'pyrfc.pyrfc' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPon
NT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEB
UG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -IC:\Us
ers\piergiorgio.grazian\AppData\Local\Programs\Python\Python39\include -IC:\Users\piergiorgio.grazian\AppData\Local\Programs\Python\Python39\include -IC:\P
rogram Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\B
uildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\
10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC
:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpsrc/pyrfc/
_pyrfc.cpp /Fobuild\temp.win-amd64-3.9\Release\src/pyrfc/_pyrfc.obj -IC:\Data\nwrfcsdk\include -IC:\Users\piergiorgio.grazian\AppData\Local\Programs\Python
\Python39\lib\inspect.py\Include -IC:\Users\piergiorgio.grazian\AppData\Local\Programs\Python\Python39\lib\inspect.py\Include\PC /EHs /Gy /J /MD /nologo /W
3 /Z7 /GL /O2 /Oy- /we4552 /we4700 /we4789
_pyrfc.cpp
src/pyrfc/_pyrfc.cpp(3646): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIF
EST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\piergiorgio.grazian\AppData\Local\Programs\Python\Python39\libs /LIBPATH:C:\Users\piergiorgio.grazian\AppD
ata\Local\Programs\Python\Python39\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\ATLMFC\l
ib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Ki
ts\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10
.0.18362.0\um\x64 sapnwrfc.lib libsapucum.lib /EXPORT:PyInit_pyrfc build\temp.win-amd64-3.9\Release\src/pyrfc/_pyrfc.obj /OUT:build\lib.win-amd64-3.9\pyrfc
\pyrfc.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\src/pyrfc\pyrfc.cp39-win_amd64.lib -LIBPATH:C:\Data\nwrfcsdk\lib -LIBPATH:C:\Users\pierg
iorgio.grazian\AppData\Local\Programs\Python\Python39\lib\inspect.py\PCbuild /NXCOMPAT /STACK:0x2000000 /SWAPRUN:NET /DEBUG /OPT:REF /DEBUGTYPE:CV,FIXUP /M
ACHINE:amd64 /nologo /LTCG
LINK : fatal error LNK1181: cannot open input file 'libsapucum.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with
exit code 1181

**********************************************************************************************************************************

**Comment by bsrdjan** [comment]
Did you install SAP NWRFC SDK binaries ([documentation](http://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation))? The SAPNWRFC_HOME env variable should be set, so that compiler can find the SDK.

**Comment by pg74-crypto** [comment]
Dear Srdjan, I did. 
But but since I just  had "libsapucum.so" in the folder nwrfcsdk\lib (as per nwrfc750P_7-70002726.zip file) I also moved there 'libsapucum.lib' (found elsewhere...). and it seems working fine. At least till the execution of the last command: 

Here the actions summary:

1) C:\Users\User1\AppData\Local\Programs\Python\Python39\Lib\site-packages>git clone https://github.com/SAP/PyRFC.git --> OK
2) C:\Users\User1\AppData\Local\Programs\Python\Python39\Lib\site-packages>cd pyrfc  --> OK
3) C:\Users\User1\AppData\Local\Programs\Python\Python39\Lib\site-packages\PyRFC>python setup.py bdist_wheel --> OK
4) C:\Users\User1\AppData\Local\Programs\Python\Python39\Lib\site-packages\PyRFC>pip install --upgrade --no-index --find-links=dist pynwrfc--> KO

Here's the log:

Looking in links: dist
ERROR: Could not find a version that satisfies the requirement pynwrfc
ERROR: No matching distribution found for pynwrfc


Many thanks again!

**Comment by bsrdjan** [comment]
Sorry, the package name is changed in main branch, but you can try:

```shell
pip install --upgrade --no-index --find-links=dist pyrfc # instead of pynwrfc
```

or 

```shell
pip install .\dist\pynwrfc-2.3.0-cp36-cp36m-win_amd64.whl # or whatever is the filename in dist on your system
```

**Comment by pg74-crypto** [comment]
Many Thanks! It worked well. I just had (at the end) to rename "PyRFC" directory with lower case letters ("pyrfc") inside site-packages.
