### ISSUE TITLE
pynwrfc-2.3.0-cp39*linux* : Long Parameter problem (alone import parameter more that CHAR520 and TAB param with multi lines)

### ISSUE THREAD

**Issue by OlegBash599** [SAP/PyRFC#219]
It seems that in pynwrfc-2.3.0-cp39*linux* there is a problem with calling functions with long parameter:

case1)  where there is an import alone (not tab) parameter with character-type more than char 520.
ABAP-interface of such functions is (in my case):
```abap
*"  IMPORTING
*"     VALUE(IV_PARAM1) TYPE  **TEXT4096** OPTIONAL
*"  EXPORTING
*"     VALUE(EV_ERROR_TEXT) TYPE  TEXT100
```
case2) where there is a call with several lines for table-type import parameter
abap-function sample code

```abap
FUNCTION z_bc009_params.
*"----------------------------------------------------------------------
*"*"Локальный интерфейс:
*"  IMPORTING
*"     VALUE(IT_CHAR_INT_TAB) TYPE  ZTTBC009_CHAR_N_INT_STRUCT
*"  EXPORTING
*"     VALUE(EV_SUBRC) TYPE  SYSUBRC
*"     VALUE(ET_TXT) TYPE  TLINE_TAB
*"----------------------------------------------------------------------


  FIELD-SYMBOLS <fs_txt> TYPE tline.
  DO 3 TIMES.
    APPEND INITIAL LINE TO et_txt ASSIGNING <fs_txt>.
    <fs_txt>-tdline = 'test tab response'.

  ENDDO.

ENDFUNCTION.
```

![abap_function_sample](https://user-images.githubusercontent.com/46314639/107176959-b29b1c80-69e1-11eb-938e-49dafc08c323.jpg)

![ZSBC009_CHAR_N_INT_STRUCT_structure](https://user-images.githubusercontent.com/46314639/107176398-55529b80-69e0-11eb-8732-5332773f9d83.png)
![ZTTBC009_CHAR_N_INT_STRUCT_table_type](https://user-images.githubusercontent.com/46314639/107176400-55eb3200-69e0-11eb-9c49-0c964e88def5.png)

code for python-call

```python
import os
from pyrfc import Connection
import ZNWCredentials as trg
def main():
    print('...')
    conn = Connection(user=trg.LOGIN,passwd=trg.PSWD,ashost=trg.HOST,
            sysnr=trg.SYS_NUMBER,client=trg.MANDANT)
    print('trying 1st simple call with short parameter')
    result = conn.call('RFC_GET_SYSTEM_INFO',DESTINATION='NONE')
    print('1st call done')
    print('trying 2nd call  with char/int tab')
    char_int_tab = [] 
    char_int_line=dict(PARAM1_CHAR12=str('test1'),
                    PARAM2_CHAR12=str('test2'),
                    PARAM3_INT4=int('10'),
                    PARAM4_INT4=int('12'),
                    PARAM5_CHAR100='asdasd asdasdqw ')
    for sytabix in range(10):
        char_int_tab.append(char_int_line)
    result = conn.call('Z_BC009_PARAMS', IT_CHAR_INT_TAB=char_int_tab)
    print('after conn')
    conn.close
    print(result)
if __name__ == '__main__':
    main()
```

![main_py](https://user-images.githubusercontent.com/46314639/107177205-5389d780-69e2-11eb-9bc7-1773bbcfe2f9.jpg)

pynwrfc just stop calling such functions. Without exceptions, without message; just stop on the line of calling.

as a result connection just does not call function.

I am using the following for the test specified
- Fedora Server 33
- python3.9.1.
- pynwrfc-2.3.0-cp39-cp39-linux_x86_64.whl (I have build via wget and  pip install *whl)
- nwrfc750P_7-70002752.zip (which is latest patch for NW RFC SDK)

I also want to outline that with the following on another computer it is working fine:
- fedora
- python3.8.7
- nwrfc750P_5-70002752.zip
- 38whl and pip install pynwrfc

[ABAP_FUNCTION_Z_BC009_PARAMS.abap.txt](https://github.com/SAP/PyRFC/files/5942015/ABAP_FUNCTION_Z_BC009_PARAMS.abap.txt)
[main.py.txt](https://github.com/SAP/PyRFC/files/5942017/main.py.txt)

**Comment by bsrdjan** [comment]
The cause might the build from the PyRFC c++ source on Fedora. c++ source is generated on last internal test system, most probably Darwin. There might be issues building/running these CPP sources on Fedora.

Could you please uninstall `pynwrfc`, re-build from pyx source and re-test:

```shell
git clone https://github.com/SAP/PyRFC
cd PyRFC
git checkout tags/2.3.0
PYRFC_BUILD_CYTHON=yes python setup.py bdist_wheel
# the wheel should be built in dist, install it from there
pip uninstall pynwrfc
pip install dist/pyrfc-...
```

If the issue still occurs, please post the full console log of the wheel build.

**Comment by OlegBash599** [comment]
all actions are done inside VirtualMachine (VirtualBox), under root

---------------------------------------------------------------------
**TestRun1**) I have created machine:
- Fedora 32, 
- python 3.8.5
- nwrfc750P_7-70002752.zip
- /2.3.0/pynwrfc-2.3.0-cp38-cp38-linux_x86_64.whl

The RFC above and python-script works **successful** as expected. No problems. 


**TestRun2**) machine:
- Fedora 33
- python 3.9.1
- nwrfc750P_7-70002752.zip
- /2.3.0/pynwrfc-2.3.0-cp39-cp39-linux_x86_64.whl

The RFC above and python-script works **WRONG** with problem as described.
Logs on installation as requested (logs are ok mostly) and with command (there is error inside)
`pip install pynwrfc --force-reinstall`

[console_logs.zip](https://github.com/SAP/PyRFC/files/5962264/console_logs.zip)

**Comment by bsrdjan** [comment]
@OlegBash599,

please see [my answer to #220](https://github.com/SAP/PyRFC/issues/220#issuecomment-777403081).

Did you try the PyRFC build from source:

```shell
pip uninstall pynwrfc
PYRFC_BUILD_CYTHON=yes pip install pynwrfc --no-binary :all:
```

**Comment by OlegBash599** [comment]
@bsrdjan 
yes, I have tried this. as for compilation itself (which is issue in [220](url)) - it is ok. But compilation was ok from wheel before.

However  for the current issue it does NOT help. The RFC with long parameters are not called without any messages or exceptions.

**Comment by bsrdjan** [comment]
@OlegBash599, my suspicion was that the cause could be improper installation. There are subtle differences and wheel built on one Linux might behave strange on another. The only reliable installation on Linux is build from source.

Can you maybe test/reproduce the issue on Ubuntu, Debian, Centos, Darwin or Windows? These platforms I have at hand, can test faster. Fedora need to build the docker first, would take me some time. Do you maybe have a Dockerfile for Fedora, where PyRFC can be pip installed ?

**Comment by OlegBash599** [comment]
I will try to reproduce it on Ubuntu and return with results.
The test env for me now is VirtualBox, not Docker - so I could not provide Docker file.

**Comment by OlegBash599** [comment]
@bsrdjan 
I have done all steps for Ubuntu with python3.9.0 - it is fine. 
Also I have reproduce all steps with Fedora Server 33 with absolutely new Installation (python3.9.1) - it is fine.

So, building via Cython could close the issue. **_thank you very much_**!

However, then I have compare all steps for previous virtual Machine and the new one and found that there is a misleading information in the installation docs.

In documentation (which is [here ](url) and also [here ](url)) said there should be **libgssapi.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgssapi.so.3** but it seems it is not necessary. In fedora to meet the requirement I had to install separate package with dependencies. 

The second mistake or mislead seems to be NOT fully installed **gcc** and **python devel** tools . It seems not all libs were correctly installed. I have solved it with installation by mask (but not by specific package) like that (only officially initially installed repos were used):
`
sudo dnf install gcc*
`

`
sudo dnf install python*devel
`


It was really strange bug / mis-installation: the call was working only a partly :-). And it was installed fine by wheel :-)

So, my question/proporsal - is to create a check-point (check point actions and libs) during installation not to mislead. I could do that for Fedora, could I?)

**Comment by bsrdjan** [comment]
@OlegBash599, glad to hear the issue solved. I could not open documentation links, could you please check and re-send?

> (which is here and also here)

Could you eventually share the steps you followed on Fedora? That would help create the docker image for PyRFC on Fedora, which is still missing here: [SAP/fundamental-tools/docker](https://github.com/SAP/fundamental-tools/tree/main/docker)

**Comment by OlegBash599** [comment]
This link:
https://github.com/SAP/PyRFC/blob/master/doc/install.rst

`
Could you eventually share the steps you followed on Fedora? That would help create the docker image for PyRFC on Fedora, which is still missing here: SAP/fundamental-tools/docker
`
I will do that and provide the steps description for fedora Server.
