### ISSUE TITLE
Question: Is it possible to call a SAP transaction?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#22]
Is it possible to call a transaction like in SAP GUI e.g. VA01?

Or is a transaction like e.g. VA01  just processed by some BAPI behind the scenes of SAP GUI? If so - how to find out which BAPI(s) a transaction refers to?

**Comment by bsrdjan** [comment]
Not all transactions use BAPIs, some more, some less. A good starting point is `BAPI` transaction (`/nbapi`) showing the overview of Business Objects and related BAPIs:

![screen shot 2016-10-14 at 12 46 48](https://cloud.githubusercontent.com/assets/1697847/19384978/a032a90c-920c-11e6-812e-8c77fb4592c8.png)

**Comment by Tset-Noitamotua** [comment]
That's really a good starting point. As a total SAP noob I already found out how to use some of the information with PyRFC. 

Business Object and BAPIs: 
![image](https://cloud.githubusercontent.com/assets/5635462/19385703/56599f4e-9210-11e6-9ff7-057f35de93f8.png)

The details of a BAPI method reveal it's technical name which have to be used with PyRFC:
![image](https://cloud.githubusercontent.com/assets/5635462/19385831/32e8d9ac-9211-11e6-9e00-14f0bf3100fa.png)

Using transaction `SE37` one get further information which are needed to know how to call the desired BAPI correctly:
![image](https://cloud.githubusercontent.com/assets/5635462/19385894/a616a864-9211-11e6-8330-a71db045c825.png)

Here we see that `BAPI_USER_EXISTENCE_CHECK` takes one not optional (thus mandatory) argument `USERNAME` which we have to provide a value when doing a call:
![image](https://cloud.githubusercontent.com/assets/5635462/19385960/056579da-9212-11e6-8181-1b8c47dc15a7.png)

When we do a call we get some response like below:
```
>>> mysap.call('BAPI_USER_EXISTENCE_CHECK', USERNAME='horst')
{'RETURN': {'SYSTEM': 'DESTENATION_123', 'MESSAGE_V2': '', 'ROW': 0, 'MESSAGE_V4': '', 'TYPE': 'I', 'MESSAG
E_V1': 'HORST', 'MESSAGE': 'Benutzer HORST existiert.', 'LOG_MSG_NO': '000000', 'LOG_NO': '', 'FIELD'
: '', 'PARAMETER': '', 'NUMBER': '088', 'MESSAGE_V3': '', 'ID': '01'}}
```

**Comment by Tset-Noitamotua** [comment]
In case of `BAPI_USER_EXISTENCE_CHECK` things were relatively easy.

But what about BAPIs like `BAPI_SALESORDER_CREATEFROMDAT2`? The only mandatory argument it takes is `ORDER_HEADER_IN` which is not represented by a single value like "horst" in case of BAPI_USER_EXISTENCE_CHECK. I gues it's some more complex data structure. But how to find out how this data structure looks like? And how would the syntax of a correct PyRFC call to such BAPI look like?

**Comment by bsrdjan** [comment]
Examples are given in the [documentation](http://sap.github.io/PyRFC/client.html). 
How data structure looks like you may see in SE37 or, programatically, via the RFC_METADATA_GET RFC call, which you can also test locally, in SE37.
