### ISSUE TITLE
Compile error, cannot install

### ISSUE THREAD

**Issue by Garfius** [SAP/PyRFC#220]
Steps to reproduce:
Install  ubuntu-20.04.1-live-server-amd64.iso (Ubuntu 20.04.1 LTS)
Install python 3.8 (apt-get install python3 python3-pip)
Download and unzip: (nwrfc750P_7-70002752.zip || nwrfc750P_3-70002752.zip) neither works
Set environment variable: (export SAPNWRFC_HOME=/usr/my/Folder/nwrfcsdk)

At this point either pip install or github download or compile results are the same:

Error:

> src/pyrfc/_pyrfc.cpp:17190:48: error: invalid conversion from ‘const SAP_UC*’ {aka ‘const char16_t*’} to ‘SAP_UC*’ {aka ‘char16_t*’}

Full Output:
>ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k5px9zhp/pynwrfc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k5px9zhp/pynwrfc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-55xlli1_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/bruce/.local/include/python3.8/pynwrfc
         cwd: /tmp/pip-install-k5px9zhp/pynwrfc/
    Complete output (25 lines):
    750 Patch Level 7
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyrfc
    copying src/pyrfc/_exception.py -> build/lib.linux-x86_64-3.8/pyrfc
    copying src/pyrfc/__init__.py -> build/lib.linux-x86_64-3.8/pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/pyrfc
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG -D_LARGEFILE_SOURCE -D_CONSOLE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -DSAPwithTHREADS -DSAPonLIN -I/usr/include/python3.8 -c src/pyrfc/_pyrfc.cpp -o build/temp.linux-x86_64-3.8/src/pyrfc/_pyrfc.o -Wall -O2 -fexceptions -funsigned-char -fno-strict-aliasing -Wall -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-function -Wcast-align -fPIC -pthread -minline-all-stringops -I/usr/local/webServices/llibreriaSAP/nwrfcsdk//include
    src/pyrfc/_pyrfc.cpp: In function ‘RFC_RC __pyx_f_5pyrfc_5pyrfc_metadataLookup(const SAP_UC*, RFC_ATTRIBUTES, _RFC_FUNCTION_DESC_HANDLE**)’:
    src/pyrfc/_pyrfc.cpp:17190:48: error: invalid conversion from ‘const SAP_UC*’ {aka ‘const char16_t*’} to ‘SAP_UC*’ {aka ‘char16_t*’} [-fpermissive]
    17190 |   __pyx_t_1 = __pyx_f_5pyrfc_5pyrfc_wrapString(__pyx_v_functionName, NULL); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1255, __pyx_L1_error)
          |                                                ^~~~~~~~~~~~~~~~~~~~
          |                                                |
          |                                                const SAP_UC* {aka const char16_t*}
    src/pyrfc/_pyrfc.cpp:2141:51: note:   initializing argument 1 of ‘PyObject* __pyx_f_5pyrfc_5pyrfc_wrapString(SAP_UC*, __pyx_opt_args_5pyrfc_5pyrfc_wrapString*)’
     2141 | static PyObject *__pyx_f_5pyrfc_5pyrfc_wrapString(SAP_UC *, struct __pyx_opt_args_5pyrfc_5pyrfc_wrapString *__pyx_optional_args); /*proto*/
          |                                                   ^~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k5px9zhp/pynwrfc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k5px9zhp/pynwrfc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-55xlli1_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/bruce/.local/include/python3.8/pynwrfc Check the logs for full command output.

**Comment by OlegBash599** [comment]
@bsrdjan I am also have the same issue when installin via pip install.
In case installing from wheel - I am having the issue as described in [219 ](https://github.com/SAP/PyRFC/issues/219)

**Comment by Garfius** [comment]
> @bsrdjan I am also have the same issue when installin via pip install pynwrfc.
> In case installing from wheel - I am having the issue as described in [219 ](https://github.com/SAP/PyRFC/issues/219)

Use PyRFC-2.0.6, 2.0.6 works.

**Comment by OlegBash599** [comment]
> > @bsrdjan I am also have the same issue when installin via pip install pynwrfc.
> > In case installing from wheel - I am having the issue as described in [219 ](https://github.com/SAP/PyRFC/issues/219)
> 
> Use PyRFC-2.0.6, 2.0.6 works.

Thanks for advice.
2.0.6. is not working with python 3.9.
Also we should make 2.3.0 work properly :-)

**Comment by bsrdjan** [comment]
Hi @garifus,

if you check the line 35 of [src/pyrfc/_pyrfc.cpp](https://raw.githubusercontent.com/SAP/PyRFC/2.3.0/src/pyrfc/_pyrfc.cpp), it shows:

```cpp
            [
                "SAPonDARW",
                null
            ]
```

The [2.0.6 version of the same file](https://raw.githubusercontent.com/SAP/PyRFC/2.1.0/src/pyrfc/_pyrfc.cpp) (or 2.1.0) shows:

```cpp
            [
                "SAPonLIN",
                null
            ]
```

PyRFC source code is Cython (pyx). CPP is generated by Cython compiler and compiled by target platform cpp toolchain. PyRFC CPP source on PyPI is for the platform last used in internal release test. It was Linux for 2.0.6 (2.1.0 ...) but it can be also Windows or Darwin, like in 2.3.0. 

The `pip install pynwrfc` fails when the target platform differs from this last one used in internal test. In this particular case the compilation of Darwin CPP fails on Ubuntu, as expected.

To the rescue there is "Build from source" Installation, described in [README](https://github.com/SAP/PyRFC#installation):

```shell
PYRFC_BUILD_CYTHON=yes pip install pynwrfc --no-binary :all:
``` 

It forces the installer to build CPP from pyx source on a target platform, which is actually highly (only) recommended way for PyPI binary packages like PyRFC. Cython and CPP build toolchain are however required. It could already installed on your Ubuntu and just as a reference, here are packages used for internal testing on Ubuntu: [SAP/fundamental-tools/docker/ubuntu-test.Dockerfile#L33](https://github.com/SAP/fundamental-tools/blob/main/docker/ubuntu-test.Dockerfile#L33)

Hope this helps.

**Comment by Garfius** [comment]
> Hi @garifus,
> 
> if you check the line 35 of [src/pyrfc/_pyrfc.cpp](https://raw.githubusercontent.com/SAP/PyRFC/2.3.0/src/pyrfc/_pyrfc.cpp), it shows:
> 
> ```c++
>             [
>                 "SAPonDARW",
>                 null
>             ]
> ```
> 
> The [2.0.6 version of the same file](https://raw.githubusercontent.com/SAP/PyRFC/2.1.0/src/pyrfc/_pyrfc.cpp) (or 2.1.0) shows:
> 
> ```c++
>             [
>                 "SAPonLIN",
>                 null
>             ]
> ```
> 
> PyRFC source code is Cython (pyx). CPP is generated by Cython compiler and compiled by target platform cpp toolchain. PyRFC CPP source on PyPI is for the platform last used in internal release test. It was Linux for 2.0.6 (2.1.0 ...) but it can be also Windows or Darwin, like in 2.3.0.
> 
> The `pip install pynwrfc` fails when the target platform differs from this last one used in internal test. In this particular case the compilation of Darwin CPP fails on Ubuntu, as expected.
> 
> To the rescue there is "Build from source" Installation, described in [README](https://github.com/SAP/PyRFC#installation):
> 
> ```shell
> PYRFC_BUILD_CYTHON=yes pip install pynwrfc --no-binary :all:
> ```
> 
> It forces the installer to build CPP from pyx source on a target platform, which is actually highly (only) recommended way for PyPI binary packages like PyRFC. Cython and CPP build toolchain are however required. They could already installed on your Ubuntu and just as a reference, here are packages used for internal testing on Ubuntu: [SAP/fundamental-tools/docker/ubuntu-test.Dockerfile#L33](https://github.com/SAP/fundamental-tools/blob/main/docker/ubuntu-test.Dockerfile#L33)
> 
> Hope this helps.

Yep, it helps!

Solved using:
$ export PYRFC_BUILD_CYTHON=yes
pip install pynwrfc --no-binary :all:

I may suggest a platform detection procedure during installation.

Thanks.

**Comment by bsrdjan** [comment]
Detection of Linux platforms' differences could be tricky and Python recommends [manylinux](https://github.com/pypa/manylinux) wheels here. These are easy to build but they pull up all dependencies, also SAP NWRFC SDK, into the package. SAP NWRFC SDK is exclusively distributed via SAP Support Portal and must not be (re)distributed via PyPI or other channels, which unfortunately disqualifies manylinux. Perhaps to install binary wheels for Windows, Darwin and Darwin and trigger the build from source for anything which is not Windows/Darwin ?

**Comment by bsrdjan** [comment]
Here the proposal for the default installation model change, starting with next release:

- **Windows and Darwin**: no build from source, prebuilt binaries downloaded from PyPI

- **Linux**: build from Cython source, no CPP sources included any more. Loocally installed Cython required for the installation.

Please let me know if any concerns.

**Comment by Garfius** [comment]
> Here the proposal for the default installation model change, starting with next release:
> 
> * **Windows and Darwin**: no build from source, prebuilt binaries downloaded from PyPI
> * **Linux**: build from Cython source, no CPP sources included any more. Loocally installed Cython required for the installation.
> 
> Please let me know if any concerns.

Looks like a good solution to me.

Thanks 4 the great work. 😀

**Comment by bsrdjan** [comment]
Please try 2.4.0: `pip install pyrfc` (package name changed)
