### ISSUE TITLE
Pyrfc bre-build wheel file for Python 3.9+Windows

### ISSUE THREAD

**Issue by bluckau** [SAP/PyRFC#222]
Hi, 

Is there a plan any time soon for a pre-built wheel file for pyrfc for Windows+Python 3.9?

Thanks,
Brian Luckau

**Comment by bsrdjan** [comment]
It will be available as soon NWRFC SDK PL8 is available, hopefully soon. 

The critical strings conversion bug is fixed in PL8 and I would therefore remove the workaround for it from PyRFC. That is why 3.9 still pending but should be available soon.

**Comment by bsrdjan** [comment]
Just released, try with `pip install pyrfc`
