### ISSUE TITLE
is there a function to call program through pyrfc package

### ISSUE THREAD

**Issue by nischal009** [SAP/PyRFC#223]
Is there a way i can leverage pyrfc to execute standard reports and extract data into data frame.

**Comment by bsrdjan** [comment]
Just create an RFC function module and call the ABAP report using [ABAP SUBMIT statement](https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abapsubmit.htm).

There are also [examples on SCN](https://www.google.com/search?q=sap+scn+help+submit+report).
