### ISSUE TITLE
calling CDS view through pyrfc

### ISSUE THREAD

**Issue by nischal009** [SAP/PyRFC#224]
can we use pyrfc to pull CDS views data

**Comment by bsrdjan** [comment]
Just create a RFC enabled function module and call the CDS view inside:

[SELECT, CDS View with Input Parameters (SAP Help)](https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenselect_cds_para_abexa.htm)

**Comment by nischal009** [comment]
Thanks for the information . Will try update .
