### ISSUE TITLE
Pip support

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#23]
Wonder why PyRFC is packaged as `.egg`. Why not use `.whl` so that one can use pip for installation?

**Comment by Tset-Noitamotua** [comment]
Do you plan to distribute PyRFC through [PyPI](https://pypi.python.org/pypi)?

**Comment by bsrdjan** [comment]
According to Python Packaging User Guide [Tool Recommendations](https://python-packaging-user-guide.readthedocs.io/current/#packaging-tool-recommendations) and [Publishing Binary Extensions](https://packaging.python.org/extensions/#publishing-binary-extensions), publishing pre-compiled extension on PyPI is currently not supported for Linux targets, only for OSX and Windows. As we anyway plan to automate cross-platform builds and testing, something like described [here](https://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/), still need the time and efforts to investigate and automate cross-platform publishing.

**Comment by Tset-Noitamotua** [comment]
Are you talking about setting up
> Continuous Integration (CI) tools like TravisCI (build for Linux and OSX) and AppVeyor (build for Windows platforms) to automatically generate, package, publish and have binary packages available each time a new version of the module is released

?

I would like to help if I can. Do I need something else than I already have (sap nw lib binaries, pyrfc code) ?

**Comment by bsrdjan** [comment]
Please see #69, no capacity for the time being.

**Comment by bsrdjan** [comment]
Finally done https://pypi.org/project/pynwrfc/
