### ISSUE TITLE
No module named 'pyrfc' - Jupyter

### ISSUE THREAD

**Issue by jignesh-bhanushali** [SAP/PyRFC#231]
**Describe the bug**
Pyrfc works directly on command prompt python, but does not works with Jupyter.

**To Reproduce**
Install Python.
Install nwrfcsdk 
Install Cython 
Set all env parameters as well.

**Screenshots**
Local Command Prompt works
![image](https://user-images.githubusercontent.com/54689567/120559738-658aee00-c3b6-11eb-814a-5034b127b95e.png)

Jupyter fails on same machine.
![image](https://user-images.githubusercontent.com/54689567/120559799-88b59d80-c3b6-11eb-9d4f-a75066dfdd3b.png)

**Environment**
 - OS: Windows
 - Running in docker? No
 - PyRFC version - 2.0.4

**Additional context**

**Comment by bsrdjan** [comment]
Could not reproduce. If you run `help('modules')` in Jupyter console, is `pyrfc` listed in output?

Did you try to uninstall and install `pyrfc` ?

**Comment by jignesh-bhanushali** [comment]
I dont see pyrfc in modules.  I tried already reinstalling.
![image](https://user-images.githubusercontent.com/54689567/120727306-0816a000-c48f-11eb-96b4-f733bcee2b82.png)

**Comment by bsrdjan** [comment]
Can you check if environment variable SAPNWRFC_HOME set when running in Jupyter:

```python
import os
print(os.environ['SAPNWRFC_HOME'])
```

It should point to SAP NWRFC SDK home folder, containing the `lib` subdirectory with SDK DLLs.

Does the`import pyrfc` work?

**Comment by bsrdjan** [comment]
I am not very familiar with Jupyter and how Python packages shall be installed in Jupyter environment. It could be the PyRFC is installed at system level but Jupyter is looking for packages elsewhere.

This might eventually help:

- https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

- https://stackoverflow.com/questions/38368318/installing-a-pip-package-from-within-a-jupyter-notebook-not-working

**Comment by jignesh-bhanushali** [comment]
I checked the below. I can see the HOME variable. 
![image](https://user-images.githubusercontent.com/54689567/120840293-e49b3600-c51e-11eb-8d2a-a0d50cb390fb.png)
I will try the other installation options within Jupyter to see if it solves the issue.

**Comment by bsrdjan** [comment]
The `SAPNWRFC_HOME` is required on Windows, to find the SDK:

https://github.com/SAP/PyRFC/blob/main/src/pyrfc/__init__.py#L8

**Comment by jignesh-bhanushali** [comment]
I reinstalled python and trying to install the pyrfc jar file. I am getting an error even if the file is there in the same location.

FINDSTR: Cannot open c:\nwrfcdsk\lib\sapnwrfc.dll

**Comment by bsrdjan** [comment]
Please reopen if needed. You could also copy the RFC SDK to Windows system directory, C:\Windows\system32 for 64bit processes and C:\Windows\SysWoW64 for 32bit processes. See https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order
