### ISSUE TITLE
 src/pyrfc/_pyrfc.cpp(754): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory

### ISSUE THREAD

**Issue by mohammedabdulb** [SAP/PyRFC#237]
```shell
C:\Users\abdul>pip install C:\Users\abdul\Downloads\PyRFC-2.0.4.tar.gz
Processing c:\users\abdul\downloads\pyrfc-2.0.4.tar.gz
Requirement already satisfied: setuptools in c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages (from pynwrfc==2.0.4) (41.2.0)
Building wheels for collected packages: pynwrfc
  Building wheel for pynwrfc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abdul\AppData\Local\Temp\pip-wheel-yph6a07t' --python-tag cp38
       cwd: C:\Users\abdul\AppData\Local\Temp\pip-req-build-5vu1koxi\
  Complete output (19 lines):
  FINDSTR: Cannot open c:\nwrfcsdk;\lib\sapnwrfc.dll
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyrfc
  copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.8\pyrfc
  copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.8\pyrfc
  running build_ext
  building 'pyrfc.pyrfc' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\pyrfc
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\abdul\appdata\local\programs\python\python38\include -Ic:\users\abdul\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj -Ic:\nwrfcsdk;\include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -GL -O2 -Oy- /we4552 /we4700 /we4789
  _pyrfc.cpp
  src/pyrfc/_pyrfc.cpp(754): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pynwrfc
  Running setup.py clean for pynwrfc
Failed to build pynwrfc
Installing collected packages: pynwrfc
  Found existing installation: pynwrfc 2.4.0
    Uninstalling pynwrfc-2.4.0:
      Successfully uninstalled pynwrfc-2.4.0
  Running setup.py install for pynwrfc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abdul\AppData\Local\Temp\pip-record-vipplkl_\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\abdul\AppData\Local\Temp\pip-req-build-5vu1koxi\
    Complete output (19 lines):
    FINDSTR: Cannot open c:\nwrfcsdk;\lib\sapnwrfc.dll
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.8\pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\pyrfc
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\abdul\appdata\local\programs\python\python38\include -Ic:\users\abdul\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj -Ic:\nwrfcsdk;\include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -GL -O2 -Oy- /we4552 /we4700 /we4789
    _pyrfc.cpp
    src/pyrfc/_pyrfc.cpp(754): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of pynwrfc
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pynwrfc-2.4.0.dist-info\
   from C:\Users\abdul\AppData\Local\Programs\Python\Python38\Lib\site-packages\~ynwrfc-2.4.0.dist-info
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\__init__.py
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\__init__.py
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\__pycache__\
   from C:\Users\abdul\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyrfc\~_pycache__
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\_exception.py
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\_exception.py
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\pyrfc.cp38-win_amd64.pdb
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\pyrfc.cp38-win_amd64.pdb
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\pyrfc.cp38-win_amd64.pyd
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\pyrfc.cp38-win_amd64.pyd
ERROR: Command errored out with exit status 1: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abdul\AppData\Local\Temp\pip-record-vipplkl_\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\abdul>
```

**Comment by mohammedabdulb** [comment]
@bsrdjan :- Please look into this issue

**Comment by mohammedabdulb** [comment]
Same thing with full lines
C:\Users\abdul>pip install C:\Users\abdul\Downloads\PyRFC-2.0.4.tar.gz
Processing c:\users\abdul\downloads\pyrfc-2.0.4.tar.gz
Requirement already satisfied: setuptools in c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages (from pynwrfc==2.0.4) (41.2.0)
Building wheels for collected packages: pynwrfc
  Building wheel for pynwrfc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abdul\AppData\Local\Temp\pip-wheel-yph6a07t' --python-tag cp38
       cwd: C:\Users\abdul\AppData\Local\Temp\pip-req-build-5vu1koxi\
  Complete output (19 lines):
  FINDSTR: Cannot open c:\nwrfcsdk;\lib\sapnwrfc.dll
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyrfc
  copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.8\pyrfc
  copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.8\pyrfc
  running build_ext
  building 'pyrfc.pyrfc' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\pyrfc
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\abdul\appdata\local\programs\python\python38\include -Ic:\users\abdul\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj -Ic:\nwrfcsdk;\include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -GL -O2 -Oy- /we4552 /we4700 /we4789
  _pyrfc.cpp
  src/pyrfc/_pyrfc.cpp(754): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pynwrfc
  Running setup.py clean for pynwrfc
Failed to build pynwrfc
Installing collected packages: pynwrfc
  Found existing installation: pynwrfc 2.4.0
    Uninstalling pynwrfc-2.4.0:
      Successfully uninstalled pynwrfc-2.4.0
  Running setup.py install for pynwrfc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abdul\AppData\Local\Temp\pip-record-vipplkl_\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\abdul\AppData\Local\Temp\pip-req-build-5vu1koxi\
    Complete output (19 lines):
    FINDSTR: Cannot open c:\nwrfcsdk;\lib\sapnwrfc.dll
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.8\pyrfc
    copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.8\pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\pyrfc
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\abdul\appdata\local\programs\python\python38\include -Ic:\users\abdul\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/pyrfc/_pyrfc.obj -Ic:\nwrfcsdk;\include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include -Ic:\users\abdul\appdata\local\programs\python\python38\lib\inspect.py\Include\PC -EHs -Gy -J -MD -nologo -W3 -Z7 -GL -O2 -Oy- /we4552 /we4700 /we4789
    _pyrfc.cpp
    src/pyrfc/_pyrfc.cpp(754): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of pynwrfc
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pynwrfc-2.4.0.dist-info\
   from C:\Users\abdul\AppData\Local\Programs\Python\Python38\Lib\site-packages\~ynwrfc-2.4.0.dist-info
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\__init__.py
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\__init__.py
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\__pycache__\
   from C:\Users\abdul\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyrfc\~_pycache__
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\_exception.py
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\_exception.py
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\pyrfc.cp38-win_amd64.pdb
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\pyrfc.cp38-win_amd64.pdb
  Moving to c:\users\abdul\appdata\local\programs\python\python38\lib\site-packages\pyrfc\pyrfc.cp38-win_amd64.pyd
   from C:\Users\abdul\AppData\Local\Temp\pip-uninstall-rpb5o5az\pyrfc.cp38-win_amd64.pyd
ERROR: Command errored out with exit status 1: 'c:\users\abdul\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"'; __file__='"'"'C:\\Users\\abdul\\AppData\\Local\\Temp\\pip-req-build-5vu1koxi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abdul\AppData\Local\Temp\pip-record-vipplkl_\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\abdul>

**Comment by bsrdjan** [comment]
Check the SAPNWRFC_HOME environment variable. It should point to the root folder of SAP NWRFC SDK. It is the one below the `include` folder, in which the file `sapnwrfc.h` is located.
