### ISSUE TITLE
PyRFC NWRFCSDK - ImportError: cannot import name Iterable

### ISSUE THREAD

**Issue by ankushmsingh** [SAP/PyRFC#250]
**Describe the bug**
PyRfc is working fine on windows 10 , but when I try to install nwrfcsdk on windows server 2016, code is giving error

**Screenshots**
    from .pyrfc import (
  File "src/pyrfc/_pyrfc.pyx", line 10, in init pyrfc.pyrfc
ImportError: cannot import name Iterable

**Environment**
 - OS: Windows Server 2016
 - Running in VM
 - PyRFC pyrfc-2.4.2.
 - Python Version 310

**Additional context**

**Comment by ankushmsingh** [comment]
this is resolved . I copied the python 3.9 files to windows server 2016. Changed the environmental variables to python39 folder and it worked

**Comment by jraber** [comment]
This should be solved with python 310 by commit e6622d5f2c5df93901690f7cb7790cb06e193505

**Comment by bsrdjan** [comment]
Solved by e6622d5 in release 2.5.0
