### ISSUE TITLE
Cannot Install PyRFC

### ISSUE THREAD

**Issue by the-master-student** [SAP/PyRFC#252]
Hi,

I have been trying to install PyRFC however it keeps throwing many errors. 
I tried to follow steps described at this issue https://github.com/SAP/PyRFC/issues/189 but no progress.

Following Information could be relevant:
OS: MacOS Monterey 12.01.1
Python Version: 3.10.0
SAP NetWeaver RFC SDK 7.50 installed and SAPNWRFC_HOME variable set correctly.

Many thanks in advance

**Comment by bsrdjan** [comment]
What kind of errors occur? Please share the full console log, starting with the installation command.

**Comment by the-master-student** [comment]
Error Log with an error that SAPNWRFC_HOME variable was not specified
![Screenshot 2021-11-29 at 14 40 39 (2)](https://user-images.githubusercontent.com/95228277/143878668-09d6e6a8-e966-4019-aebb-fd0b3ece58b5.png)
)

SAPNWRFC_HOME variable  specified
![Screenshot 2021-11-29 at 14 43 48](https://user-images.githubusercontent.com/95228277/143878684-12aa181b-9794-414a-8a0f-0cc790cec05f.png)

**Comment by bsrdjan** [comment]
The package is called `pyrfc` not `pynwrfc`, try:

```shell
pip install pyrfc
```

**Comment by bsrdjan** [comment]
Did you download and installed SAP NWRFC SDK: https://github.com/SAP/PyRFC#all-platforms ?

To verify, check if `rfcexec` output looks like below. The error complaining about parameters indicates the SAP NWRFC SDK installation is correct:

```shell
cd $SAPNWRFC_HOME/bin
./rfcexec
Error:
	Please start the program in the following way:
	rfcexec -t -a <program ID> -g <gateway host> -x <gateway service>
		-f <file with list of allowed commands> -s <allowed Sys ID>
The options "-t" (trace), "-f" and "-s" are optional.

Below further optional parameters are listed. You can find their
documentation in sapnwrfc.ini:
-on_cce <0, 1, 2> (On Character Conversion Error)
-cfit (Conversion Fault Indicator Token - the substitute symbol used if on_cce=2)
-keepalive (Sets the keepalive option. Default is 0.)
-delta <0, 1> (default 1, i.e. use delta-manager)
-no_compression (table compression, default is 0, i.e. compression is on)
```

**Comment by the-master-student** [comment]
The exact same output is reproduced

![Screenshot 2021-11-29 at 15 18 43](https://user-images.githubusercontent.com/95228277/143884315-c11a8386-2d74-4e43-b89b-fad19384f9b6.png)

**Comment by bsrdjan** [comment]
Could you please try following

1. Clean-up site packages

```shell
pip uninstall pynwrfc
pip uninstall pyrfc
```

Ensure neither `pyrfc` not `pynwrfc` is present in site packages:
<img width="634" alt="Screenshot 2021-11-29 at 15 52 44" src="https://user-images.githubusercontent.com/1697847/143889916-6cb26a27-7167-439c-8d6a-7bf728fb4bc4.png">

2. pip install pyrfc and post the log

3. Repeat the `from pyrfc import Connection` test. 

If it does not work:

1. Share the log
2. Try if `from pyrfc import *` works?
3. Let me know SAP NWRFC SDK version:

```shell
echo `strings $SAPNWRFC_HOME/lib/libsapnwrfc.dylib | grep "Patch Level"`
```

**Comment by the-master-student** [comment]
![Screenshot 2021-11-29 at 16 02 09](https://user-images.githubusercontent.com/95228277/143892042-93b42e1d-0a11-450c-99d7-402e364d7ad6.png)

**Comment by bsrdjan** [comment]
hm, no idea, could not reproduce on my macbook 12.0.1 and the sam RFC SDK.

Which Python are you using, how it is installed ?

I am running 3.10.0 installed by pyenv.

**Comment by the-master-student** [comment]
I am also running python 3.10.0 downloaded via the Python download site.

**Comment by bsrdjan** [comment]
and installed following which installation procedure?

**Comment by the-master-student** [comment]
Still the import was not successful.

<img width="1463" alt="Screenshot 2021-12-01 at 16 14 26" src="https://user-images.githubusercontent.com/95228277/144263420-a54ce62d-ac51-4b2f-9878-7bbb72748382.png">

**Comment by bsrdjan** [comment]
Where the SAP NW RFC SDK is downloaded from?

**Comment by the-master-student** [comment]
It was downloaded from the SAP Support Portal

<img width="1249" alt="Screenshot 2021-12-02 at 08 04 13" src="https://user-images.githubusercontent.com/95228277/144374100-1597912a-9f31-4f21-ab88-ac668fc7f5bb.png">

**Comment by bsrdjan** [comment]
Exactly the same Darwin, pyenv Python and pyrfc on my Macbook and can't reproduce.

Could you please try if it works with pyenv python 3.9.8 ?

Found also this SO post but does not seem to be relevant: https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

**Comment by bsrdjan** [comment]
Could you please try build from source installation?

It requires pip install cython and wheel:

```shell
pip uninstall pyrfc
git clone https://github.com/SAP/PyRFC/ && cd PyRFC
python setup.py bdist_wheel
pip install dist/pyrfc-2.5.0-cp310-cp310-macosx_11_0_x86_64.whl
```

**Comment by the-master-student** [comment]
The problem is solved. The terminal on Apple silicon Macs is run on Apple processors. For pyrfc to successfully run the terminal/ app should be run on an intel emulator. 
Thank you for your time and effort.

**Comment by bsrdjan** [comment]
Glad to hear it is solved and thank you for the info on troubleshooting.
