### ISSUE TITLE
Can not install pyrfc

### ISSUE THREAD

**Issue by mahmed1995** [SAP/PyRFC#253]
I am trying to install pyrfc in a docker with ubuntu image running on mac. I can not install directly with pip or compiling from source. Both methods end up with the same error. Thank you for the help.

**Environment**
 - OS: Darwin Monterey 12.0.1
 - Python 3.10
 - Yes running in Docker

Path for SAPNWRFC_HOME is set properly and ldconfig -p | grep sap gives correct output. The architecture is aarch64. 

Main error on console: gcc: error: unrecognized command-line option ‘-minline-all-stringops’

<img width="1435" alt="Screenshot 2021-12-02 at 15 05 07" src="https://user-images.githubusercontent.com/20825201/144438235-d3e4c25f-e7f2-429e-b359-4b2e90b6f2fb.png">

**Comment by bsrdjan** [comment]
Hard to guess what goes wrong without looking into Dockerfile source, but here one working [ubuntu based docker](https://github.com/SAP/fundamental-tools/blob/main/docker/ubuntu-qa.Dockerfile) you could try or use a reference.

**Comment by Ryanb58** [comment]
@mahmed1995 Were you able to get this working?

**Comment by bsrdjan** [comment]
Please re-open if needed

**Comment by fgandolfo** [comment]
Hi, did anyone come up with a solution? I'm facing the same issue.

**Comment by bsrdjan** [comment]
@fgandolfo, recommended solution in comment above: https://github.com/SAP/PyRFC/issues/253#issuecomment-985438953

Adding a `--platform=linux/amd64` option to `docker run` command should be enough. More info: https://docs.docker.com/build/building/multi-platform/
