### ISSUE TITLE
PyRFC Server error

### ISSUE THREAD

**Issue by Mx1014** [SAP/PyRFC#255]
I’m used the PyRFC ，PYRFC, when trying to run the PYRFC server example，the serve has been start ,but i can't register to SAP gateway ,and when use the rfcexec to test,the server will be error

Describe the steps to reproduce the behavior, including test script.
1.start the server 
2.test to connect 
./rfcexec -t -a SAP_TO_IWM_NL -g 10.50.201.118 -x sapgw03

3.serve error 
![image](https://user-images.githubusercontent.com/19869645/146772011-4d21b689-6b71-46a9-8d80-67bd177a5cbb.png)

![image](https://user-images.githubusercontent.com/19869645/146772312-0c12d134-15fb-408d-814d-065f94324a9b.png)

**Environment**
 - OS: Linux Centos 7.9
 - PyRFC version 2.5.0 
 - Python 3.7.12
 - 

**Additional context**

The code 
![image](https://user-images.githubusercontent.com/19869645/146772755-1010d7d1-9f26-41f7-9531-97b13df29233.png)

![image](https://user-images.githubusercontent.com/19869645/146772492-30f55f8a-5033-4e6c-8ffd-0af231370bfa.png)

**Comment by Ryanb58** [comment]
Where you able to connect via the PyRFC library? I've never heard of **rfcexec** before.

**Comment by Mx1014** [comment]
Provided by a sap technical support, he uses this method to test whether the service is available

**Comment by bsrdjan** [comment]
Please check this guide and try to reproduce steps

**Comment by bsrdjan** [comment]
Please re-open if needed
