### ISSUE TITLE
Error in SNC and X509

### ISSUE THREAD

**Issue by calvarezl-cl** [SAP/PyRFC#266]
Hello:

We are trying to use PyRFC for connecting to SAP using SNC with X509 certificate, but we aren´t able to do, We were able to connect to SAP using user/password or SNC with PSE.

We have defined following environment variables in ec2 server: SNC_LIB, LD_LIBRARY, SECUDIR and PATH. Params that we are passing to connection are de following: SNC_PARTNERNAME, NAME, ASHOST, CLIENT, LANG, SYSNR, SAPROUTER, TLS_CLIENT_CERTIFICATE_LOGON, X509CERT, SNC_LIB y TLS_CLIENT_PSE

Error in connection is:
Traceback (most recent call last):
  File "Conexionsnc.py", line 41, in <module>
    X509CERT=X509CERT,SNC_LIB=SNC_LIB,TLS_CLIENT_PSE=TLS_CLIENT_PSE)
  File "src/pyrfc/_pyrfc.pyx", line 264, in pyrfc.pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 310, in pyrfc.pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 353, in pyrfc.pyrfc.Connection._error
pyrfc._exception.LogonError: RFC_LOGON_FAILURE (rc=2): key=RFC_LOGON_FAILURE, message=El nombre SNC del sistema contraparte no existe en la ACL de sistema [MSG: class=, type=, number=, v1-4:=;;;]

Best regards,
Christian

**Comment by bsrdjan** [comment]
The SNC connection requires more configuration, like set-up the trust between ABAP system and system on which Python/PyRFC is running and configuring x509 to ABAP user id mapping rules in ABAP system. You can search SAP OSS notes and SCN blogs for "SNC RFC", like: https://blogs.sap.com/2021/08/04/setting-up-sap-secure-network-communications-snc-on-s4hana-and-integration-with-itx-ibm-transformation-extender-tool/, of for "CERTRULE" transaction: https://blogs.sap.com/2018/11/07/principal-propagation-setup-between-cloud-platform-and-on-premise-backend-system-part-2/

**Comment by bsrdjan** [comment]
More support on this topic goes beyond standard PyRFC oss support and can be provided as a commercial consulting service. Please re-open if needed.
