### ISSUE TITLE
(🐞) On pypi, pynwrfc 2.4.0 is missing an sdist

### ISSUE THREAD

**Issue by KotlinIsland** [SAP/PyRFC#269]
And there are no linux wheels.

**Comment by bsrdjan** [comment]
Linux wheels are attached to GH releases:
https://github.com/SAP/PyRFC/releases

**Comment by KotlinIsland** [comment]
Thanks, could you add the wheels to the 2.4.0 release on pypi? I don't know if you can get pip to install from a GH release

**Comment by bsrdjan** [comment]
Portable Linux wheels are not supported, as described in README section "Supported Platforms" and PEP-513: https://www.python.org/dev/peps/pep-0513/

The installation on Linux is described in README section "Download and installation"

**Comment by KotlinIsland** [comment]
Oh, it moved to a new name, and the current releases have sdists, I guess that resolves my issue.

You could '[yank](https://pypi.org/help/#yanked)' the `pynwrfc` release with a message pointing to the new one. Here is a package that has been yanked:

```
> pip install gitlab==1.0.2
Collecting gitlab==1.0.2
  Using cached gitlab-1.0.2-py3-none-any.whl
WARNING: The candidate selected for download or install is a yanked version: 'gitlab' candidate (version 1.0.2 at https://files.pythonhosted.org/packages/ad/c5/91cb054390cafd6739eab83dfb5d739b699f10b4ff139602f98345e787ef/gitlab-1.0.
2.tar.gz#sha256=28425cd714fd1e4bc6b275acade5367bea869be85ac23ca5bd984375e742d172 (from https://pypi.org/simple/gitlab/))
Reason for being yanked: A more complete GitLab API wrapper replaces this package. See: https://github.com/python-gitlab/python-gitlab
Installing collected packages: gitlab
Successfully installed gitlab-1.0.2
```
