### ISSUE TITLE
AttributeError: 'str' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#27]
I have below script which is based on `clientStfcStructure.py` from examples folder:

``` python
import os

# Put SAP NW RFC Library on PATH
SAPNWRFC_PATH = os.path.abspath('dependencies/32bit/SAP_NW_RFC_32/lib')
os.environ['PATH'] = SAPNWRFC_PATH + ";" + os.environ['PATH']


from pyrfc import Connection
from pprint import pprint
from configparser import ConfigParser


header = {
    'DOC_TYPE': 'TA',
    'SALES_ORG': '0500',
    'DISTR_CHAN':'01',
    'DIVISION': '01',
    'PURCH_NO_C': 'ABC12345'
}

partners = {
    'PARTN_NUMB': 512345500,
    'NAME': 'Otto GmbH'
}

def main():
    config = ConfigParser()
    config.read('sapnwrfc.cfg')
    params_connection = config._sections['connection']

    conn = Connection(**params_connection)
    result = conn.call('BAPI_SALESORDER_CREATEFROMDAT2', ORDER_HEADER_IN=header, ORDER_PARTNERS=partners)
    pprint(result2)

if __name__ == '__main__':
    main()
```

Then I run this script (with Python 2.7 32bit) I get the error

```
AttributeError: 'str' object has no attribute 'iteritems'
```

If I pass only one keyword-argument to BAPI call like this

``` python
result = conn.call('BAPI_SALESORDER_CREATEFROMDAT2', ORDER_HEADER_IN=header)
```

then it works and I get some answer from BAPI_SALESORDER_CREATEFROMDAT2. Obviously more parameters have to be passed, though because  BAPI states

```
...
u'RETURN': [{u'FIELD': u'',
              u'ID': u'VP',
              u'LOG_MSG_NO': u'000000',
              u'LOG_NO': u'',
              u'MESSAGE': u'Bitte Auftraggeber oder Warenempf\xe4nger eingeben.',
...
```

Please help with that one. I have spend hours on it but just don't have any more ideas how to further debugg it.

**Comment by Tset-Noitamotua** [comment]
Oh damn! I definitely should take a break more often and read the [documentation ](http://sap.github.io/PyRFC/client.html#examples) more carefully :-/

> There are some points worth mentioning.
... For more complex types, the **value is a dictionary (for structures)** or a **list of dictionaries (for tables)**."

It works if I pass `ORDER_PARTNERS` as a list of dictionaries: `ORDER_PARTNERS=partners`.

**Comment by Tset-Noitamotua** [comment]
![image](https://cloud.githubusercontent.com/assets/5635462/19760397/e0720a2e-9c31-11e6-9c4f-abb19f8689f2.png)

**Comment by Tset-Noitamotua** [comment]
still a short question remains. In screenshot below one see `ORDER_PARTNERS STRUCTURE BAPIPARNR`. Does that mean that ORDER_PARTNERS is a table which belongs to the structure named BAPIPARNR or is ORDER_PARTNERS a structure itself?

![image](https://cloud.githubusercontent.com/assets/5635462/19760576/a2e121d0-9c32-11e6-859a-78c3989083b8.png)

**Comment by bsrdjan** [comment]
It is a table, with rows of the BAPIPARNR structure. You can double click on BAPIPARNR in editor to open the  structure. If you are new to ABAP, you may check [ABAP Dictionary @ SAP Help](https://help.sap.com/saphelp_nw73ehp1/helpdata/en/cf/21ea43446011d189700000e8322d00/content.htm?frameset=/en/cf/21ea0b446011d189700000e8322d00/frameset.htm&current_toc=/en/4f/991f82446d11d189700000e8322d00/plain.htm&node_id=3&show_children=true#jump3)

**Comment by Tset-Noitamotua** [comment]
Thank you. Slowly but deliberately I'm getting the pieces of that puzzle together.
