### ISSUE TITLE
RFC_COMMUNICATION_FAILURE

### ISSUE THREAD

**Issue by Joselguti** [SAP/PyRFC#273]
Hello,

I am new to using PyRFC and having some troubles in the connection.

I am currently trying to replicate a connection I use in another framework and is working, said data is the following:
AppServer = "159.x.x.220"
Clientnumber = "120"
SystemID= "W4D"
InstanceNumber = "01"
Username and Password.

For this I'm using the same information

```
from pyrfc import Connection
conn_user = 'x'
conn_password = 'x'
conn_ashost = '159.x.x.220'
conn_sysnr = 'W4D'
conn_client = '120'
conn = Connection(user=conn_user, passwd=conn_password, ashost=conn_ashost, sysnr=conn_sysnr, client=conn_client)
```

However I am recieving the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyrfc/_pyrfc.pyx", line 264, in pyrfc.pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 310, in pyrfc.pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 353, in pyrfc.pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       partner '159.x.x.220:3300' not reached
TIME        Mon Apr 18 17:51:37 2022
RELEASE     753
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      D:/depot/bas/753_REL/src/base/ni/nixxi.cpp
LINE        3454
DETAIL      NiPConnect2: 159.x.x.220:3300
SYSTEM CALL connect
ERRNO       10061
ERRNO TEXT  WSAECONNREFUSED: Connection refused
COUNTER     10
 [MSG: class=, type=, number=, v1-4:=;;;]
```

What do you think could be the error?

Thanks in advance,

**Comment by IT-HONGREAT** [comment]
@Joselguti 
Hi! 
I'm experiencing the same error, can you tell me how you solved it?

**Comment by Joselguti** [comment]
@IT-HONGREAT 

Hey! 
This was a long time ago, but the reasons for not being able to reach a client can be the following:
-The client has some sort of firewall protection and you IP has to be whitelisted
-You need to include the saprouter = (Whatever IP the SAPROUTER is)
