### ISSUE TITLE
Pyinstaller with PyRFC "Did not find config file sapnwrfc.ini"

### ISSUE THREAD

**Issue by the-master-student** [SAP/PyRFC#275]
Hello,

I created a program with the PyRFC package that prompts user with login GUI where the data required to establish a connection is requested (including SystemID, client, user, password and instance number). However when I try to create an executable out of the python program via Pyinstaller, I get the error that the config file sapnwrfc.in could not be found. The error is raised on Linux and Windows, however not in Mac.

**Environment 1**
 - OS: Windows 10
 - PyRFC version: pyrfc-2.5.0-cp38-cp38-win_amd64.whl

**Environment 2**
 - OS: Linux 5.4.0-42-generic 64bit
 - PyRFC version: pyrfc-2.5.0-cp38-cp38-linux_x86_64.whl
 
I would very much appreciate the help here. The program runs but however when an executable is created via Pyinstaller it fails because the "sapnwrfc.ini" couldn't be located.

Thank you so much in advance.

**Comment by bsrdjan** [comment]
The installer is probably searching for `sapnwrfc.ini` at different location and the file is not there? 

The SAP NWRFC SDK library looks for `sapnwrfc.ini` at full path set in `RFC_INI` env variable. If the variable not set, it will search the current working directory of Python script (should be `os.getcwd()`).

Python application (PyRFC) can also set the different directory (not the full path) to search for `sapnwrfc.ini`file, using  `set_ini_file_directory()` method, like:

```python
from pyrfc import set_ini_file_directory
set_ini_file_directory("/home/user/config")
```

I would first check if RFC_INI variable is set. If not set, add the console output of current working directory to your script and to installer, to check where the `sapnwrfc.ini` is expected to be found and check if the file is really there and if read permissions are granted.

Some more info are [SAP Help](https://help.sap.com/doc/saphelp_nw73ehp1/7.31.19/en-US/48/ce50e418d3424be10000000a421937/content.htm?no_cache=true) and in [SAP NWRFC SDK Programming Guide](https://support.sap.com/content/dam/support/en_us/library/ssp/products/connectors/nwrfcsdk/NW_RFC_750_ProgrammingGuide.pdf): 

> Where does the NW RFC library look for the sapnwrfc.ini file? The default location is the
> current working directory (CWD) of the current process. But the application can change this –
> for example, during start-up – via the API RfcSetIniPath(). This automatically loads the
> .ini file into memory. Furthermore, the program can also trigger a reload of the .ini file into
> memory by calling the API RfcReloadIniFile(), if it got modified during the runtime of the
> application.
