### ISSUE TITLE
This cannot be connected

### ISSUE THREAD

**Issue by zhengxinghua1101** [SAP/PyRFC#276]
![image](https://user-images.githubusercontent.com/70559590/164392858-1448bcf3-e134-437c-a58b-d98b6510dca3.png)

This cannot be connected．Can you have a look? Or provide a　Ｄｏｍｅ

**Comment by bsrdjan** [comment]
The context is missing. Reopen with following info provided: https://github.com/SAP/PyRFC/issues/new?assignees=&labels=&template=bug_report.md&title=
