### ISSUE TITLE
Unable to install PyRFC and include sapnwrfc.h on Docker 

### ISSUE THREAD

**Issue by bp-brendan-quinn** [SAP/PyRFC#279]
**Describe the bug**
PyRFC is unable to detect SDK files on Docker

**To Reproduce**
Describe the steps to reproduce the behavior, including test script.
```
FROM python:3.8-slim-buster

WORKDIR /usr/src/app
COPY scripts/entrypoint.py ./
COPY ./scripts/nwrfcsdk/* /usr/local/sap/nwrfcsdk/

ENV SAPNWRFC_HOME = /usr/local/sap/nwrfcsdk/
ENV NWRFCSDK_INCLUDE = /usr/local/sap/nwrfcsdk/include/
ENV NWRFCSDK_LIBS = /usr/local/sap/nwrfcsdk/lib/

WORKDIR /usr/sap
COPY . /usr/sap
WORKDIR /usr/local/sap/nwrfcsdk/
ENV PATH="${PATH}:/usr/sap/app/nwrfcsdk/lib"

RUN pip install pandas
RUN pip install cython
RUN pip install Cmake
RUN pip install pyarrow
RUN pip install sphinx
RUN pip install ipython
RUN pip install pytest
RUN pip install wheel
RUN pip install pyrfc
```

**Environment**
 - Debian Linux in Docker
 - PyRFC version: 2.02

**Comment by bp-brendan-quinn** [comment]
![Capture](https://user-images.githubusercontent.com/95434518/180839551-492f764c-b51d-492f-9090-aeaad92f27db.PNG)

**Comment by bsrdjan** [comment]
Environment path is not enough to register shared libraries on Linux. Please check

- installation documentation http://sap.github.io/PyRFC/install.html#sap-nw-rfc-sdk-installation
- docker container examples: https://github.com/SAP/fundamental-tools/tree/main/docker

**Comment by bsrdjan** [comment]
Please re-open if needed
