### ISSUE TITLE
Installation error - cannot convert argument to 'RFC_SERVER_FUNCTION'

### ISSUE THREAD

**Issue by Aj-Revelino** [SAP/PyRFC#280]
Issue is the same as https://github.com/SAP/PyRFC/issues/242

> src/pyrfc/_pyrfc.cpp(21150): error C2664: 'RFC_RC RfcInstallGenericServerFunction(RFC_SERVER_FUNCTION,RFC_FUNC_DESC_CALLBACK,RFC_ERROR_INFO *)': cannot convert argument 1 from 'RFC_RC (__cdecl *)(RFC_CONNECTION_HANDLE,RFC_FUNCTION_HANDLE,RFC_ERROR_INFO *)' to 'RFC_SERVER_FUNCTION'
>       src/pyrfc/_pyrfc.cpp(21150): note: None of the functions with this name in scope match the target type
>       src/pyrfc/_pyrfc.cpp(29687): warning C4018: '<': signed/unsigned mismatch
>       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit code 2

Python version - 3.8.2
Pyrfc version -  pyrfc-2.5.0
OS : Windows 2016 Datacenter (64 Bit)
Netweaver RFC SDK - Downloaded the latest version (64 bit) Patch level 10; NW750pip

All prerequisites listed in https://github.com/SAP/PyRFC#windows are met:
- Installed Visual C++ Redistributable Package for Visual Studio 2013 (64 bit)
- Installed Microsoft C++ build tools Version 14.0. Activated the build tools from Modify -> individual components -> MSVC v140 -VS 2015 C++ build tools (v14.16)

I tried to clone the repository and ran `python setup.py bdist_wheel` but I get the same error.

**Comment by bsrdjan** [comment]
Could you please post the full log after `python setup.py bdist_wheel`

**Comment by Aj-Revelino** [comment]
Apologies for the delay. I downloaded the zip from github and ran the setup.py. pls see the logs below

F:\PyRFC-main\PyRFC-main> python setup.py bdist_wheel
F:\anaconda3\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.9
creating build\lib.win-amd64-3.9\pyrfc
copying src\pyrfc\_exception.py -> build\lib.win-amd64-3.9\pyrfc
copying src\pyrfc\__init__.py -> build\lib.win-amd64-3.9\pyrfc
running build_ext
skipping 'src/pyrfc\_pyrfc.cpp' Cython extension (up-to-date)
building 'pyrfc.pyrfc' extension
creating build\temp.win-amd64-3.9
creating build\temp.win-amd64-3.9\Release
creating build\temp.win-amd64-3.9\Release\src
creating build\temp.win-amd64-3.9\Release\src\pyrfc
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -IF:\anaconda3\include -IF:\anaconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc/pyrfc\_pyrfc.cpp /Fobuild\temp.win-amd64-3.9\Release\src/pyrfc\_pyrfc.obj -IF:\nwrfc750\nwrfcsdk\include -IF:\anaconda3\lib\inspect.py\Include -IF:\anaconda3\lib\inspect.py\Include\PC /EHs /Gy /J /MD /nologo /W3 /Z7 /GL /O2 /Oy- /we4552 /we4700 /we4789
_pyrfc.cpp
src/pyrfc\_pyrfc.cpp(4023): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:F:\anaconda3\libs /LIBPATH:F:\anaconda3 /LIBPATH:F:\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" sapnwrfc.lib libsapucum.lib /EXPORT:PyInit_pyrfc build\temp.win-amd64-3.9\Release\src/pyrfc\_pyrfc.obj /OUT:build\lib.win-amd64-3.9\pyrfc\pyrfc.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\src/pyrfc\pyrfc.cp39-win_amd64.lib -LIBPATH:F:\nwrfc750\nwrfcsdk\lib -LIBPATH:F:\anaconda3\lib\inspect.py\PCbuild /NXCOMPAT /STACK:0x2000000 /SWAPRUN:NET /DEBUG /OPT:REF /DEBUGTYPE:CV,FIXUP /MACHINE:amd64 /nologo /LTCG
_pyrfc.obj : warning LNK4197: export 'PyInit_pyrfc' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.9\Release\src/pyrfc\pyrfc.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\src/pyrfc\pyrfc.cp39-win_amd64.exp
Generating code
Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit code 1158

**Comment by bsrdjan** [comment]
The error is different then originally posted one. It looks like Visual Studio or dependency issue.

Build from source is more complicated way of installation and `pip install` should work on Windows without rebuilding the source.

Could you please post the full log of `pip install pyrfc` ?

**Comment by Aj-Revelino** [comment]
Log from `pip install pyrfc`:

Installing collected packages: pyrfc
  Running setup.py install for pyrfc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hameah\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hameah\\AppData\\Local\\Temp\\2\\pip-install-ugzo7z2b\\pyrfc\\setup.py'"'"'; __file__='"'"'C:\\Users\\hameah\\AppData\\Local\\Temp\\2\\pip-install-ugzo7z2b\\pyrfc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hameah\AppData\Local\Temp\2\pip-record-ql_36vdj\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\hameah\AppData\Local\Temp\2\pip-install-ugzo7z2b\pyrfc\
    Complete output (21 lines):
    750 Patch Level 10
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\pyrfc
    copying src\pyrfc\_exception.py -> build\lib.win32-3.8\pyrfc
    copying src\pyrfc\__init__.py -> build\lib.win32-3.8\pyrfc
    running build_ext
    building 'pyrfc.pyrfc' extension
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    creating build\temp.win32-3.8\Release\src
    creating build\temp.win32-3.8\Release\src\pyrfc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DSAPonNT -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATES -D_CRT_NONSTDC_NO_DEPRECATE -D_AFXDLL -DWIN32 -D_WIN32_WINNT=0x0502 -DWIN64 -D_AMD64_ -DNDEBUG -DSAPwithUNICODE -DUNICODE -D_UNICODE -DSAPwithTHREADS -D_ATL_ALLOW_CHAR_UNSIGNED -D_LARGEFILE_SOURCE -D_CONSOLE -DSAP_PLATFORM_MAKENAME=ntintel -Ic:\users\hameah\appdata\local\programs\python\python38-32\include -Ic:\users\hameah\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc/pyrfc/_pyrfc.cpp /Fobuild\temp.win32-3.8\Release\src/pyrfc/_pyrfc.obj -IF:\nwrfc750\nwrfcsdk\include -Ic:\users\hameah\appdata\local\programs\python\python38-32\lib\inspect.py\Include -Ic:\users\hameah\appdata\local\programs\python\python38-32\lib\inspect.py\Include\PC /EHs /Gy /J /MD /nologo /W3 /Z7 /GL /O2 /Oy- /we4552 /we4700 /we4789
    _pyrfc.cpp
    src/pyrfc/_pyrfc.cpp(21150): error C2664: 'RFC_RC RfcInstallGenericServerFunction(RFC_SERVER_FUNCTION,RFC_FUNC_DESC_CALLBACK,RFC_ERROR_INFO *)': cannot convert argument 1 from 'RFC_RC (__cdecl *)(RFC_CONNECTION_HANDLE,RFC_FUNCTION_HANDLE,RFC_ERROR_INFO *)' to 'RFC_SERVER_FUNCTION'
    src/pyrfc/_pyrfc.cpp(21150): note: None of the functions with this name in scope match the target type
    src/pyrfc/_pyrfc.cpp(29687): warning C4018: '<': signed/unsigned mismatch
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hameah\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hameah\\AppData\\Local\\Temp\\2\\pip-install-ugzo7z2b\\pyrfc\\setup.py'"'"'; __file__='"'"'C:\\Users\\hameah\\AppData\\Local\\Temp\\2\\pip-install-ugzo7z2b\\pyrfc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hameah\AppData\Local\Temp\2\pip-record-ql_36vdj\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 22.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by bsrdjan** [comment]
`python\python38-32\python.exe` indicates you might be using 32 bit python? In that case the 32-bit SAP NWRFC SDK is required so that and pip install can build and install the 32-bit pyrfc on your system.

On 64-bit Windows Python, the pip install does not start the build from source but downloads the pre-build binary from pypi.   If 64-bit installation needed, use the 64-bit Python and 64-bit RFC SDK.

To verify Python version:

```shell
PS C:\src\PyRFC> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Aj-Revelino** [comment]
Yes, there was a 32 bit installation in my PC. Cleaned it up and the issue has been resolved. Thanks!
