### ISSUE TITLE
(🎁) Support PEP-518

### ISSUE THREAD

**Issue by KotlinIsland** [SAP/PyRFC#281]
This project is distributed as an sdist, so building it with a PEP-518 build system doesn't work:
- https://github.com/python-poetry/poetry/issues/6261

ie add a pyproject.toml file with a `[build-system]` section.

**Comment by bsrdjan** [comment]
Please let me know if new version 2.5.1 works for you

**Comment by KotlinIsland** [comment]
I think it works fantastic!
