### ISSUE TITLE
Not able to call a function module with different destination

### ISSUE THREAD

**Issue by Skolluri836** [SAP/PyRFC#288]
Hi,

I am trying to call the function module "RFC_DETERMINE_JURISDICTION" which requires to pass the destination
![image](https://user-images.githubusercontent.com/104452303/202078661-79a7e605-2a92-42af-927d-f6243145fe0c.png)

Though documentation says "dest" parameter will accept the target destination, but not sure whether we need to pass this in call or connection method.  I have tired in both methods but no luck
Please suggest/fix or add this in feature scope.

**Comment by bsrdjan** [comment]
Hi @Skolluri836,
good suggestion, thanks. The "dest" field shown in screenshot is not related to PyRFC connection destination.
The PyRFC connection configuration, including destinations, is documented in 
[SAP NetWeaver RFC SDK ProgrammingGuide](https://support.sap.com/content/dam/support/en_us/library/ssp/products/connectors/nwrfcsdk/NW_RFC_750_ProgrammingGuide.pdf) (see `4.1.2 Using sapnwrfc.ini`), which is apparently not mentioned in PyRFC README or doc. Will add the link there and if you have better suggestion please let me know.

**Comment by bsrdjan** [comment]
Fixed by 42576bb
