### ISSUE TITLE
GCP Functions and PyRFC

### ISSUE THREAD

**Issue by Joselguti** [SAP/PyRFC#289]
Hello, I have been using PyRFC to consume data from SAP but all of this on a server instance, considering the fact you have to do some manual installations and configure enviroment variables I was wondering if it is possible to utilize PyRFC with technologies such as GCP Functions.

Thank you in advance.

**Comment by bsrdjan** [comment]
Hello @Joselguti,

SAP open source RFC Connectors for Python and NodeJS both use SAP NWRFC SDK C++ binaries, SAP standard product.

This library does not provide standard support cloud connectivity and as long that capability is missing, RFC open source connectors do not support cloud connectivity standard either (SAP SCC Secure Cloud Connector).

PyRFC deployment and deployment of RFC SDK binaries is technically possible on cloud platforms (tested on Cloud Foundry, AWS ...) and connectivity to on-premise ABAP backend can be established without SAP SCC, assuming SAP system is exposed to internet via web sockets, behind proxy etc. User example: https://github.com/SAP/node-rfc/issues/145
Recommended way is however using SAP Cloud Connector and SAP NWRFC SDK is not enabled for that usage context atc,

Voting for providing this capability in standard is possible here: [Add support for NW RFC in the Cloud Foundry Environment especially Node.JS Buildpack](https://influence.sap.com/sap/ino/#/idea/262169) (S-User required).

You can also comment on existing feature request for PyRFC cloud support: https://github.com/SAP/PyRFC/issues/51
