### ISSUE TITLE
SAP NW RFC Library (libsapnwrfc) Copyrights / Distribution in open source project

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#29]
I would like to distribute a little library on PyPI which uses PyRFC and thus depends on SAP NW RFC Library.

To make intallation process of my library as easy as possible I would like to include SAP NW RFC files in my package so that users of the library don't need to have a logon on SAP Market Place which may be too big hurdle for some users.

I gues there is no such issue with PyRFC as it is obviously open source but whom can I asked about permission for SAP NW RFC Lib files?

**Comment by bsrdjan** [comment]
That is unfortunately not allowed atm. SAP NW RFC Library is available only on SAP Service Marketplace and the assumption is that any user of PyRFC and similar software, requiring the NW RFC Lib, will connect to some backend system of SAP customer and SAP customer or partner can download the library from the Service Marketplace.

**Comment by Tset-Noitamotua** [comment]
One can use SAP NW trial from https://cal.sap.com/ , can't one?  I have not tried it yet but I hope that one can use PyRFC with it, too(?). If so then one would not need to be a SAP customer or partner to play with it. Thus to try PyRFC one would need access to SAP NW RFC Lib without an SAP Marketplace Logon. Please correct me if I am mistaken.

My hope is to be able to create a demo / tutorial which one can follow along with a free trial account on https://cal.sap.com/.

**Comment by bsrdjan** [comment]
No plans to release make the NW RFC lib public for the time being.
