### ISSUE TITLE
Question regarding applying SNC on PYRFC call for microservice

### ISSUE THREAD

**Issue by savlee** [SAP/PyRFC#295]
Hi there,

My team is trying to implement SNC for the pyRFC call for one of our microservice. The goal is to have the Python program acts as a “middleware system” and impersonates multiple end-users. We followed the documentation and apply the X509 with SNC approach in this link: [SNC with X509](http://sap.github.io/PyRFC/authentication.html )
 
We have encountered a “verification of own certificate failed error” after following the instruction on the document. After several failed attempts, I hope you don’t mind us reaching out to you. Could you please spare a few minutes and help us by review the steps below and point out what could be the possible issue?

Below is a brief on the implementation steps:

1. Download SAPGENPSE tool and create BDTUSER.pse, login BDTUSER.pse with the intended user
2. Create self-signed certificate and place it in BDTUSER.pse
3. Import the certificate into the target system, place the target system SNC SAPCryptolib certificate into BDTUSER.pse

(The above steps are performed in a docker container)
 
On the target system, BDTUSER snc_name is added in the control list (tran. SNC0). Users of the python service is mapped (tran. EXTID_DN) with X509 as external ID.

The Dockerfile has the env variable SECUDIR set as the same path as the pse and cred_v2 file was generated without issue. The python script in the container has the following format:  

from pyrfc import Connection
 
```python
ABAP_SYSTEM = {
    'snc_lib': '/usr/local/bin/libsapcrypto.so',
    'ashost': '10.177.53.245',
    'x509cert': '''{user X509 certificate in text}}''',
    'sysnr': '77',
    'client': '001',
    'snc_myname':'p:CN=BDTUSER, O=SAP-AG, C=DE',
    'snc_partnername': 'p/secude:CN=CVA, O=SAP-AG, C=DE',
    'snc_qop': '1',
}
 
c = Connection(**ABAP_SYSTEM)
 
print(c.get_connection_attributes())
```

The pyrfc call is working fine without the SNC in place. I previously created a ticket to the IT dep. of the target system, but they couldn’t find the issue and aid the set up on the target system should be correct. When looking into logs of the target system, I noticed that the SNC RFC call didn’t reach the system.

Thanks a lot for your help!

**Comment by bsrdjan** [comment]
Closed and discussed as SAP internal topic.
