### ISSUE TITLE
Is PyRFC the Python equivalent of JCo for Java?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#30]
I thought that PyRFC is the same for Python what JCo is for Java. But when I read [here](https://websmp109.sap-ag.de/rfc-library) 

>The improvements over the existing classic RFC Library are:
You no longer need to worry about getting the correct structure definitions for your imports, exports and tables. One API call fetches the complete definition of a function module from the backend DDIC and caches it for later use. (Metadata and repository functionality kind of like in JCo.)

especially the part
> (Metadata and repository functionality kind of like in JCo.)

I am a bit confused.

Can you clarify, please.

**Comment by bsrdjan** [comment]
PyRFC is the same kind of the RFC connector for Python, like the JCo is for Java. The first statement is about the _internal_ functionality of SAP NW RFC Library, to retrieve and cache the RFC metadata for the later use. The JCo is "kind of like", in a sense that it has automatic metadata lookup and caching functionality, with some functions exposed for the RFC client user. 

A nice [example from SAP Help](https://help.sap.com/saphelp_nwpi71/helpdata/en/45/b04688a2146000e10000000a1553f6/content.htm) shows what needs to be done on the C++ client side, to call an ABAP RFC using SAP NW RFC Library. Using JCo, the most of that is done internally, using the JCo built-in metadata and repository functionality. 

Thanks to dynamic nature of the language, in Python all this happens "automatically", fully transparent for the user and the RFC client programmer does not have to care about metadata and repository.

**Comment by Tset-Noitamotua** [comment]
Thanks for clarification!

**Comment by satyasashi** [comment]
In the website https://sap.github.io/PyRFC/ it shows the installation to Python 2. Does this support Python 3 as well?

**Comment by mpf82** [comment]
@satyasashi Yes, but different Python versions need different distributions. You can find them here: https://github.com/SAP/PyRFC/tree/master/dist
