### ISSUE TITLE
Outbound Queues support in pyrfc 

### ISSUE THREAD

**Issue by KunalBurangi** [SAP/PyRFC#300]
Continuing from issue [#284 ](https://github.com/SAP/PyRFC/issues/284)
and the example you provided [bgrfc](https://github.com/SAP/PyRFC/blob/BgRfcHandlers/examples/server/bgrfc.py#L43) 
what is SID ? what am I suppose to put there ? 
![image](https://user-images.githubusercontent.com/37167732/217781016-51390ff9-fad7-4499-acab-bbcb8b725ce2.png)
also this is what I am getting in response after running it as it is ... 
![image](https://user-images.githubusercontent.com/37167732/217781162-8d7c4fc7-a606-42e3-9081-59a1f694ffd1.png)

here's is what I am trying to do.
In SAP system I am using cfm2 to trigger the outbound queue and hoping that I receive the data. in pyrfc.  

@bsrdjan

**Comment by bsrdjan** [comment]
the branch is not a working implementation, only example how to register user-defined Python logic for processing bgRFC queues on server.

The implementation, testing and documentation of bgRFC server support might take a longer time. If more near-term solution needed, please submit feature request as customer incident in SAP BC-MID-RFC-SDK component.

For more info on bgRFC operations and configuration, you can refer to

- https://help.sap.com/doc/saphelp_nw73ehp1/7.31.19/en-us/48/9709f255493987e10000000a421937/frameset.htm
- [SAP NetWeaver RFC SDK ProgrammingGuide](https://support.sap.com/content/dam/support/en_us/library/ssp/products/connectors/nwrfcsdk/NW_RFC_750_ProgrammingGuide.pdf), referenced in https://support.sap.com/en/product/connectors/nwrfcsdk.html

**Comment by KunalBurangi** [comment]
ok. but can you please help us with a scenario? 

What I tried up till now was to use the same pyrfc setup to achieve the functionality. 
I created an Outbound Queue.
On the python side, this is the code. 
`
import os
from pyrfc import Server, set_ini_file_directory, Connection
import requests
import time

def my_custom_rfc(request_context=None, **param):
    print("my_custom_rfc invoked 0",param)


def TRFC_QIN_OVERVIEW(request_context=None, **param):
    print("TRFC_QIN_OVERVIEW invoked 0",param)
    return {"QVIEW":[],"QTABLE":[]}
    

def CIF_NQRFC_INFODET(request_context=None, **param):
    print("CIF_NQRFC_INFODET invoked 0",param)
    return {"EV_NEW_QRFC":"X","ET_QTABLE":[]}

def CIF_NQRFC_GET_HANGING(request_context=None, **param):
    print("CIF_NQRFC_GET_HANGING invoked 0",param)
    return {"EV_OK":"X","EV_NEW_QRFC":"","EV_UNREG_Q":"","EV_REG_Q":"*","ET_QVIEW":[],"ET_QTABLE":[]}

def main():
    dir_path = os.path.dirname(os.path.realpath(__file__))
    set_ini_file_directory(dir_path)
    server = Server({"dest": "gateway"}, {"dest": "client"},{"server_log":True})
    server.add_function("/SAPAPO/CIF_LOC_INBOUND", my_custom_rfc)
    server.add_function("TRFC_QIN_OVERVIEW",TRFC_QIN_OVERVIEW)
    server.add_function("/SAPAPO/CIF_NQRFC_INFODET",CIF_NQRFC_INFODET)
    server.add_function("/SAPAPO/CIF_NQRFC_GET_HANGING",CIF_NQRFC_GET_HANGING)
    print("\nPress CTRL-C to skip server test...")
    server.serve()
    time.sleep(3000000)
    
main()
`
"/SAPAPO/CIF_LOC_INBOUND" is a function that is supposed to give us the data
every other function i have added because it was giving logs that the function is not attached. 

when we activate the queue it gives us this error 
![image](https://user-images.githubusercontent.com/37167732/217810494-2c407ff9-9015-41bb-b78d-3e4dc60964f7.png)

also,
when I directly execute the function it gives us data... 

Can you please help us with the issue ?

**Comment by bsrdjan** [comment]
Background RFC server support and bgRFC event handlers' example implementation are provided in `pyrfc` release 2.7.2 and documented here: http://sap.github.io/PyRFC/server.html

Further investigation requires access to your test system or configuration of similar SAP internal test system, plus some consulting efforts.

If any further support needed, please open partner or customer ticket for component BC-MID-RFC-SDK, with reference to this issue.
