### ISSUE TITLE
RFCTable with TBL1024 structure

### ISSUE THREAD

**Issue by LeyersN** [SAP/PyRFC#31]
Hello

To upload a PDF binary file to SAP I can use an RFC function module. This FM requires two specific parameters:

- IC_ARC_OBJECT = the document class to define the mime type in SAP (OAC2)
- IN_CONTENT_LENGHT = IMPORTING data type, is the size of the file
- IT_CONTENT = IMPORTING table of structure TBL1024, table with the bytes of the file, cut into pieces of size 1024
- ET_MESSAGES = just a BAPIRET2 table to check on errors (RETURN table)

The function module is successfully executed in the PyThon program but when I break on the function module to check on the content of IT_CONTENT I can see that the lines of the table is not filled in correctly:

Extraction of the python program call of the FM:
`       
arc_object = "ZZ_PDF" 
content = Arc.get_arc_content(filename)
size = Arc.get_size(filename)
messages = []
result = connection.call("ZZ_UPLOAD_FILE", IC_ARC_OBJECT= arc_object, IN_CONTENT_LENGTH= str(size), IT_CONTENT= content, ET_MESSAGES= messages )
messages = result['ET_MESSAGES']
for mes in messages:
     print mes['MESSAGE']
`

Extraction of the python function Arc.get_arc_content(filename)
`

def get_arc_content(filename="file.pdf"):
    maxLineLength = 1024
    structure = []
    if filename == '':
        filename = 'file.pdf'
    with open(filename, 'rb') as file1:
        f = file1.read()
        n = 1024
        fl = [f[i:i + n] for i in range(0, len(f), n)]

    content = []
    for line in fl:
        lineapp = {
            u"LINE": line
        }
        print len(line)
        content.append(lineapp)

    return content
`

The result in SAP is the following for the parameters:

- IN_CONTENT_LENGHT = 000000007945 (7.8 kb)

- IT_CONTENT = 8 x 1 lines: (4lines)
LINE1	255044462D312E3300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
LINE2	B89B067867673EAB00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
LINE3	5BF4CB23B9A7513700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
LINE4	61DB44B3B0AAB12500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
....
LINE8
202020202020202000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

The expecting result for IT_CONTENT, checked with FM ARCHIVE_OBJECT_GET, should be something like:
LINE1
255044462D312E330D0A25E2E3CFD30D0A25525354585044463320506172616D65746572733A204452535458680D0A322030206F626A0D0A3C3C0D0A2F46696C7465722033203020520D0A2F4C656E67
LINE2
FA1D555450C8EF41AC263F14BC03C49BDD773CF22BC43FD21B3565DA2DFCCB83D8FFAC7BCBBBEBE6DED0AD68DEA29B349398511824DDDCFFAF41EA7FDADDF67EE61EF3FC303293F7E96351A911F8DE10
LINE3
FB4A559526CD6AED428976E80F8DD0B02517C4178D1EFB73C65792D09CFE5C717883BE38E61ED0AB3ADC0983C103E4338A1B210DA086DA73375E679C0A410F510FDC542BB686A1A4D601DD411A506504
...

So the problem is that only the first 4bytes) are transferred, the rest are trailing zero's.

Is this related to the fact that I'm doing something wrong, or isn't it possible to cut the binary files properly into chuncks of 1024 and transfer them into a table towards SAP.

Many thanks for your suggestions/support.

**Comment by bsrdjan** [comment]
it could be that the `size` should be size of the file itself, not the name of the file :)
```shell
content = Arc.get_arc_content(filename) size = Arc.get_size(filename) 
```

**Comment by LeyersN** [comment]
Hello

See the get_size function:
`def get_size(filename="file.pdf"):
    if filename == '':
        filename = 'file.pdf'
    print file_size(filename)
    stats = os.stat(filename)
    size = stats.st_size
    return size`

The size function gives the correct size of the file:

e.g. file of 41 kb has size of 41016 and will create a IT_CONTENT with 41 lines, 40 lines of size 1024 and 1 line with the remaining part

**Comment by bsrdjan** [comment]
do you have to use fixed size RAW type TBL1024 ? The alternative could be XSTRING, which is variable size and no need for 1024 chunks - just sequential read and send as byte sequence in XSTRING.

Do have an example of the RFC enabled function module with TBL1024 or similar RAW table parameter ? I would like to test and try to reproduce the issue.

**Comment by bsrdjan** [comment]
or use this:

```python
content = []
for line in fl:
    print len(line)
    content.append(line)
return content
```

**Comment by LeyersN** [comment]
thats the code I use!

I cannot share the real FM because of NDA, but the standard function modules of SAP are called:

`
CALL FUNCTION 'ARCHIVOBJECT_CREATE_TABLE'
         EXPORTING
              archiv_id                = archiv_id
              arc_doc_id               = arc_doc_id
              document_type            = document_type
              length                   = length
              compid                   = compid
              signature                = signature
         IMPORTING
              archiv_doc_id            = archiv_doc_id
         TABLES
              archivobject             = archivobject
              binarchivobject          = binarchivobject
         EXCEPTIONS
              error_archiv             = 1
              error_communicationtable = 2
              error_kernel             = 3.

  CASE sy-subrc.
    WHEN 1.
      RAISE error_archiv.
    WHEN 2.
      RAISE error_communicationtable.
    WHEN 3.
      RAISE error_kernel.

`


So if you create an own FM with this included, you can do the tests:

Thanks

**Comment by bsrdjan** [comment]
Thanks. Removing the LINE, per my prev comment, should fix.

**Comment by LeyersN** [comment]
Sorry, but what do you mean?

In python I cannot use the datatypes XSTRING, TBL1024 or similar RAW, 

In python I need to fill a table having the size en type of the RFCTABLE structure TBL1024

**Comment by bsrdjan** [comment]
I meant two solutions are possible. One is to use the IT_CONTENT parameter, of the TBL1024 type, just like it is now, and fill it with the array of 1024 byte sequences, not array of dictionaries:

```python
content = []
for line in fl:
    print len(line)
    content.append(line)
return content
```

Even simpler solution would be using IS_CONTENT parameter of the type XSTRING, instead of the IT_CONTENT. The advantage of XSTRING is that it is sequential, no need for chunks, and the memory is dynamically allocated. The entire file can be binary read into `content` and passed to IS_CONTENT parameter:

 ```python
with open(filename, 'rb') as file1:
    content = file1.read()
```

Would expect both to work.

**Comment by LeyersN** [comment]
the problem is that the IT_CONTENT is required for the existing FM, because it's going to transfer this table to the FM ARCHIVOBJECT_CREATE_TABLE.

so it is required to cut the binary object into pieces, in my opinion the blocks are ok but the transfer from python 2.7 -> PyRfc -> SAP is transforming, or is trimming the values with the known Issue

Also tried hexify, encoding struct .... with similar results.

**Comment by bsrdjan** [comment]
ok. did the first fix help ? If not, what is the error ?

```python
content = []
for line in fl:
    print len(line)
    content.append(line)
return content
```

**Comment by LeyersN** [comment]
this result:  File "_pyrfc.pyx", line 1574, in pyrfc._pyrfc.fillVariable (pyrfc\_pyrfc.c:16573)
  File "_pyrfc.pyx", line 1553, in pyrfc._pyrfc.fillTable (pyrfc\_pyrfc.c:16316)
AttributeError: 'str' object has no attribute 'iteritems'

**Comment by bsrdjan** [comment]
the error looks like the string passed to RFC table parameter. Can you share the Python source, that I can test tomorrow ? You can also send per Email.

**Comment by LeyersN** [comment]
I did the other way arround and requested the ET_CONTENT table for the know picture:

The result in python is this, with 1 line:
{u'LINE': '%PDF-1.3\r%\xe2\xe3\xcf\xd3\r\n7 0 obj\r<</Linearized 1/L 7945/O 9/E 3524/N 1/T 7656/H [ 451 137]>>\rendobj\r                       \r\n13 0 obj\r<</DecodeParms<</Columns 4/Predictor 12>>/Filter/FlateDecode/ID[<4DC91A1875A6D707AEC203BB021C93A0><F6C92B368A8A13408457A1D395A37EB9>]/Index[7 21]/Info 6 0 R/Length 52/Prev 7657/Root 8 0 R/Size 28/Type/XRef/W[1 2 1]>>stream\r\nh\xdebbd\x10``b`\xb2\x01\x12\x0c \x82\xb1\x01H0\xa7\x02\t6G \xf1\xe5\x18\x03\x13#\xc34\x90,\x03#\xb9\xc4\x7f\xc6\x9d_\x00\x02\x0c\x00L\xa4\x06\xf0\r\nendstream\rendobj\rstartxref\r\n0\r\n%%EOF\r\n        \r\n27 0 obj\r<</Filter/FlateDecode/I 69/Length 58/S 38>>stream\r\nh\xdeb```a``\xfc\xcf\x00\x04\xdc6\x0c\xa8\x80\x91\x01$\xcb\xd1\x80,\xc6\x02\xc5\x0c\x0c\r\x0c\xdc\x0c\xdc\xd3\x1et&\x808\xcc\x0c\x0cZ\x02\x10-\x8c,\x00\x01\x06\x00\xbf\xe2\x05\x19\r\nendstream\rendobj\r8 0 obj\r<</Metadata 1 0 R/Pages 5 0 R/Type/Catalog>>\rendobj\r9 0 obj\r<</Contents 11 0 R/CropBox[0 0 595 842]/MediaBox[0 0 595 842]/Parent 5 0 R/Resources 14 0 R/Rotate 0/Type/Page>>\rendobj\r10 0 obj\r<</Filter/FlateDecode/First 94/Length 773/N 13/Type/ObjStm>>stream\r\nh\xde\xbcTmo\xda0\x10\xfe+\xfe\x03\xe0\x97\xd8q"UH\xd0\x8e\xae\xd2Z\xa1&[?D\xf9\x90\x82\x0b\x91B\x82\x12W\xa3\xff~w\t.\x81\xb5+\xa5\xd2\x88\xcc\xf9\xe5\xee|\xbe\xe7\xb9\xe3\x920\xc2\x15\xe1\x9e&\xdc\'"\x80\x95&\x9e\x08\x08\x0f\x88\xe7\x83\x08\x89\x94\x8a\x08FT\xc8\x88\xe0$\x14\xa0&\x08gZ\x12\xe1\x81\xad\xe6DH\xb0b!\x11\xe0(\x90\xb0\x06\x15\xc6$\xb9\xb8\xa0\x97UQ\xd5\xd1&\x9b\x1b\\4\n/c\xe4~4\xa2\xdf\xb6\xf6:\xb2\x99\xc5\x83\xeb\x88\xe3\xf5\xdd\xc1\xb4*-\xecM\x05\xc6\x00[4\x8e\x05\x06\xd0M%\xde\xdeM}\xbc'}
....

I will send you an email with the python programs

**Comment by LeyersN** [comment]
As you suggested, the **pyrfc-1.9.4-py2.7-win-amd64.egg** solved the issue.

Seems to be a **Windows + PyRFC 1.9.3 version** issue, the 1.9.4 distribution works perfect, 

**Many, Many thanks for your support!**

**Comment by naveenronuru** [comment]
Hi, I’m using the same FM to send attachments to Dms server, I could able to create the link and send the file content, but jpg file is not getting posted properly couldn’t able to view colour content, I’m passing the file length to the parameter length

can I get any help here ??

**Comment by bsrdjan** [comment]
Please open the new issue, providing a test Python script and:

- SAP NWRFC SDK version
- PyRFC release
- Operating system

**Comment by naveenronuru** [comment]
Hi 

I'm not using any python script, We are developing a functionality to send the Attachments from Sap server to other content server, for that purpose I'm using the Function Module : ARCHIVOBJECT_CREATE_TABLE

My requirement is to send only jpg files to other server, to enhance this functionality I'm sending hex format of jpg image to the 
 BINARCHIVOBJECT  of the table parameter,

Using the below mentioned code, Attachments is getting posted and I could able to view only 20 percent of Image remaining object got color changed

Here is my code:

*--------------------------------------------------------------------*
* Data Declarations for Internal Tables and Structures
*--------------------------------------------------------------------*

   Data : lv_archiv_id type SAEARCHIVI,
          lv_doc_id    type SAPB-SAPADOKID,
          lv_scan_profile type VSCAN_PROFILE,
          ls_attachments type zstr_pm_notif_attachments,
          lv_number(12) type n,
          lv_length_new type i,
          lv_notification type qmnum.

  Data : lt_binary_data type table of TBL1024,
         lt_binary_data_1 type table of TBL1024,
         lt_document type table of DOCS,
         ls_binary_data type tbl1024,
         lv_lines type I,
         lv_file_data type xstring,
         lv_content_length type SAPB-LENGTH.

          lv_scan_profile = '/SCMS/KPRO_CREATE'.

          Data : lv_leng type SAPB-LENGTH,
                 lv_rest type sapb-length,
                 lv_act  type sapb-length,
                 lv_off type sapb-length,
                 lv_tab1024 type tabl1024,
                 lv_t1  type sapb-length,
                 lv_length type SAPB-LENGTH.



   DATA :
        lv_strlen type string,
        lt_string_comp type table of SWASTRTAB,
        ls_string_comp type SWASTRTAB.

  Data : lt_component type table of http_comp,
         ls_component type http_comp.

  Loop at it_attachments into ls_attachments.

lv_leng = strlen( ls_attachments-file_data ).

        IF lv_leng NE 0.
           lv_rest = lv_leng.

           WHILE lv_off < lv_leng.

             IF lv_rest <= 1024.
                lv_t1    = lv_rest.
             ELSE.
               lv_t1 = 1024.
             ENDIF.

              ls_binary_data-line  = ls_attachments-file_data+lv_off(lv_t1).
             APPEND ls_binary_data to lt_binary_data.

             lv_act = xstrlen( ls_binary_data-line ).

             lv_rest = lv_rest - lv_act.
             lv_off = lv_off + lv_act.

            ENDWHILE.


        ENDIF.

  CALL FUNCTION 'ARCHIVOBJECT_CREATE_TABLE'
            EXPORTING
              archiv_id                      = 'A1'
              document_type                  = 'ZZM'
              LENGTH                         = lv_leng
              COMPID                        = 'DATA'
              SIGNATURE                     = 'X'
              VSCAN_PROFILE                 = '/SCMS/KPRO_CREATE'
            IMPORTING
              ARCHIV_DOC_ID                  = lv_doc_id
           TABLES
             COMPONENTS                     = lt_component
             BINARCHIVOBJECT                = lt_binary_data
           EXCEPTIONS
             ERROR_ARCHIV                   = 1
             ERROR_COMMUNICATIONTABLE       = 2
             ERROR_KERNEL                   = 3
             BLOCKED_BY_POLICY              = 4
             OTHERS                         = 5
                    .
          IF sy-subrc <> 0.
* Implement suitable error handling here
          ENDIF.

          CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
           EXPORTING
             WAIT          = 'X'.
                    .
   CALL FUNCTION 'ARCHIV_CONNECTION_INSERT'
        EXPORTING
           ARCHIV_ID                   = 'A1'
           arc_doc_id                  = lv_doc_id
           AR_DATE                     = ls_attachments-storage_date
           ar_object                   = 'ZZM'
           object_id                   = ls_attachments-object_id
           sap_object                  = ls_attachments-doc_object
           DOC_TYPE                    = ls_attachments-file_type
**         BARCODE                     = ' '
           FILENAME                    = ls_attachments-file_name
           DESCR                       = ls_attachments-description
           CREATOR                     = ls_attachments-created_by
       EXCEPTIONS
         ERROR_CONNECTIONTABLE       = 1
         OTHERS                      = 2

 ENDLOOP.
