### ISSUE TITLE
After upgrading to Pyrfc 2.7.2: get_function_description gives me a NameException: enum_names is not defined

### ISSUE THREAD

**Issue by bluckau** [SAP/PyRFC#311]
**Issue** 
When I use get_function_description() it throws an exception (NameError: 'enum_names' is not defined)

**To Reproduce**
        from pyrfc import Connection
        connection = Connection(ashost = (redacted)', sysnr=(redacted)', client=(redacted), user=(redacted)', passwd=(redacted))
        stuff = connection.get_function_description('BAPISDORDER_GETDETAILEDLIST')
        print(stuff.parameters)

**Environment**
 - OS: Windows
 - Running in docker? not currently
 - PyRFC version 2.7.2
 
 (Note this also happens running in Linux+docker)

**Additional context**
Our code worked in pyrfc <= 2.7.0. The code above is a distilled version of what is in the code base but still reproduces the problem.

I have also tried other function names such as BS01_SALESORDER_GETDETAIL

**Comment by bluckau** [comment]
I accidentally said PyRFC version 2.7.0 in the original description. Actually, this only happens after upgrading to 2.7.2.

**Comment by bsrdjan** [comment]
it is a bug, just reproduced in 2.7.2. Will be fixed on priority

**Comment by senthu73** [comment]
Sound great, Srdjan.
