### ISSUE TITLE
"pip install pyrfc" does not work in Debian GNU/Linux

### ISSUE THREAD

**Issue by IssacH** [SAP/PyRFC#313]
**Describe the bug**
We have a jenkins testing pipeline to install **pyrfc** in a docker container. And we noticed the installation failed after running "pip install pyrfc" with version **2.8.0**. It could not be reproduced in pyrfc previous versions

**To Reproduce**
1. docker pull di-qa-docker-public.int.repositories.cloud.sap/di-qa-python
2. docker run --entrypoint /bin/bash -it `<image-name>`
3. Inside the container, execute `pip install pyrfc`

**Screenshots**
![image](https://user-images.githubusercontent.com/17758420/233270888-91c89d9b-0261-4e48-ae47-adbfb1010153.png)

**Environment**

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```
 - Running in docker? Yes
 - PyRFC version: 2.8.0

**Comment by bsrdjan** [comment]
It was an issue in Linux installation configuration, fixed now in 2.8.1 version.
