### ISSUE TITLE
Qualifiers to delimiter fields

### ISSUE THREAD

**Issue by eumateuscandido** [SAP/PyRFC#321]
**Is your feature request related to a problem? Please describe.**
I'm using the RFC_READ_TABLE function to export data from SAP, but some columns are being concatenated. Example: When importing the BSIK, the DMBTR field is concatenating with any other fields that come after it.

**Describe the solution you'd like**
As a solution, it would be interesting in addition to the delimiter to have qualifiers to delimit the size of the fields, like quotes.

**Describe alternatives you've considered**
Alternatively, its size could be described for each field, so that it would be exported in its correct configuration.

**Comment by bsrdjan** [comment]
PyRFC does not provide a functionality specific to any ABAP function module. Therefore this feature request will not be implemented in PyRFC. The request can be created on SAP customers influence platform, for RFC_READ_TABLE function module.
