### ISSUE TITLE
Wheel for Linux and ARM64

### ISSUE THREAD

**Issue by titovanton** [SAP/PyRFC#324]
Hello, 
I'm using Docker on Mac OS with M1 CPU. Would be nice to have a wheel for this kind of setup. 
Thanks.

**Comment by bsrdjan** [comment]
Hello Anton,
amd64 wheel can be used also in docker on M1. Just run the container for amd64 platform, like here
https://github.com/SAP/fundamental-tools/blob/main/docker/ubuntu-qa.Dockerfile#L9
Would that work for you?
Linux binary wheels are generally not recommended and build from source is the only installation guaranteed to work on Linux
Best regards,
Srdjan

**Comment by titovanton** [comment]
> https://github.com/SAP/fundamental-tools/blob/main/docker/ubuntu-qa.Dockerfile#L9

Thank you!
