### ISSUE TITLE
File README.rst is missing for build localy

### ISSUE THREAD

**Issue by dheule** [SAP/PyRFC#33]
You have changed the setup.py from README.md to README.rst,
but the README.rst ist not present.

Please fix ;-)

Thank you

**Comment by tehpr0** [comment]
Bump. Having same issue.

**Comment by bsrdjan** [comment]
fixed [5acc0d0](https://github.com/SAP/PyRFC/commit/5acc0d03386c5cdf9f308330a8988f8d6d7901e0).
