### ISSUE TITLE
SAPNWRFC_HOME Environment Variable

### ISSUE THREAD

**Issue by bensonrlee** [SAP/PyRFC#334]
**Is your feature request related to a problem? Please describe.**
Is it possible to get the value of SAPNWRFC_HOME by setting it programmatically instead of an environment variable?  For example, having it in the same directory as the script/program and dynamically referencing the `/lib` directory?

**Describe the solution you'd like**
Instead of requiring the use of SAPNWRFC_HOME environment variable, allow the path to be specified programmatically.

**Describe alternatives you've considered**
None yet

**Additional context**
N/A

**Comment by bsrdjan** [comment]
Is SAPNWRFC_HOME really needed in your scenario? It is used only in PyRFC installation and build and not required in regular use. Can you describe the actual problem the proposed change should solve?

**Comment by bensonrlee** [comment]
Hello @bsrdjan ,

I would like to make sure I understand this correctly.  Do you mean to say if I convert to a singlefile exe, I no longer need to have an end user install `nwsdk` manually, and thus, there is no need to set the environment variable on their PC?

Thank you!

**Comment by bsrdjan** [comment]
Packaging SAP NW RFC SDK with PyRFC is not allowed because licenses are different. The SDK must be installed separately. I just try to understand the problem the problem with current solution. Could you please describe the usage scenario and the issue with current solution?

**Comment by bensonrlee** [comment]
Hello @bsrdjan ,

I was wondering if there is a way to include the prerequisites in my binary, which means including `nwsdk` in it.  This way, the program would be a "portable" single file exe program.

But as you said in your response, it seems this is not allowed due to license restrictions in `nwsdk`.

**Comment by bsrdjan** [comment]
Is is unfortunately not allowed, because of SAP NW RFC SDK is not open source and has different license terms
