### ISSUE TITLE
[S]upport - setup connection

### ISSUE THREAD

**Issue by dnsBlah** [SAP/PyRFC#34]
Hi all,

I'm trying to setup a connection through load balancer using saprouter string.
I'm not sure how to format it all, hopefully someone can/will help me out here.
```
from pyrfc import Connection

TEST = {
    'user'      : 'myUser',
    'passwd'    : 'myPass',
    'saprouter' : '/H/198.125.208.20/S/3299/H/',
    'mshost'    : 'SV006P0G',
    'sysid'     : '68',
    'group'     : '840_SAPGUI',
    'client'    : '840',
    'trace'     : '3',
    'lang'      : 'EN'
}

conn = get_connection(TEST)
#want to do a check here
conn.close()
```

Parts of the details are provided by external party who supports our SAP system.
The response I get is:

```
Traceback (most recent call last):
  File "asd.py", line 2, in <module>
    conn = Connection(user='myUser', passwd='myPass', saprouter='/H/198.125.208.20/S/3299/H/', mshost='SV006P0G', sysnr='68', client='840')
  File "_pyrfc.pyx", line 123, in pyrfc._pyrfc.Connection.__init__ (pyrfc/_pyrfc.c:2110)
  File "_pyrfc.pyx", line 161, in pyrfc._pyrfc.Connection._open (pyrfc/_pyrfc.c:2613)
  File "_pyrfc.pyx", line 191, in pyrfc._pyrfc.Connection._error (pyrfc/_pyrfc.c:2792)
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message= [MSG: class=, type=, number=, v1-4:=;;;]
```

This shouldn't be such a rocket science... should it?
Can someone point me out whats going wrong here

**Comment by bsrdjan** [comment]
Per error message output it looks like network issue. In case of network issues, it helps first check  names and values of relevant connection parameters.

The parameters for the scenario with load balancer are described on pg. 5 of [SAP NetWeaver RFC SDK Guide](https://websmp109.sap-ag.de/~sapidb/011000358700000869672007.pdf), the document linked at the bottom of http://service.sap.com/rfc-library.

Connection param names and values look ok, except the router string, in which the target seem to be missing  -> SAP Help  [Route String Entry for SAProuter](   https://help.sap.com/saphelp_nw70/helpdata/en/4f/992df1446d11d189700000e8322d00/content.htm).

I would suggest a Basis expert check and fix the saprouter string.

`niping` utility can help troubleshooting saprouter string and network issues in general:

[Testing Basic Functions](https://help.sap.com/saphelp_nwpi711/helpdata/en/48/6c623d1d5a350ce10000000a42189d/content.htm)

When saprouter string fixed and works with `niping`, it should work rfc connector as well.

**Comment by dnsBlah** [comment]
Hi bsrdjan,

on OSX we use the following connection string:
`conn=/H/198.125.208.20/S/3299/M/P6G.sds-host.de/S/3668/G/840_SAPGUI&clnt=840`
But this is on SAPGUI

The details provided in the topic, are from a Windows GUI
I can't find any way to install niping. 

I only need to 'login' check if I'm logged in, and disconnect.

**Comment by bsrdjan** [comment]
Hi,
you need a little help from SAP Basis consultant.
 
The SAP NW RFC Library and `niping` are not available for OSX and PyRFC is therefore also not supported on OSX - see "Platform and Prerequisites" in PyRFC [README](https://github.com/SAP/PyRFC/blob/master/README.md))

Can you use Linux VM on OSX or Linux box ? Or Windows ?

**Comment by dnsBlah** [comment]
Hi,

I'm trying to set it up on Linux :-) Thats where I installed PyRFC.
If it's in the Library, I'll have another look.

**Comment by bsrdjan** [comment]
hier the OSS note how to find and install `niping`

[799428 - Downloading SAProuter and/or niping](https://launchpad.support.sap.com/#/notes/799428/E)

**Comment by dnsBlah** [comment]
@bsrdjan,
we are not using niping server.

But I got a bit further now:
```
SAPROUTER = '/H/198.125.208.20/S/3299/H/P6G.sds-host.de/S/3268'
TEST = {
    'user'	: 'dsweben',
    'passwd'    : 'BlahBlah88',
    'saprouter' : SAPROUTER,
#    'mshost'    : 'SV006P0G',
    'ashost'     : '198.125.208.20',
    'sysid'     : 'P6G',
    'sysnr'     : '68',
    'group'     : '840_SAPGUI',
    'client'    : '840',
    'trace'     : '3',
    'lang'	: 'EN'
}
```
