### ISSUE TITLE
ImportError: cannot import name 'Connection' on Suse Linux

### ISSUE THREAD

**Issue by nf345g** [SAP/PyRFC#342]
I am trying to install pyrfc on Suse Linux and getting the following error and just import pyrfc works fine.

>>> from pyrfc import Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Connection'

Environment :

OS : SUSE Linux Enterprise Server 15 SP3
Python : Python 3.6.15 (Default version)
Cython : Version: 3.0.4
PyRFC shows version as : 
pip3 show pyrfc
Name: pyrfc
Version: 0.0.0

Below are steps I have tried.

1. Install SAP NW RFC SDK 7.50 Patch Level 12 and create an SAPNWRFC_HOME point to the nwrfcsdk library 

2. Install cython and build the python wheel from source distribution using below steps as mentioned here https://github.com/SAP/PyRFC

git clone https://github.com/SAP/PyRFC.git
cd PyRFC
python3 setup.py bdist_wheel
cd dist
pip install pyrfc-0.0.0-cp36-cp36m-linux_x86_64.whl

Issue seems to be same as https://github.com/SAP/PyRFC/issues/191 - but this didn't really help me as the environment is different. Kindly assist if someone has the experience of setting up pyrfc on Suse Linux.

p.s : I have installed this on window platform and it is working fine. Issue is with Suse Linux.

**Comment by bsrdjan** [comment]
Python 3.6 is not supported, 3.8 is the minimum version required.

RFC SDK binaries shall be also registered on your system, as described here: https://sap.github.io/PyRFC/install.html#linux

Check similar question: https://github.com/SAP/PyRFC/issues/339

**Comment by nf345g** [comment]
> Python 3.6 is not supported, 3.8 is the minimum version required.
> 
> RFC SDK binaries shall be also registered on your system, as described here: https://sap.github.io/PyRFC/install.html#linux
> 
> Check similar question: #339
 
@bsrdjan  : Thanks for the response. Let me try that and get back to you with the results.

**Comment by bsrdjan** [comment]
Check also the installation documentation
https://github.com/SAP/PyRFC#download-and-installation
