### ISSUE TITLE
paths_fix.sh fails 

### ISSUE THREAD

**Issue by richca** [SAP/PyRFC#344]
**Describe the bug**
When trying to run the paths_fix.sh the script fails on Apple Arm OS 14.1 Sonoma. Pyrfc wont' work for me because NWFC won't setup correctly.

I did change the script to zsh instead of bash since bash wasn't work either. I also did try running as sudo. 

**To Reproduce**
Describe the steps to reproduce the behavior, including test script.

**Screenshots**
![image](https://github.com/SAP/PyRFC/assets/31680267/87826492-86ae-42bb-92dd-5fc5ecc2d063)

**Environment**
 - OS: Mac Sonoma 14.1 Arm 
 - Running in docker? No 
 - PyRFC version 3.3

**Additional context**

**Comment by bsrdjan** [comment]
Thanks @richca for reporting this bug. [paths_fix.sh](https://github.com/SAP/PyRFC/blob/main/ci/utils/paths_fix.sh) should work now
