### ISSUE TITLE
BW Query with Parameters - ERROR: IVALID INPUT

### ISSUE THREAD

**Issue by Yasine001** [SAP/PyRFC#348]
I have an issue retrieving data using a bw query.

I use the function module RRW3_GET_QUERY_VIEW_DATA to query data from the bw based predefined queries. This function module also give the prossibility the query data based on certain predefined parameters. It works prefectly with queries with no parameters, but once I try al call data from a query with parameters, I get an error.
 
The Query functions prefectly in Excel (Analysis for Office):

![image](https://github.com/SAP/PyRFC/assets/49436175/2d053e1a-65d4-4c72-a8d2-d64367d4a506)

But with Pyrfc I get the error the input is invalid:

![image](https://github.com/SAP/PyRFC/assets/49436175/d98da8e4-ff2f-4489-b83f-51c102fd47c3)

I also tried to give the parameter ID instead of the name, but I get the same error.  The Key words "Name" und "Value" are recognized, but somehow I get the same error. 

Does anyone please have experince with inputs and can help. Thanks

**Comment by bsrdjan** [comment]
`RRW3_GET_QUERY_VIEW_DATA` function module is not supported, please check SAP Help
https://help.sap.com/docs/SUPPORT_CONTENT/bwplaolap/3361386636.html

The error is not PyRFC error, more likely the inconsistence of input parameters.

**Comment by Yasine001** [comment]
Hallo Srdjan,

thanks for the response. I was able parameters:

`parameters = [{'NAME': 'VAR_NAME_1', 'VALUE': &THE_TECHNICAL_NAME_OF_THE_VARIBALE}, {'NAME': 'VAR_VALUE_EXT_1', 'VALUE': lv_matnr}]`

**Comment by Yasine001** [comment]
Hallo Srdjan,

I was able parameters. Just In in case needs the same Info:

`parameters = [{'NAME': 'VAR_NAME_1', 'VALUE': &THE_TECHNICAL_NAME_OF_THE_VARIBALE}, {'NAME': 'VAR_VALUE_EXT_1', 'VALUE': &THE_VALUE}]`

Thanks for the information about the function module - from practical experience, it does indeed have a memory problem. It only retrieves a limited amount of data. . I'll soon be moving to `RSDRI_INFOPROV_READ_RFC`, which is supported and maintained.
