### ISSUE TITLE
Error while setting up PyRFC

### ISSUE THREAD

**Issue by elohmeier** [SAP/PyRFC#35]
I'm having a problem setting up PyRFC on debian. 
On a clean install I've installed python 3.5 and put the nwrfcsdk to /usr/sap/lib as in the install documentation. ldconfig is reporting no problems.
I've installed PyRFC using easy-install.

When trying to create a connection in python, I'm getting the following error:
`Traceback (most recent call last):
  File "/code/sap.py", line 6, in <module>
    from pyrfc import Connection
  File "/usr/local/lib/python3.5/site-packages/pyrfc-1.9.5-py3.5-linux-x86_64.egg/pyrfc/__init__.py", line 22, in <module>
    from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
ImportError: /usr/local/lib/python3.5/site-packages/pyrfc-1.9.5-py3.5-linux-x86_64.egg/pyrfc/_pyrfc.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
`
Do you have an idea what's wrong with PyFPE_jbuf?

**Comment by bsrdjan** [comment]
I am testing on ubuntu and never had such issue. Just tested again with Python 3.5.2:

```shell
git clone https://github.com/SAP/PyRFC.git
python3 setup.py install --user
cd tests
python3
from pyrfc import *
```

Eventually a python(s) path/environment issue, in this direction: https://github.com/scikit-learn/scikit-learn/issues/7542 ?

**Comment by bsrdjan** [comment]
Is this issue still open?

**Comment by elohmeier** [comment]
I still have to test this on ubuntu, tried on Debian the last time. As I'm on vacation right now, I'll close the issue. I'll open a new one if the error persists. Thanks :)

**Comment by warp3r** [comment]
Hi there,

I've been checking and conclussions are that PyRFC is not working for RHEL systems (Centos included)

```
[root@ip-172-31-2-170 tmp]# python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrfc import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyrfc-1.9.4-py2.7-linux-x86_64.egg/pyrfc/__init__.py", line 22, in <module>
    from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
ImportError: /usr/lib/python2.7/site-packages/pyrfc-1.9.4-py2.7-linux-x86_64.egg/pyrfc/_pyrfc.so: undefined symbol: PyFPE_jbuf
```

Same configuration on a SuSE box:
```
ip-172-31-6-59:/usr/sap/nwrfcsdk # python
Python 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrfc import *
>>> exit()
```

To be transparent, we use this provisioning script (very simple):
```
#!/bin/bash
sudo zypper -n in python-setuptools
sudo cp /tmp/SAPCAR /usr/local/bin/SAPCAR
sudo chmod +x /usr/local/bin/SAPCAR
sudo mkdir -p /usr/sap
cd /
sudo tar zxvf /tmp/nwrfcsdk.tgz
sudo echo "/usr/sap/nwrfcsdk/lib" > /etc/ld.so.conf.d/nwrfcsdk.conf
sudo ldconfig 
cd /tmp
sudo easy_install pyrfc-1.9.4-py2.7-linux-x86_64.egg
```

**Comment by warp3r** [comment]
Hi there,

I've been able to build an egg that works for centos and redhat 7.

**Comment by bsrdjan** [comment]
Hi,

glad to hear it works on centos and redhat. I see 1.9.4 version is used and just to mention that 1.9.6 is also available, with few bugs fixed.

**Comment by pawel1392** [comment]
Hi warp3r. Could you please let me know how to build an egg to be working on Centos 7 ? I am facing the same issue :/
