### ISSUE TITLE
Cannot call Connection from the pyrfc import or any other object

### ISSUE THREAD

**Issue by guicastello** [SAP/PyRFC#361]
**Describe the bug**
I'm trying to implement pyrfc in my python project, but after all the installations of the library, and the nw rfc sdk package, I can't call the connection through import.
I've seen some, if not all, of the issues with related problems and they say to use pip install pynwrfc, but I've also seen on https://pypi.org/project/pynwrfc/ that it's been yanked. So I really don't understand what to do. 
The issue I saw was from 2020, should I use what pynwrfc or pyrfc? Can you help me, please?

**To Reproduce**
I've done the installations that README.md tells me to, and I've tried to start coding.

**Screenshots**
![image](https://github.com/SAP/PyRFC/assets/122810534/8c5b324f-c935-4411-af58-8f92e5c0f4d0)

**Environment**
 - OS: Linux Ubuntu 22.04
 - Running in docker? No
 - PyRFC version: 3.3.1
 - Cython version:3.0.8
 - Installed NWRFCSDK in folder /usr/local/sap/nwrfcsdk
 - Set SAPNWRFC_HOME variable to path = /usr/local/sap/nwrfcsdk

**Comment by bsrdjan** [comment]
`pynwrfc` is obsolete and not supported. Uninstall that package first.

SAP NW RFC SDK libraries must be registered on Linux. Either add `/usr/local/sap/nwrfcsdk/lib` to LD_LIBRARY_PATH, or using `ldconfig`, as described in  PyRFC documentation: https://sap.github.io/PyRFC/install.html#linux

To verify SAP NW RFC SDK libraries are registered correctly, check the RFC SDK version number:

```shell
cd $SAPNWRFC_HOME/bin
./startrfc -v
```

Then PyRFC should work as well.

**Comment by guicastello** [comment]
First of all, thank you very much for your help and your comment!

I've added the path to the LD and also checked the SDK version, both work as seen in the images below. However, I still can't find the path to Connection in the code.
![image](https://github.com/SAP/PyRFC/assets/122810534/de19977e-a7fe-4346-a1b5-ae68f40de2ef)
![image](https://github.com/SAP/PyRFC/assets/122810534/dbb927cf-daab-461d-baef-7b9ea4a8c80b)
![image](https://github.com/SAP/PyRFC/assets/122810534/fad560de-3989-467b-8634-b17f06ce4cd8)

I checked that inside my venv where I'm using pyrfc, the _cyrfc file has the .so format. Could it be that I'm not having some kind of error when downloading and transforming this into a py file and that's why I can't import it? Could this have something to do with it? 
![image](https://github.com/SAP/PyRFC/assets/122810534/d4fd0d6d-9340-48cb-a008-3580d0164735)

**Comment by IsmaelAlvarez** [comment]
installed pyrfs using 

`pip3 install pyrfc` and another time using `pip install pyrfc`

same error

![image](https://github.com/SAP/PyRFC/assets/7153162/6c0bf337-1f48-426d-aa7e-bbbf13cd114f)

**Comment by bsrdjan** [comment]
Could it be that pynwrfc impacts the installation?

Anyway, the hotifx should not be installed, unless requested by SAP Support. If not requested, please uninstall RFC SDK and install/register PL12, without hotfix.

Then create new virtualenv and run pip install pyrfc there. Just to ensure the pynwrfc leftovers does not cause issues.

The so format is ok, here how it looks in test system

```shell
$ cd ...site-packages
$ tree pyrfc
pyrfc
├── _cyrfc.cpython-311-x86_64-linux-gnu.so
├── _exception.py
├── __init__.py
└── _utils.py
```

**Comment by bsrdjan** [comment]
@IsmaelAlvarez, the error is different, it looks like pyrfc is not installed.

Is it listed in `pip freeze` or `pip list` output?

**Comment by IsmaelAlvarez** [comment]
> @IsmaelAlvarez, the error is different, it looks like pyrfc is not installed.
> 
> Is it listed in `pip freeze` or `pip list` output?


it does show
![image](https://github.com/SAP/PyRFC/assets/7153162/e3402cfc-30df-4ce0-a451-714085499c7a)

**Comment by bsrdjan** [comment]
@IsmaelAlvarez 

no idea yet. Could you please open new issue because the symptom is different and provide requested info on platform, python, sdk
