### ISSUE TITLE
RFC_BUFFER_TOO_SMALL for emoji symbols

### ISSUE THREAD

**Issue by Pentusha** [SAP/PyRFC#38]
Hello, I recompiled library with huge utf8_size, but still got an error on 4 bytes strings.
https://github.com/SAP/PyRFC/issues/7#issuecomment-283973702

**Comment by bsrdjan** [comment]
could you please post the `ZHHDEMO_BASESCALARS` parameters' signature, showing the ABAP DDIC type of the `IM_SCALAR_C` parameter ? 
```python
response = connection.call('ZHHDEMO_BASESCALARS', IM_SCALAR_C=u'\U0001F4AA')
```
After pyrfc recompile, do you uninstall the old pyrfc wheel and install the new one?

**Comment by Pentusha** [comment]
I tried with different virtual environments, so recompile and uninstall is unnecessary.
![selection_046](https://cloud.githubusercontent.com/assets/1904496/23860190/3f44f7f4-0817-11e7-8bb2-a578442c7bc4.png)
![selection_047](https://cloud.githubusercontent.com/assets/1904496/23860993/ae13ed00-0819-11e7-9d85-7e79efaa8319.png)

```
FUNCTION ZHHDEMO_BASESCALARS.
*"----------------------------------------------------------------------
*"  IMPORTING
*"     VALUE(IM_SCALAR_C) TYPE  ZHHE_SCALAR_C OPTIONAL
*"     ...
*"  EXPORTING
*"     VALUE(EX_ZHHT_MERGE) TYPE  ZHHTT_MERGE
*"----------------------------------------------------------------------

  DATA: ls_merge TYPE zhhs_merge.

  "IF IM_SCALAR_C IS NOT INITIAL.
    CLEAR ls_merge.
    ls_merge-PARAM_NAME = 'IM_SCALAR_C'.
    ls_merge-COL_C      = IM_SCALAR_C.
    APPEND ls_merge TO EX_ZHHT_MERGE.
  "ENDIF.

  ...

ENDFUNCTION.
```

**Comment by bsrdjan** [comment]
The name of the DDIC element is missing on 1st screenshot. Is it ZHHE_SCALAR_C type of CHAR255 ?

The structure ZHHS_MERGE is not used in the python call, does it have anything to do with this issue?

**Comment by Pentusha** [comment]
I do not know what is DDIC and where to see it.
![selection_050](https://cloud.githubusercontent.com/assets/1904496/23863666/59467ff6-0821-11e7-9847-baf38fbfd0c8.png)
![selection_049](https://cloud.githubusercontent.com/assets/1904496/23863668/59567258-0821-11e7-8f1d-259a44d60335.png)

**Comment by bsrdjan** [comment]
yes, it is new bug, regarding 8 bytes unicodes handling. Thanks for helping reproduce it. DDIC stands for SAP Data Dictionary.

The fix is available in [dev](https://github.com/SAP/PyRFC/tree/dev) branch, just pushed. Could you please try if works for you ?

**Comment by Pentusha** [comment]
It's works for me. Thanks.

**Comment by bsrdjan** [comment]
Glad it helps :)

**Comment by inviscid** [comment]
Hi,

We are running into this same issue today.  Latest release shows over 10 months old.  Is this fixed, and if so, how do we go about getting the updated code operational.  Unfortunately, I am somewhat confused as to whether this was fixed and how we get this to work.

Thanks in advance...
