### ISSUE TITLE
PyRFC & SAP  S/4HANA

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#39]
It seems that [SAP HANA is becoming more and more important][1] and SAP S/4HANA and the HANA Cloud Plattform (HCP) will replace SAP ERP in coming years. In that context will PyRFC still be relevant or will there be no use case for it any more?

I am just asking cause I don't understand what role SAP Netweaver will have in context of S/4HANA.

Cheers
Tset

[1]: https://it-onlinemagazin.de/sap-trends-2017-die-entscheider-kennen-sollten/

**Comment by Tset-Noitamotua** [comment]
Some answers I got from SAP support (Germany)

### Q: Wo ist SAP Netweaver AS im Kontext von SAP S/4HANA einzuordnen? Oder wird SAP NW AS hier gar keine mehr spielen?
> A: SAP Netweaver stellt aus Sicht von SAP S4/HANA (on premise) weiterhin die Entwicklungsumgebung für Geschäftsapplikationen dar. Informationen diesbezüglich finden Sie in unserem Help-Portal unter folgendem Link: https://help.sap.com/viewer/product/SAP_S4HANA_ON-PREMISE/1511%2520000/en-US


### Q: Sie betonen on premise ... wie sieht es im Fall von HANA Cloud Plattform (HCP) aus?
> A: Informationen bzgl. der Kompatibilität zwischen SAP Netweaver sowie der HANA Cloud Palttform kann ich Ihnen adhoc leider nicht zur Verfügung stellen. Ich würde Sie bitten uns diesbezüglich Ihre Anfrage via Mail an info.germany@sap.com weiterzuleiten. Unsere Kollegen werden Ihre Anfrage an die zuständige Fachabteilung weiterleiten, die sich umgehend direkt mit Ihnen in Verbindung setze werden.


### Q: Werde ich in der SAP S4/HANA Welt weiterhin BAPIs über RFC aufrufen können?
> A: Dies können Ihnen die Kollegen des Fachbereichs unter info.germany@sap.com genau erläutern.

Regarding [this document][1] the answer is - Yes, you can.

[1]:  https://uacp.hana.ondemand.com/http.svc/rc/PRODUCTION/pdfa3ec0db8df99460abbc799b2d06d230b/1511%20000/en-US/FSDNW75_OP1511.pdf

**Comment by bsrdjan** [comment]
I am not a strategist and cant provide clear answer here. PyRFC is Open Source and users decide whether and what for to use it, or not. Regarding mid/long term strategy I would suggest discussing in some other forum. Issues here are related to PyRFC "daily business", like bugs or feature requests.
