### ISSUE TITLE
RFC_ABAP_EXCEPTION (rc=5): key=DATA_BUFFER_EXCEEDED

### ISSUE THREAD

**Issue by rhnux** [SAP/PyRFC#42]
results = conn.call('RFC_READ_TABLE', QUERY_TABLE = '/BIC/OHZOH_PSC05', OPTIONS = options, DELIMITER='|', FIELDS = fields, ROWSKIPS = rowskips, ROWCOUNT = ROWS_AT_A_TIME)
  File "src/pyrfc/_pyrfc.pyx", line 377, in pyrfc._pyrfc.Connection.call (src/pyrfc/_pyrfc.c:4507)
  File "src/pyrfc/_pyrfc.pyx", line 232, in pyrfc._pyrfc.Connection._error (src/pyrfc/_pyrfc.c:3532)
pyrfc._exception.ABAPApplicationError: **RFC_ABAP_EXCEPTION (rc=5): key=DATA_BUFFER_EXCEEDED**, message= Number:000 [MSG: class=, type=, number=000, v1-4:=;;;]

I try similar issues like #7 and #38, but I get the same error.

**Comment by rhnux** [comment]
DATA_BUFFER_EXCEEDED only happens if the total width of the fields you want to read exceeds the width of the DATA parameter, which may vary depending on the SAP release - 512 characters for current systems. It has nothing to do with the number of rows, but the size of a single dataset. So the question is: What are the contents of the FIELDS parameter? If it's empty, this means "read all fields." CDHDR is 192 characters in width, so I'd assume that the problem is CDPOS which is 774 characters wide. The main issue would be the fields VALUE_OLD and VALUE_NEW, both 245 Characters. Even if you don't get developer access, you should prod someone to get read-only dictionary access to be able to examine the structures in detail.

**Comment by bsrdjan** [comment]
I finally reproduced the issue today, by accident. Universal Linux wheel crated on one Linux crashes with DATA_BUFFER_EXCEEDED on another one.

If the issue still reproducible, could you please try to create platform specific wheel and check if that helps?

**Comment by rhnux** [comment]
Dear,

I solved this point from the SAP side. Configured. The length of the custom fields.
Do you have the possibility to perform this action?

**Comment by bsrdjan** [comment]
@rhnux, could you please post the full set of input parameters and what exactly configuration on sap side solved the problem?

**Comment by rhnux** [comment]
@bsrdjan, I attach a small example:

When using RFC_READ_TABLE with the following fields

```
fields = ['CUST_GROUP', 'PLANT', '/BIC/ZCFEM', 'TRZONE', '/BIC/ZCUSTOMER', '/BIC/ZCOFINS',
              'SHIP_TO', '/BIC/ZMERCREG', '/BIC/ZREPRVN', 'MATERIAL', 'INCOTERMS', '/BIC/ZREPRVNA',
              '/BIC/Z_CV', 'CALDAY', '/BIC/ZDTOCONC', '/BIC/ZDEVOL', '/BIC/ZREGIONIC',
              'VAL_TYPE', 'PROD_HIER', 'FISCPER', '/BIC/ZFLAUT', '/BIC/ZCE_FTCDS',
              '/BIC/ZCE_FTPTA', '/BIC/ZCE_FTVD', 'SALES_GRP', '/BIC/ZICMS', '/BIC/ZICMS2',
              '/BIC/ZICMS3', '/BIC/ZIMPOST', '/BIC/ZIPI', '/BIC/ZISS', '/BIC/ZAREAC',
              'BILL_ITEM', '/BIC/ZMGVSTD', 'CUST_MKT', 'SALES_DIST', 'IND_CODE', 'CURRENCY',
              'BILL_NUM', 'COUNTRY', '/BIC/ZF_CSLOG', '/BIC/Z_PIS', 'SEGMENT', '/BIC/ZDIVPROD',
              '/BIC/ZRECBRUT', 'SALES_UNIT', 'BILL_QTY', 'INV_QTY', 'BILL_TYPE', 'DOC_TYPE'] 
```
The following error occurs

`pyrfc._exception.ABAPApplicationError: RFC_ABAP_EXCEPTION (rc=5): key=DATA_BUFFER_EXCEEDED, message= Number:000 [MSG: class=, type=, number=000, v1-4:=;;;]`

From sap I start to decrease the length of the fields. CHAR 10 to CHAR 5, NUMBER 19.3 to 15.3 etc.
It's not a definitive solution, but it's the only one I found.

**Comment by bsrdjan** [comment]
Could you please attach the entire test script?

**Comment by rhnux** [comment]
Solution of the SAP side.

#### 1.- Use BBP_RFC_READ_TABLE

#### 2.- Create Z_RFC_READ_TABLE t change the structure of the DATA output table, which was char of 512, by a structure that creates (ZBBP_DATA) that contains the WA char field of 1024. This allows more fields to be selected without overflowing .

**Comment by yashbhutoria** [comment]
Was there any fix for this? I do not have an option to configure anything on the SAP side.

**Comment by bsrdjan** [comment]
I could not reproduce. Please provide Python script to reproduce the issue and info on environment: pyrfc and RFC SDK versions, os platform.

**Comment by yashbhutoria** [comment]
Environment Details:
pyrfc 2.4.0
Platform: X86_64
SAP NetWeaver RFC SDK 7.50
Windows 10 Enterprise N (20H2)(19042.928)
Python 3.8.6

[error reproduction scirpt](https://gist.github.com/yashbhutoria/372627b2d37bdd59bf5216431172ff26)

**Comment by bsrdjan** [comment]
The error is a consequence of RFC_READ_TABLE limitations. Please check:

-  https://stackoverflow.com/questions/54189708/jco-rfc-read-table-data-buffer-exceeded
- https://stackoverflow.com/questions/4165551/data-buffer-exceeded-error-when-calling-rfc-read-table

**Comment by rhnux** [comment]
@yashbhutoria 
try use BBP_RFC_READ_TABLE.

**Comment by dbiswas** [comment]
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError
from configparser import ConfigParser
from pprint import PrettyPrinter

if __name__ == '__main__':
    print('\n\nDemo')
    ASHOST = 'XXXXXXX'
    CLIENT = 'NNN'
    SYSNR = 'NN'
    USER = 'XXXXXXXXX'
    PASSWD = 'XXXXXXX'
    conn = Connection(ashost=ASHOST, sysnr=SYSNR, client=CLIENT, user=USER, passwd=PASSWD)

    options = [{'TEXT': "LAND1 EQ 'SA' AND KTOKD EQ '0096'"}]
    fields = ['KUNNR', 'NAME1', 'KTOKD']

    pp = PrettyPrinter(indent=4)

    print
    u"----Begin of Batch---"
    result = conn.call('RFC_READ_TABLE', \
                        QUERY_TABLE='KNA1', \
                        OPTIONS=options, \
                        FIELDS=fields)
    pp.pprint(result['DATA'])

    #
    # result = conn.call('STFC_CONNECTION', REQUTEXT=u'Hello SAP!')
    # print (result)
