### ISSUE TITLE
PyRFC Connection call issues

### ISSUE THREAD

**Issue by gopipamula** [SAP/PyRFC#45]
Hi,

I am trying to get data from SAP system. I tried using below code but unable to return any data. Do I need to pass any thing to connection parameters.

`
>>> from pyrfc import *
>>> conn = Connection(user='XXXXXXXXXX', passwd='XXXXXXXXX', ashost='XXXXXXXXXXXXX', sysnr='XX', client='XXX')
>>> result = conn.call('STFC_CONNECTION', REQUTEXT=u'Hello Sap')
>>> print result
{u'RESPTEXT': u'SAP R/3 Rel. 740   Sysid: CUP      Date: 20170405   Time: 190015   Logon_Data: 100/R_NA_L360/E', u'ECHOTEXT': u'Hello Sap'}
>>> result = conn.call('ZBW_TESTC018')
>>> print result
{u'PT_LIST': [], u'PT_COMPANY': []}
>>>
`

**Comment by bsrdjan** [comment]
Could you please post the error text you are getting ?

**Comment by kamalelsaaid** [comment]
I have the same error
The code I write:
from pyrfc import Connection
conn = Connection(user='my_name', passwd='my_password', ashost='my_ip', sysnr='00', client='100')

 and I got that error;

Traceback (most recent call last):                                                                                                   
  File "<stdin>", line 1, in <module>                                                                                              
  File "pyrfc\_pyrfc.pyx", line 150, in pyrfc._pyrfc.Connection.__init__ (pyrfc\_pyrfc.c:2281)
  File "pyrfc\_pyrfc.pyx", line 188, in pyrfc._pyrfc.Connection._open (pyrfc\_pyrfc.c:2927)
  File "pyrfc\_pyrfc.pyx", line 218, in pyrfc._pyrfc.Connection._error (pyrfc\_pyrfc.c:3153)
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1):              key=RFC_COMMUNICATION_FAILURE, message=                                                                      
LOCATION    SAP-Gateway on host ides672.arete-global.local / sapgw00                          
ERROR       timeout during allocate                                                                                             
TIME        Sun Apr  9 15:11:11 2017                                                                                           
RELEASE     742                                                                                                                                
COMPONENT   SAP-Gateway                                                                                                        
VERSION     2                                                                                                                                   
RC          242                                                                                                                                    
MODULE      /bas/742_REL/src/krn/si/gw/gwr3cpic.c                                                             
LINE        2181                                                                                                                                  
DETAIL      no connect of TP sapdp00 from host                                                                        
              host-197.51.239.117.tedata.net after 20 sec                                                               
COUNTER     3                                                                                                                                
 [MSG: class=, type=, number=, v1-4:=;;;]                                                                              

is this mean that the problem related to the server or related to the installed pyrfc function ?

**Comment by bsrdjan** [comment]
The error key RFC_COMMUNICATION_FAILURE indicates a network problem, happening during opening the RFC connection. It usually happens because the RFC connection can't be established using given connection parameters.

Error keys are described in [NWRFC SDK Guide](https://websmp106.sap-ag.de/~sapidb/011000358700000869672007.pdf) and in `sapnwrfc.h` include of the sapnwrfc lib.

SAP troubleshooting utility `niping` can check the network connection, from the system on which the Python client is running, to ABAP  backend. It works independent of pyrfc and if the `niping` test is positive, the pyrfc should open the connection as well, without errors. The link to SAP Help I posted in [issue #43](https://github.com/SAP/PyRFC/issues/43).

**Comment by kamalelsaaid** [comment]
Okay, I will follow the links and guide, hope this give me the solution.
Thank you for your quick response.

**Comment by pranatishete** [comment]
Hi @bsrdjan  can we make a RFC call from pyrfc to sap logon even if we don't have sap logon installed in our system. And in sap do we have to add the ip address from which we are going to send the request??
