### ISSUE TITLE
Parallel requests fail

### ISSUE THREAD

**Issue by mpf82** [SAP/PyRFC#46]
When I try to send multiple RFCs in parallel with the same connection the application crashes - in such a way that I can not even handle it with ``try ... except``.

How to reproduce it:

```
import pyrfc
def test_parallel():
    from threading import Thread

    conn = pyrfc.Connection( ... )

    print("test_parallel ... start")

    def do_call(iteration):
        print("do_call {}", iteration)
        try:
            print( conn.call('STFC_CONNECTION', REQUTEXT="Hello World! Iteration: {}".format(iteration)) )
        except Exception as e:
            print("Exception in iteration {}: {}".format(iteration, e))

    # just to make sure it's working at least once
    do_call(0)

    t_list = []
    for i in range(1, 10):
        t = Thread(target=do_call, args=(i,))
        t.start()
        t_list.append(t)
    for t in t_list:
        t.join()

    conn.close()

    print("test_parallel ... done")

test_parallel()
```

Output:

> test_parallel ... start
>
> do_call {} 0
> {'ECHOTEXT': 'Hello World! Iteration: 0', 'RESPTEXT': 'SAP R/3 Rel. 740   Sysid: BLD      Date: 20170623   Time: 090216   Logon_Data: 123/xxx/D'}
> do_call {} 1
> do_call {} 2
> do_call {} 3
> do_call {} 4
> do_call {} 5
> do_call {} 6
> do_call {} 7
> do_call {} 8
> do_call {} 9
> Exception in iteration 3: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 6: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 7: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 8: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 5: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 4: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 9: RFC_INVALID_HANDLE (rc=13): key=RFC_INVALID_HANDLE, message=Invalid RFC connection handle: 58766656 [MSG: class=, type=, number=, v1-4:=;;;]
> Exception in iteration 2: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
> ERROR       program state check for conversation 12958055
> TIME        Fri Jun 23 09:02:14 2017
> RELEASE     721
> COMPONENT   CPIC (TCP/IP) with Unicode
> VERSION     3
> RC          471
> MODULE      r3cpic.c
> LINE        6078
> DETAIL      called function STSEND in state state=BUFFER_DATA2
> COUNTER     1
>  [MSG: class=, type=, number=, v1-4:=;;;]

After the last output, I get a **‘python.exe has stopped working’**.

Traceback of the communication failure:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\Python34_64\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "c:\Python34_64\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SAP_RFC_TEST.py", line 51, in do_call
    print( conn.call('STFC_CONNECTION', REQUTEXT="Hello World! Iteration: {}".format(iteration)) )
  File "pyrfc\_pyrfc.pyx", line 363, in pyrfc._pyrfc.Connection.call (pyrfc\_pyrfc.c:4130)
  File "pyrfc\_pyrfc.pyx", line 218, in pyrfc._pyrfc.Connection._error (pyrfc\_pyrfc.c:3153)
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
ERROR       program state check for conversation 13613935
TIME        Fri Jun 23 09:12:27 2017
RELEASE     721
COMPONENT   CPIC (TCP/IP) with Unicode
VERSION     3
RC          471
MODULE      r3cpic.c
LINE        6078
DETAIL      called function STSEND in state state=BUFFER_DATA2
COUNTER     1
 [MSG: class=, type=, number=, v1-4:=;;;]
```

These node-rfc issues might be related:

* https://github.com/SAP/node-rfc/issues/11
* https://github.com/SAP/node-rfc/issues/16

My system:

* pyrfc: pyrfc-1.9.4-py3.4-win-amd64
* OS: Windows 7 64 bit
* Python: 3.4.3 64 bit

**Comment by bsrdjan** [comment]
The SAP NW RFC Library is not thread safe, neither the `pyrfc` is. The recommended design is not to share a pyrfc instance among threads but instantiate a pool of client instances, so that threads can get the connection from the pool, execute the call(s) and return the connection. 

The topic is described in [SAP OSS Note 513386 - SAP Java Connector: CPIC error in multithreaded application](https://launchpad.support.sap.com/#/notes/513386) and the same principle applies for `pyrfc`, except the `pyrfc` does not have a built-in connection pool but leaves that task to client application.

Connection pool may have a parameters/features like number of free connections to be available, opening new chunk of connections when the low threshold reached, status, monitoring ... Because application requirements may vary and the pool implementation is relatively straightforward, especially in python, the `pyrfc` is not offering universal solution here.

**Comment by mpf82** [comment]
Thanks for the reply. I will check what fits my project the best (semaphore, connection pool, new connection for each RFC) and go from there.

The node-rfc issues I have found (and linked) on the subject sounded as if parallel processing *should* possible - seems I was wrong.

Cheers =)

**Comment by mpf82** [comment]
We went with the two following solutions and made it configurable which one is used:
1) making a single connection thread-safe by using semaphores 
2) using a new connection for each thread

Closing the issue.
