### ISSUE TITLE
LogonError since SAP system update to EHP8

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#47]
Since an recent update of our SAP system to EHP8 I am getting the following error:

```shell
LogonError: <Unrepresentable object LogonError. Error:
 UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 45
: ordinal not in range(128)>
```

Actually I do not use any special characters in logon information. Thus no idea where to look and how to solve that.
Some hints?

My setup:
Python 2.7.10
PyRFC 1.9.3
Windows 7 64bit

**Comment by bsrdjan** [comment]
Are you using connection parameters with username and password and eventually use unicode in username or password?

**Comment by Tset-Noitamotua** [comment]
I will check that asap and update this issue.

**Comment by bsrdjan** [comment]
Closing, no response
