### ISSUE TITLE
fill_and_submit_unit / confirm_unit return values

### ISSUE THREAD

**Issue by mpf82** [SAP/PyRFC#50]
We have modified the [clientIDoc](https://github.com/SAP/PyRFC/blob/master/examples/clientIDoc.py) example, to call ``IDOC_INBOUND_SINGLE`` - now we would like to get the SAP return value, which should contain the IDoc number.

However, ``fill_and_submit_unit`` only returns the unit dictionary (containing the ID, as well as background and queue setting) - and ``confirm_unit`` does not return anything (``None``).

Questions: 

1) Is there a way to get the actual SAP return value?

2) Is the unit ID used (and stored) somewhere on the SAP server side, so that we could maybe find a relation from the unit ID to the actual transaction?

3) Is there any advantage in using this unit approach, compared to making a direct RFC call to `` IDOC_INBOUND_SINGLE `` / ``IDOC_INBOUND_SYNCHRONOUS`` /  ``IDOC_INBOUND_ASYNCHRONOUS``?

**Comment by mtolksdorf** [comment]
Hi mpf82, 

referring to your questions:
1. you should be more precise, which value you are interested in. It i snot really clear
2. It is: Check tables that have BGRFC as prefix
3. Depends on what you need. The approach using t/qRFC or bgRFC allows to add some qualities to the execution of function modules. When implementing the protocol correctly it offers exactly once or exactly once in order behavior. So, when there is a failure in execution, you could repeat the execution of the same unit and it will still be executed only once in the system, even if the error occurred after successful execution when returning the technical response. This is not the case for synchronous invocation. Executing twice on the client will always execute twice in the system, which could lead to double bookings

Best regards,
Markus
