### ISSUE TITLE
Install error: Could not find suitable distribution for Requirement.parse('pyrfc==1.9.5')

### ISSUE THREAD

**Issue by XuRuHang** [SAP/PyRFC#53]
I'm trying to install pyrfc on my system : pyrfc-1.9.5-py3.5-win-amd64.egg

OS : Windows 7 64 bits
Python : Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32

I'm trying to install with : 
.\easy_install.py https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.5-py3.5-win-amd64.egg
(also tried with locally downloaded egg file which gives same error)

I have the following message : 
Installed c:\users\ulhe0002\appdata\local\programs\python\python36\lib\site-packages\pyrfc-1.9.5-py3.5-win-amd64.egg
Processing dependencies for pyrfc==1.9.5
Searching for pyrfc==1.9.5
Reading https://pypi.python.org/simple/pyrfc/
Couldn't find index page for 'pyrfc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pyrfc==1.9.5
error: Could not find suitable distribution for Requirement.parse('pyrfc==1.9.5')

**Comment by XuRuHang** [comment]
Well solved by adding --no-deps option to easy_install.py ...

However I cannot load the DLL : 
>>> from pyrfc import *
ImportError: DLL load failed:...

FYI i've tried to load with ctypes and it works : 
from ctypes import *
SAPNWRFC = "C:\\Program Files (x86)\SAP\\nwrfcsdk\lib\\sapnwrfc.dll"
SAP = windll.LoadLibrary(SAPNWRFC)
--> i can call SAP Modules/function

The path is also correct : 
Path=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windo
ws\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32
\WindowsPowerShell\v1.0\;C:\Program Files (x86)\SAP\nwrfcsdk\lib

Any idea ?

**Comment by bsrdjan** [comment]
Not sure what the issue could be.

I tested with just released wheel and worked fine:

```shell
(dev) $ pip install https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.7-cp27-cp27mu-linux_x86_64.whl
Collecting pyrfc==1.9.7 from https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.7-cp27-cp27mu-linux_x86_64.whl
  Using cached https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.7-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: setuptools in /home/www-admin/.virtualenvs/py27/lib/python2.7/site-packages (from pyrfc==1.9.7)
Installing collected packages: pyrfc
Successfully installed pyrfc-1.9.7
```

Can you try with 1.9.7 wheel ?

**Comment by XuRuHang** [comment]
ok retried with 1.9.7 (pyrfc-1.9.7-cp36-cp36m-win_amd64.whl) and works fine now !
