### ISSUE TITLE
SNC with X509

### ISSUE THREAD

**Issue by gibsonxavier** [SAP/PyRFC#55]
I am getting the below error when trying to use a cert based authentication. The connection works fine with basic auth.

/XXXX/XXX-engine-cert.pem',snc_lib='XXXXX/libsapcrypto.so',ashost='XXXXXX', sysnr='00', client='001', )
[Thr 140640983607040] Wed Oct 11 15:16:43 2017
[Thr 140640983607040] *** ERROR => SncPEstablishContext() failed for target='p:CN=A4H, OU=SAP-AG, C=DE' [sncxxall_m 3638]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyrfc/_pyrfc.pyx", line 164, in pyrfc._pyrfc.Connection.__init__
  File "src/pyrfc/_pyrfc.pyx", line 208, in pyrfc._pyrfc.Connection._open
  File "src/pyrfc/_pyrfc.pyx", line 238, in pyrfc._pyrfc.Connection._error
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) with Unicode
ERROR       GSS-API(maj): No credentials were supplied
            Unable to establish the security context
            target="p:CN=A4H, OU=SAP-AG, C=DE"
TIME        Wed Oct 11 15:16:43 2017
RELEASE     721
COMPONENT   SNC (Secure Network Communication)
VERSION     6
RC          -4
MODULE      sncxxall_mt.c
LINE        3604
DETAIL      SncPEstablishContext
SYSTEM CALL gss_init_sec_context
COUNTER     7
 [MSG: class=, type=, number=, v1-4:=;;;]

What should be passed in parameter x509cert=.......?

**Comment by bsrdjan** [comment]
The parameter stands for x509 certificate, as described [here]( http://sap.github.io/PyRFC/authentication.html). 

Based on x509 certificate received, ABAP system shall be able to determine the ABAP user and for that x509/ABAP-user mapping must be created in ABAP system, either 1:1 or rule-based. SNC shall be enabled in ABAP system as well and for both configurations, skilled SAP Security Consultant is required.

**Comment by gibsonxavier** [comment]
Thanks for the quick response, we have already enabled SNC and mapped imported the certificate. 

Do we pass the complete base64 encoded X509 certificate string as a parameter value in the connection string or do we pass the absolute path to the certificate? 

Also, looking at the error, It would be good to know, if we need configuration change at the ABAP system end or if there is something wrong with the connection string.

**Comment by gibsonxavier** [comment]
Ok, thanks. We will check this again on the SAP side.

**Comment by bsrdjan** [comment]
Looks clarified.

**Comment by aeweiwi** [comment]
Hi,

I know this might be old but currently I have similar problem, I get the following failure message

RFC_LOGON_FAILURE (rc=2): key=RFC_LOGON_FAILURE, message=Syntaxfehler im empfangenen X.509-Client-Zertifikat (Base64-Kodierung) 

I tried to encode the certficate using base64 but also did not work. any further ideas
