### ISSUE TITLE
Connection.call() not extracting full record (#### symbols in BKTXT)

### ISSUE THREAD

**Issue by bschwab003** [SAP/PyRFC#56]
Hello,

We are experiencing an issue when using Connection.call().  Specifically, certain records appeared to be blank after the first three fields.  After doing some digging, we were able to identify the a common theme for records that were being experiencing this problem:

The data BKTXT field in BKPF contained 1-many "odd" characters that were represented in the GUI by the pound/hash sign.  It appears that pyRFC can't handle them. 

Here is the BKTXT field per the SAP GUI:

![bkpf_in_sap](https://user-images.githubusercontent.com/8813369/31906838-c011f9be-b7f7-11e7-833c-19fcc4172a9c.png)

And here is the data exactly how it is returned in the pyrfc.Connection.call().  Note, the data for the record completely cuts off after the BKTXT field.  The adjacent records are normal.

![bkpf_data](https://user-images.githubusercontent.com/8813369/31903864-23c675ec-b7ef-11e7-9c55-7bdc13cf5a7e.PNG)

The record is cutting off immediately following BKTXT.  

Note we are calling the function module "/BODS/RFC_READ_TABLE2" and we are not using a delimiter.  We are using the RECOFFSET.

**Comment by bsrdjan** [comment]
I tried to reproduce internally and could not find any "odd" characters in two test systems.

Any chance for you to find out what these characters exactly are and post the problem causing content as base64 for example, that I can try to reproduce internally?

I am less familiar with these function module, could you please clarify what is meant by "using RECOFFSET" ? Also which pyrfc version are you using and on which platform?

**Comment by bschwab003** [comment]
Understand you may not have any special characters in your sandbox....

I am not 100% sure what the special characters are.  Just ran into another issue...with other characters..  This time, the record was not being truncated at the special character.  But it was causing the column characters from one column to spill into another.

Data in SAP:

![sap_eg3](https://user-images.githubusercontent.com/8813369/32027407-81499e0e-b9ae-11e7-8c4d-ff632783d374.png)

How the data looks when we get it back from pyrfc.Connection

![sap_eg2](https://user-images.githubusercontent.com/8813369/32027427-9d560fce-b9ae-11e7-8dba-98b9bb74f125.png)

When reading text fields from SAP, how encoding does pyrfc use? Is there a way to see and/or change how pyrfc encodes characters in text fields?

**Comment by bsrdjan** [comment]
It uses utf-8 and here the logic for transforming SAP string to python: https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L2080 

I will try to find out more about this function module.

**Comment by bschwab003** [comment]
Any chance to dig into this further?  I would expect that UTF-8 encoding would cover the majority of characters we would typically encounter in systems we are hitting......

In the rare event, however, where a character cannot be encoded using UTF-8, what is the expected behavior?  For whatever reason, maybe we are hitting this scenario and the handling of said scenario could be 'enhanced?'

**Comment by bsrdjan** [comment]
We need to reproduce and localise the issue. Here few points in that regard.

1. Functions in /BODS name space are considered obsolete. The supported ones are now in /SAPDS, for example, /SAPDS/RFC_READ_TABLE2. Could you check if the issue occurs with /SAPDS as well?

2. Which backend system release and service pack and which pyrfc release/platform?

3. Can customer file an incident and provide remote access to system with reproducible example or can you post a sample of problematic data (e.g. from ABAP debugger of using test report), that we try to reproduce in test system over here?

I will anyway try with couple of international characters, like "Garantias Imobiliárias em Contratos Empresariais: Hipoteca e Alienação Fiduciária" for example.

**Comment by bsrdjan** [comment]
Closing, no response.
