### ISSUE TITLE
cannot import name 'Connection'

### ISSUE THREAD

**Issue by I057542** [SAP/PyRFC#58]
my system environments:
1) Windows 10 64bit
2) Python 3.6 64bit

I executed following steps:
1) download SAP NW RFC SDK 7.20 for win 64bit and unpack to corresponding folder, and add the lib directory to PATH
2) In installation wiki - http://sap.github.io/PyRFC/install.html#installation it suggested to use easy_install.py. However, I tried the code but failed. Hence I skipped this step. 
3) install pyrfc with below command:
".\Desktop>pip3 install https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.7-cp36-cp36m-win_amd64.whl"
--- Successfully installed pyrfc-1.9.7 ----

4) then, I back to python 3.6 (64bit) shell: 
>>> from pyrfc import Connection
and got below errors:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Connection'
```
I searched on websites and tried several 'solution', however no one can solve my problem. Does anyone encounted the similiar issue? thank you.

**Comment by bsrdjan** [comment]
Could you please post the output of 
```shell
pip3 show pyrfc
```

**Comment by I057542** [comment]
here it is
`C:\Users\I057542\Desktop>pip3 show pyrfc
Name: pyrfc
Version: 1.9.7
Summary: Python bindings for SAP NetWeaver RFC Library (libsapnwrfc)
Home-page: https://github.com/SAP/pyrfc
Author: Srdjan Boskovic
Author-email: srdjan.boskovic@sap.com
License: OSI Approved :: Apache Software License
Location: c:\users\i057542\appdata\local\programs\python\python36\lib\site-packages
Requires: setuptools`

thank you for your help!

**Comment by I057542** [comment]
here it is:

C:\Users\I057542\Desktop>pip3 show pyrfc
Name: pyrfc
Version: 1.9.7
Summary: Python bindings for SAP NetWeaver RFC Library (libsapnwrfc)
Home-page: https://github.com/SAP/pyrfc
Author: Srdjan Boskovic
Author-email: srdjan.boskovic@sap.com
License: OSI Approved :: Apache Software License
Location: c:\users\i057542\appdata\local\programs\python\python36\lib\site-packages
Requires: setuptools

-----Thank you for your help! -----

**Comment by bsrdjan** [comment]
Removing egg of the incorrect pyrfc module solved the issue.
