### ISSUE TITLE
Empty values in TIME fields 

### ISSUE THREAD

**Issue by eyesonly** [SAP/PyRFC#6]
Some SAP standard BAPIs return an 'empty' rather than 'initial' value in a time field. For example, BAPI_BUS1240_GETDETAIL can cause Python dumps.

I have produced a repeatable scenario for the problem without having to use BAPI_BUS1240_GETDETAIL, example follows below:

=====================
Test program - python
=====================

#!/usr/bin/env /usr/bin/python
from pyrfc import Connection, ABAPApplicationError, ABAPRuntimeError, LogonError, CommunicationError
from ConfigParser import ConfigParser
from pprint import PrettyPrinter

def main():
    
    try:

        config = ConfigParser()
        config.read('sapnwrfc.cfg')
        params_connection = config._sections['connection']
        conn = Connection(**params_connection)

        result = conn.call('ZNWRFC_TIMESTAMP')

        pp = PrettyPrinter(indent=4)
        pp.pprint(result)

    except CommunicationError:
        print u"Could not connect to server."
        raise
    except LogonError:
        print u"Could not log in. Wrong credentials?"
        raise
    except (ABAPApplicationError, ABAPRuntimeError):
        print u"An error occurred."
        raise

if __name__ == '__main__':
    main()

=====================
Test function - ABAP
=====================

function znwrfc_timestamp.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     VALUE(EV_TIME) TYPE  SYUZEIT
*"----------------------------------------------------------------------

* This will make pyrfc dump
ev_time = ''.

* Uncomment this out and it will correctly initialize the field and it doesn't dump
*clear ev_time.

endfunction.

=====================
Example of dump 
=====================

$ python timedump.py 
Traceback (most recent call last):
  File "timedump.py", line 31, in <module>
    main()
  File "timedump.py", line 15, in main
    result = conn.call('ZNWRFC_TIMESTAMP')
  File "_pyrfc.pyx", line 368, in pyrfc._pyrfc.Connection.call (pyrfc/_pyrfc.c:4006)
  File "_pyrfc.pyx", line 1837, in pyrfc._pyrfc.wrapResult (pyrfc/_pyrfc.c:19400)
  File "_pyrfc.pyx", line 2013, in pyrfc._pyrfc.wrapVariable (pyrfc/_pyrfc.c:21282)
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data ' 00000' does not match format '%H%M%S'

=====================
Version 
=====================
pyrfc-1.9.4-py2.7-linux-x86_64.egg

**Comment by bsrdjan** [comment]
Thank you very much for the good example. I reproduced the issue using following ABAP code, [fixed](https://github.com/SAP/PyRFC/commit/f50100b092ed6facc1abf4f42a92b31a2b06c3ed) and updated the Linux egg. Please check if works for you.
```
FUNCTION ZNWRFC_TIMESTAMP.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_INIT) TYPE  I DEFAULT 0
*"  EXPORTING
*"     VALUE(EV_TIME) TYPE  SYUZEIT
*"     VALUE(EV_DATE) TYPE  SYDATE
*"----------------------------------------------------------------------

IF IV_INIT > 0.
  EV_TIME = ''.
  EV_DATE = ''.
ELSE.
  CLEAR EV_TIME.
  CLEAR EV_DATE.
ENDIF.

ENDFUNCTION.
```
