### ISSUE TITLE
Last ChangeLog Entry from year 2014

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#64]
Dear developers,

I see that the last ChangeLog is from 2014: 

 * http://sap.github.io/PyRFC/
 * http://sap.github.io/PyRFC/changelog.html

First I thought this library is not maintained any more, since there are no changes since 4 years.

But according to github there is progress.

Maybe it would be time for a new ChangeLog?

**Comment by bsrdjan** [comment]
Fixed. I close the issue but feel free to continue the conversation (or open new one) if any more issues with documentation.

**Comment by guettli** [comment]
thank you for maintaining this library!
