### ISSUE TITLE
wrapString uclen: 512 utf8_size: 1537

### ISSUE THREAD

**Issue by bschwab003** [SAP/PyRFC#65]
We are receiving the following error when making an `RFC_READ_TABLE2` function module call to pull data out of SAP using PyRFC 1.9.4.

`wrapString uclen: 512 utf8_size: 1537`

This sounds like it could be related to one or both of the following..

https://github.com/SAP/PyRFC/issues/7
https://github.com/SAP/PyRFC/issues/38

Hoping this can be resolved by upgrading to the latest version?

**Comment by bsrdjan** [comment]
Yes, the upgrade to the latest version should help. Did you already try?
