### ISSUE TITLE
Not able to get Python PYRFC package 

### ISSUE THREAD

**Issue by Dinesh4136** [SAP/PyRFC#66]
Need PYRFC (.whl) Package which supports Version 3.4 and Windows 64 bit. Is there any other way to connect SAP through Python?

**Comment by mpf82** [comment]
There's an .egg for Python 3.4 Win amd64 in the dist folder that you can convert to a .whl using wheel.

**Comment by Dinesh4136** [comment]
Thanks Mike. I tried command like this "**python ./wheel-0.31.1-py2-py3-none-any.whl/wheel convert pyrfc-1.9.4-py3.4-win-amd64.egg**"  It's executing but where .whl is generating which i'm not able to findout. Can you help me. Thanks :)

**Comment by Dinesh4136** [comment]
Thanks Mike. I tried command like this "python ./wheel-0.31.1-py2-py3-none-any.whl/wheel convert pyrfc-1.9.4-py3.4-win-amd64.egg" It's executing but where .whl is generating which i'm not able to findout. Can you help me. Thanks :)

**Comment by bsrdjan** [comment]
Did you try to build the wheel from source, like described in [Build from source](http://sap.github.io/PyRFC/build.html#building-the-code) ?

**Comment by bsrdjan** [comment]
Even if technically works, the 3.4 egg is more than two year old and building the current version from source is highly recommended. Did you already try it?
