### ISSUE TITLE
Upload PyRFC to pypi

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#69]
It would be very nice if you could make PyRFC available at pypi.org.

Unfortunately this is already a packages with this name. But releasing under a different name should be no problem.

**Comment by bsrdjan** [comment]
Considering still shaky support for binary wheels distribution (https://packaging.python.org/guides/packaging-binary-extensions/#publishing-binary-extensions), the build from source seem still to be the most reliable way for Linux installations.

[manylinux](https://github.com/pypa/manylinux) and Linux/Windows CI environments could help but I have no time and capacity for experimenting in that direction and no plans to support pypi in the near future.

**Comment by guettli** [comment]
Thank you for your reply. It is no problem, that you provide no wheel today. 

Building the binary wheel was easy. 

Should I close the issue?

**Comment by bsrdjan** [comment]
Yes, let us close for the time being. Before publishing, the names of node-rfc and PyRFC could be eventually changed/harmonised.
