### ISSUE TITLE
Download Link needs update

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#70]
On this page:
  http://sap.github.io/PyRFC/install.html
the link to 
 http://service.sap.com/rfc-library
is deprecated.

I was redirected and told to update my bookmarks.

This is the new page:

https://support.sap.com/en/product/connectors/nwrfcsdk.html

**Comment by bsrdjan** [comment]
thanks a lot @guettli, will fix.

**Comment by bsrdjan** [comment]
Fixed in 1.9.92 release.
