### ISSUE TITLE
RFC_Communication_Failure

### ISSUE THREAD

**Issue by vinayver198** [SAP/PyRFC#74]
Hi,

I am trying to make a connection like this
from pyrfc import Connection

def get_connection(connmeta):
    """Get connection"""
    print 'Connecting ...', connmeta['ashost']
    return Connection(**connmeta)

TEST = {
    'user'      : 'xxxx',
    'passwd'    : 'xxxx',
    'ashost'    : 'xxxx',
    'sysnr'     : 'xx',
    'client'    : 'xxx',
    'sysid'     : 'xxx',
    'lang'      : 'xx'
    }

conn = get_connection(TEST)

After getting executed, it is throwing this error.
pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_C
OMMUNICATION_FAILURE, message=Timeout while opening an RFC connection. [MSG: cla
ss=, type=, number=, v1-4:=;;;]

Where I am getting wrong ?
Please Help!!

**Comment by bsrdjan** [comment]
It looks like a network connectivity issue. As a quick check, you may try if the same parameters work from SAPLOGON client, if SAPLOGON available?

For troubleshooting, you may try SAP `niping` tool and check if `niping` can reach the ABAP backend, using the same parameters. When `niping` works with certain parameters set, the PyRFC works as well.

Here few hopefully helpful links:

* [OSS NOTE 500235 - Network Diagnosis with NIPING](https://launchpad.support.sap.com/#/notes/500235)
* https://blogs.sap.com/2015/07/08/understanding-saprouter/
* https://blogs.msdn.microsoft.com/saponsqlserver/2011/04/26/niping-a-useful-tool-from-sap/

**Comment by vinayver198** [comment]
Thanks @bsrdjan , Links helped me a lot :). Issue resolved.
