### ISSUE TITLE
pyrfc 1.9.5 - importerror while calling from IIS hosted .NET Core api

### ISSUE THREAD

**Issue by Niladri24dutta** [SAP/PyRFC#75]
I am facing the below issue while running a python script from a .NET Core api which is hosted in windows server IIS . 
    from pyrfc import Connection
      File "<C:\Program Files\Python35\lib\site-packages\pyrfc-1.9.5-py3.5-win-amd64.egg\pyrfc\__init__.py>", line 22, in <module>
        from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
    `ImportError: DLL load failed: The specified module could not be found.`

It's working fine from the command prompt , python IDLE, powershell etc. Previously I got this error when the visual c++ redistributable package was not installed . But now it is installed properly as the same script is working from IDLE and powershell. 

Here are the installed software details - 
- windows server 2016 64 bit 
- Visual c++ 2013 redistributable 64 bit 
- Python 3.5 64 bit,
- pyrfc 1.9.5 for python 3.5 64 bit (amd64)
- SAP NW sdk 7.5.0 64 bit 

Python executable and the path to the `lib` folder of the SDK is already added to the Environment variable. I have also tried to execute the sample rfcexec.exe program from the `bin` directory it's working fine. I am only getting the error while running the application from IIS. The app pool identity has full permission on the python scripts.

**Comment by Niladri24dutta** [comment]
I used the `.egg` file with setuptools to install pyrfc. isn't it the correct one?

**Comment by Niladri24dutta** [comment]
@bsrdjan thanks for the reply. I have found the solution after debugging for atleast 1 week. The problem was access related issue. the SAP NW RFC SDK was installed in the path `C:\nwrfcsdk\lib` as per the documentation.

But the user account under which the .NET Core API was running in the application pool of IIS didn't have any read/write access to this `nwrfcsdk` folder. Hence pyrfc was not able to import the DLL (`SAPNWRFC.dll`) when the python script was being called from the .NET Core API.I have provided read/write access to that particular account and the script is running fine now .

I have followed the below steps to debug the diagnose the issue -

   -  I have used profiling with Procmon.exe from sysinternals to monitor w3wp.exe IIS worker process and python.exe after calling the API

   -  I have also used dependency walker to track the dependent dll.
you can close this issue.

**Comment by bsrdjan** [comment]
Hi @Niladri24dutta,

thank you very much for solving the issue and documenting solution steps. It really helps other users with same or similar setup.

Yes, the .egg is also correct. Egg and wheel are functionally identical, only the latest pyrfc egg for Python 3.5 was the older [pyrfc 1.9.5 version](https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.5-py3.5-win-amd64.egg).

In case you did not built the current version from source and prefer .egg over wheel, here the latest [pyrfc 1.9.92 .egg for Python 3.5](https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.92-py3.5-win-amd64.egg).

**Comment by Niladri24dutta** [comment]
@bsrdjan just a request , the installation documentation is missing some important dependency steps and troubleshooting steps which I faced during the installation . They are available in README but not in the installation documentation. Should I create a PR to add them in the documentation. ( like the visual c++ redistributable dependency for windows)

**Comment by bsrdjan** [comment]
Thank you @Niladri24dutta, good point. The documentation is actually in rework, for the version 2 and Windows prerequisites are already added. No need for PR.

**Comment by amarvin** [comment]
Duplicate of #54
