### ISSUE TITLE
Pyhton error with CX_Oracle package

### ISSUE THREAD

**Issue by Dinesh4136** [SAP/PyRFC#76]
Hi,

Getting below error "connection = cx_Oracle.connect('discovery/Welcome1@172.20.60.77:1521')" . Python 32 bit ,Pycharm 32bit installed. 
cx_Oracle.DatabaseError: DPI-1047: 32-bit Oracle Client library cannot be loaded: "D:\app1\client\product\12.1.0\client_1\bin\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help
Please do help.

Thanks!

**Comment by bsrdjan** [comment]
Please use this repository for PyRFC related issues. I am sorry that I can't help with Oracle/Python integration issues. Perhaps you can try posting an issue @ [ODPI](https://github.com/oracle/odpi)?

PyRFC can read also Oracle tables' content, via ABAP remote function modules, if of any help in your scenario.
