### ISSUE TITLE
Port number configuration in Connection

### ISSUE THREAD

**Issue by notmatthancock** [SAP/PyRFC#79]
Is it possible to specify the port number on instantiation of a `Connection` object? The docstring for the class doesn't suggest that this is possible, but the [help page](https://help.sap.com/viewer/ports) says the application server listens on a range (3300-3399) of ports. Is a port chosen automatically?

note: setting `ashost=domain.com:port` does not work

**Comment by bsrdjan** [comment]
hope the reply comes not too late.

The port number is not automatically chosen but depends on System Number (SYSNO). Assuming the XY is the SysNo, the Gateway Port is 33XY. The most of systems are running with SYSNO 00 and the port is almost always 3300. 

There are few possibilities to set the SYSNO, like:

1. Provide the SYSNO = XY connection parameter. The RFC library will first check if the service sapgwXY is maintained in /etc/services and if not, it will use the 33XY port

2. Provide ASSERV or GWSERV parameter. Here either the Service (sapgw00) or the Port number (3300) can be provided. This is used mostly in systems not using the standard 33XY port

Hope this helps.
