### ISSUE TITLE
Link from docs to source.

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#82]
On this page http://sap.github.io/PyRFC/client.html#examples

Please make the word "clientStfcStructure.py" a link to the source: https://github.com/SAP/PyRFC/blob/master/examples/clientStfcStructure.py

This makes it easier to look up to the details.

Thank you.

**Comment by bsrdjan** [comment]
Thanks, will add in next release.

**Comment by bsrdjan** [comment]
Fixed in 1.9.94 release.
