### ISSUE TITLE
pyrfc._exception.RFCError: Unknown RFC type 23 when wrapping

### ISSUE THREAD

**Issue by MassimoCastell** [SAP/PyRFC#83]
Reading a table from SAP there a fields defined as type "DF16_DEC". Returning pyrfc gets this error.

pyrfc._exception.RFCError: Unknown RFC type 23 when wrapping xxxx

It is possible to process all data types defined in SAP (all attached in the screenshot)?

![2018-10-01 19_51_25-dictionary_ struktur anzeigen](https://user-images.githubusercontent.com/29167382/46306092-90906480-c5b3-11e8-8690-0898bbb43c10.png)

Thank you.

Regards from germany

Massimo

**Comment by MassimoCastell** [comment]
OK. Sorry. This is probably not an error of PyRFC. It seems that generally only strings are allowed through RFC.

**Comment by bsrdjan** [comment]
Solved by adding RFCTYPE_DECF16
