### ISSUE TITLE
Unable to fetch data from BAPI BAPI_SYSTEM_MON_GETTREE

### ISSUE THREAD

**Issue by anupmk1986** [SAP/PyRFC#85]
Hi,

I'm trying to call the BAPI BAPI_SYSTEM_MON_GETTREE, but the program doesn't work. I get the below error 

Traceback (most recent call last):
  File "C:/Users/anupk/Documents/Anup/Python27/TestProject/pgm_sap.py", line 9, in <module>
    a=conn.call("BAPI_SYSTEM_MON_GETTREE", MONITOR_NAME=imp,EXTERNAL_USER_NAME='xxxx')
  File "_pyrfc.pyx", line 368, in pyrfc._pyrfc.Connection.call (pyrfc\_pyrfc.c:4006)
  File "_pyrfc.pyx", line 1837, in pyrfc._pyrfc.wrapResult (pyrfc\_pyrfc.c:19400)
  File "_pyrfc.pyx", line 1910, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:19954)
  File "_pyrfc.pyx", line 1882, in pyrfc._pyrfc.wrapTable (pyrfc\_pyrfc.c:19732)
  File "_pyrfc.pyx", line 1855, in pyrfc._pyrfc.wrapStructure (pyrfc\_pyrfc.c:19609)
  File "_pyrfc.pyx", line 2013, in pyrfc._pyrfc.wrapVariable (pyrfc\_pyrfc.c:21282)
  File "C:\Python27\Lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '      ' does not match format '%H%M%S'

Process finished with exit code 1

Below is the code
from pyrfc import *

conn = Connection(user='xxxx', passwd='xxxxxx', ashost='xxxxxx', sysnr='00', client='100')
f = conn.call('BAPI_XMI_LOGON', EXTCOMPANY= 'Test',EXTPRODUCT= 'Test Agent',INTERFACE='XAL',VERSION='1.0')
ms_name="SAP CCMS Monitor Templates"
imp =dict(MONI_NAME='Filesystems',MS_NAME=ms_name.rstrip())
a=conn.call("BAPI_SYSTEM_MON_GETTREE", MONITOR_NAME=imp,EXTERNAL_USER_NAME='xxxx')
print a

The problem seems to be with ms_name variable. Could you please help how to call the BAPI function?

Thanks in advance

**Comment by bsrdjan** [comment]
Could you please share the pyrfc version used and did you try the latest one?

**Comment by anupmk1986** [comment]
Hi,

I'm currently using pyrfc version 1.9.3

One thing noticed was if ms_name is provided without any spaces like "SAPCCMSMonitorTemplates", program would work but i would get below error message

'SAPCCMSMonitorTemplates' is not a valid monitor set name

"SAP CCMS Monitor Templates" was fetched from BAPI BAPI_SYSTEM_MON_GETLIST that fetches all the monitor sets 

Thanks,
Anup

**Comment by bsrdjan** [comment]
Hi Anup,

I am not familiar with BAPI_SYSTEM_MON_GETLIST semantics but what works in SE37, should, (with Conversion Exits implemented, if any), work in PyRFC as well.

You may try different input parameters in ABAP transaction SE37, or ABAP test reports. Once you get expected results, you may try the same input parameters with PyRFC.

The current version is 1.9.93 and if you use 1.9.3, please upgrade as many bugs fixed in between.

Regards,
Anup

**Comment by bsrdjan** [comment]
Hi Anup,

was any of above answers helpful ? Is any more support needed or shall we close the issue?

Regards,
Srdjan
