### ISSUE TITLE
SNC authentication

### ISSUE THREAD

**Issue by ku7mich** [SAP/PyRFC#87]
I am trying to connect with following code:

```
from pyrfc import Connection

def get_connection(connmeta):
    """Get connection"""
    print ('Connecting ...', connmeta['ashost'])
    return Connection(**connmeta)

SB1_300 = {
    'snc_partnername': 'p:CN=TEST_01@KKK.KZ',
#    'snc_lib': 'C:\Program Files\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll',

    'name': 'TEST_01@KKK.KZ',
    'client': '300',
    'ashost': 'happ01sb1',
    'sysnr': '10',
#    'trace': '3'
}

conn = get_connection(SB1_300)
```
And get the errror:

```
**** Trace file opened at 2018-11-20, 17:13:43 Pakistan Standard Time
NW RFC Library: SDK variant, Release 750 Patch Level 2, Compiled on Aug 31 2018 22:25:28
 CPIC library: 753.2018.08.08 version 3, NI library: 40, Kernel Release: 753 Patch Level 225
 Current working directory: I:\, Program: python
 Hardware: PC with Windows NT 4x AMD64 Level 6 (Mod 94 Step 3), Operating_system: Windows NT 10.0

Error during connect: 
LOCATION    CPIC (TCP/IP) with Unicode
ERROR       GSS-API(maj): Miscellaneous failure
            GSS-API(min): A2200210:Peer certificate verification failed
            target="p:CN=TEST_01@KKK.KZ"
TIME        Tue Nov 20 17:13:43 2018
RELEASE     753
COMPONENT   SNC (Secure Network Communication)
VERSION     6
RC          -4
MODULE      D:/depot/bas/753_REL/src/krn/snc/sncxxall.c
LINE        3604
DETAIL      SncPEstablishContext
SYSTEM CALL gss_init_sec_context
COUNTER     4
```
But connection by SAP GUI is working fine.

**Comment by bsrdjan** [comment]
To be able to communicate using SNC, the ABAP system must be able to
identify Python "system" and vice versa, using public certificates, exchanged and stored in Personal Secure Environment. Based on error message it looks like this configuration is missing (is independent from SAP GUI) or needs to be fixed.

Please find some more info, hopefully helpful to verify and fix the configuration: 

* [2497505 - SNC Error Code A2200210 Peer certificate verification failed - Kerberos configuration](https://launchpad.support.sap.com/#/notes/2497505)

* [645876 - Configuring SNC (J2EE Engine <--> ABAP using JCo)](https://launchpad.support.sap.com/#/notes/645876) (see attached document SNC_JCO.pdf, for Java but the same applies with Python)

* [Configuring SNC: External Programs -> AS ABAP Using RFC ](https://help.sap.com/saphelp_nwpi71/helpdata/en/2c/83ed79a1c44508a848f070c538b912/frameset.htm)

**Comment by bsrdjan** [comment]
The blog could be helpful as well: https://blogs.sap.com/2006/09/29/setup-data-encryption-between-rfc-client-and-web-as-abap-with-snc/
