### ISSUE TITLE
Enable Background RFC Requests

### ISSUE THREAD

**Issue by inviscid** [SAP/PyRFC#9]
Currently bgrfc is marked as not operational.  Enabling the use of background processing is essential for large result sets due to RFC timeout issues.  Not trying to be selfish but the immediate need is for enabling this functionality in the client, not on the server.

Three key aspects seem to be important in this process:
1. Triggering the execution of a background RFC on an external system
2.  Monitoring the execution of the background process to determine status and completion
3.  Retrieving the results of the background process once the request is complete

**Comment by bsrdjan** [comment]
Still no capacity for new features.
