### ISSUE TITLE
Can PyRFC be combined with gevent

### ISSUE THREAD

**Issue by jjmurre** [SAP/PyRFC#90]
I am trying to use PyRFC together with gevent. However, PyRFC is based on underlying SAP c libraries. So, I guess calls to SAP through PyRFC will be blocking calls. So combining PyRFC with gevent will not get the benefits of asynchronous gevent execution, I am correct?

**Comment by bsrdjan** [comment]
The behaviour is documented [here](https://github.com/SAP/PyRFC/blob/master/src/pyrfc/_pyrfc.pyx#L64) and you may use gevent or stack like supervisord/gunicorn/flask/pyrfc for example:

```python
# NOTES ON NOGIL:
# NW RFC Lib function call may take a while (e.g. invoking RFC),
# other threads may be blocked meanwhile. To avoid this, some statements
# calling NW RFC Lib functions are executed within a "with nogil:" block,
# thereby releasing the Python global interpreter lock (GIL).
```

**Comment by jjmurre** [comment]
That's great news. Tx. for the info, I'll close this issue.
