### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#91]
If I call a RFC which has an optional argument, and supply this argument with None,
then I get this error:

```
Traceback (most recent call last):
  File "tmp/test-rfc-get-report-data.py", line 6, in <module>
    data = conn.call('/MLK/GET_REPORT_DATA', IV_REPORT_NAME='RM07MLBS', IV_SELECTION_SET_VARIANT=None)
  File "src/pyrfc/_pyrfc.pyx", line 393, in pyrfc._pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 1623, in pyrfc._pyrfc.fillFunctionParameter
  File "src/pyrfc/_pyrfc.pyx", line 1670, in pyrfc._pyrfc.fillVariable
  File "src/pyrfc/_pyrfc.pyx", line 1793, in pyrfc._pyrfc.fillString
AttributeError: 'NoneType' object has no attribute 'encode'

```
I see two ways to solve this:

V1: give a better error message at say that a string is needed.

V2: if the python developer uses the kwarg value=None then it is the same like not use the kwarg
"value" at all.

**Comment by bsrdjan** [comment]
Added in 1.9.94

**Comment by guettli** [comment]
@bsrdjan thank you very much for implementing this. Just one little feature request: It would be nice to have a link from the issue to the commit which closes it. I guess you already know this: https://help.github.com/en/articles/closing-issues-using-keywords 

Back to the important topic: Thank you for fixing this issue.

**Comment by kkrani2009** [comment]
getting error while using ORS tool of QGIS

**Comment by guettli** [comment]
@kkrani2009 do you have traceback? I think the authors of pyrfc would like to see it.

**Comment by kaneali** [comment]
Hello, I get this error while using flask and smtplib. May someone help me? I am very stuck.

**Comment by kaneali** [comment]
![python_code](https://user-images.githubusercontent.com/61082818/78960035-0e102b80-7aed-11ea-9474-73b488d6b949.JPG)

**Comment by bsrdjan** [comment]
The error is likely caused by value sent from Python to AbAP RfC. Please open new issue and provide more details: platform, pyrfc and SAP NWRFC SDK versions. Also the full error log.

**Comment by Akshayarohith** [comment]
SOS!!! Coding helper!!!
For the below code:

![Capture1](https://user-images.githubusercontent.com/83659469/117030085-e35acb80-ad1c-11eb-9e56-ca7cff615867.PNG)


Error I am getting:

![Capture](https://user-images.githubusercontent.com/83659469/117029867-b4445a00-ad1c-11eb-8f5c-6bdf8db3ba24.PNG)


What to do please???

**Comment by amarvin** [comment]
> SOS!!! Coding helper!!!
> For the below code:
> 
> ![Capture1](https://user-images.githubusercontent.com/83659469/117030085-e35acb80-ad1c-11eb-9e56-ca7cff615867.PNG)
> 
> Error I am getting:
> 
> ![Capture](https://user-images.githubusercontent.com/83659469/117029867-b4445a00-ad1c-11eb-8f5c-6bdf8db3ba24.PNG)
> 
> What to do please???

Your question has nothing to do with this Python package `pyrfc` nor is it related to this GitHub Issue. How did you get here? Sorry that this isn't the right place to ask about the error you're facing.

**Comment by YashKansagara-0** [comment]
Mine was just solved by restarting the IDE
