### ISSUE TITLE
<unprintable ABAPRuntimeError object>

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#92]
If the error message of ABAP contains a german umlaut in latin1, then I see "<unprintable ABAPRuntimeError object>" in Python2.7.
```

    data = connection.call('/MLK/GET_REPORT_DATA', **cls.get_report_data_kwargs(report, parameter_value_list))
  File "src/pyrfc/_pyrfc.pyx", line 397, in pyrfc._pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 238, in pyrfc._pyrfc.Connection._error
ABAPRuntimeError: <unprintable ABAPRuntimeError object>
```

The real error message is this:

> ABAPRuntimeError(u'Sie haben keine Berechtigung f\xfcr diesen Vorgang in Werk 0001',)

It would be very nice if I could see above line and not `ABAPRuntimeError: <unprintable ABAPRuntimeError object>`

I guess the error message is in latin1 since "für" is written as "f\xfcr". In utf8 the umlaut would be two bytes.

I hope I added enough information for you. Please ask, if you need more input.

I use pyrfc==1.9.91

**Comment by guettli** [comment]
I was able to solve this.

Here is the simple patch:

```

--- /home/foo_cok_q/lib/python2.7/site-packages/pyrfc/_exception.py	2018-12-11 10:03:12.195006000 +0100
+++ tmp/_exception.py	2018-12-11 10:02:56.574940456 +0100
@@ -68,6 +68,7 @@
                  msg_class=None, msg_type=None, msg_number=None,
                  msg_v1=None, msg_v2=None, msg_v3=None, msg_v4=None):
         super(RFCLibError, self).__init__(message)
+        message = message.encode('ascii', errors='backslashreplace')
         self.message = message # Exception.message removed in Py3
         self.code = code
         self.key = key

```

Here is a test to see that it is working:

```
    def test_pyrfc_exception(self):
        import pyrfc
        exc = pyrfc.ABAPRuntimeError('message mit Umlaut üöä')
        self.assertEqual('??? (rc=None): key=None, message=message mit Umlaut \\xfc\\xf6\\xe4 [MSG: class=None, type=None, number=None, v1-4:=None;None;None;None]', str(exc))

```

If you do not have the simple patch applied this fails with a UnicodeError. This UnicodeError is the reason why you see "<unprintable ABAPRuntimeError object>".

Maybe this is only an issue on Python 2.7. 

I don't have Python3 to test it.

**Comment by bsrdjan** [comment]
I tested with pyrfc 1.9.93 and could not reproduce in standard Python console, neither with  Python 2.7, nor with Python 3.7:

```python
>>> import pyrfc
>>> message = 'Umlauts üöä'
>>> exc = pyrfc.ABAPRuntimeError(message)
>>> exc
ABAPRuntimeError('Umlauts \xc3\xbc\xc3\xb6\xc3\xa4',)
>>> print exc # print (exc) in Python 3
??? (rc=None): key=None, message=Umlauts üöä [MSG: class=None, type=None, number=None, v1-4:=None;None;None;None]
>>>
```
Could you please let me how exactly your test setup looks like? 

If you use the docker container, could you please check of unicode locales are properly installed and PYTHONIOENCODING env variable set (see https://github.com/docker-library/python/issues/147) ?

**Comment by guettli** [comment]
```
python tmp/unicode-exc.py
Traceback (most recent call last):
  File "tmp/unicode-exc.py", line 7, in <module>
    assert '??? (rc=None): key=None, message=message mit Umlaut \\xfc\\xf6\\xe4 [MSG: class=None, type=None, number=None, v1-4:=None;None;None;None]' == str(exc), exc
  File "/home/foo_cok_q/lib/python2.7/site-packages/pyrfc/_exception.py", line 88, in __str__
    self.msg_v1, self.msg_v2, self.msg_v3, self.msg_v4
UnicodeEncodeError: 'ascii' codec can't encode characters in position 19-21: ordinal not in range(128)

```
Version:

foo_cok_q@conuskq01:~$ python --version
Python 2.7.13


File:
```

# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals


import pyrfc
exc = pyrfc.ABAPRuntimeError('message mit Umlaut üöä')
assert '??? (rc=None): key=None, message=message mit Umlaut \\xfc\\xf6\\xe4 [MSG: class=None, type=None, number=None, v1-4:=None;None;None;None]' == str(exc), exc


```

**Comment by bsrdjan** [comment]
Following the https://stackoverflow.com/questions/23370025/what-is-unicode-literals-used-for, I suspect the issue could be utf8 settings of your console/platform.

Could you please post the output of environment variables LC_CTYPE, LANG and LC_ALL and check if the issue still occurs after configuring the system/console for unicode?

I tested with Python 2.7.15 and test script:

**unicode.py**

```python
# encoding: utf-8

from __future__ import unicode_literals

message  = 'message mit Umlaut üöä'

print message
``` 

With my standard test environment the script works fine:

```shell
LANG=en_US.UTF-8
LC_CTYPE=UTF-8

$ python unicode.py
message mit Umlaut üöä
```

After changing the LC_CTYPE to "C", the issue is reproduced:

```shell
$ python unicode.py
Traceback (most recent call last):
  File "unicode.py", line 7, in <module>
    print message
UnicodeEncodeError: 'ascii' codec can't encode characters in position 19-21: ordinal not in range(128)
$
```

**Comment by guettli** [comment]
I am very very happy that you can reproduce the issue.

I think pyrfc should work even if LC_CTYPE is "C".

Changing my environment is only a work-around.

Several are other people will have this issue in the future if it does not get solved (including environments where LC_CTYPE is "C".)

**Comment by bsrdjan** [comment]
Proposed change would affect all Python 2 users with unicode settings. They would get ascii encoded output  like `message mit Umlaut \xfc\xf6\xe4`, despite their environment is unicode and they expect `message mit Umlaut üöä`.

Moreover, if the behaviour changed for errors only, assuming the conditional encoding based on detected terminal encoding is possible, the same issue will occur as soon the user gets some data from SAP system (unicode) and try to print them.

As nobody complained so far about the behaviour, I could reproduce with retiring Python 2 only, I would rather leave it as it is. Also do not see the use-case for using non-unicode terminal for working with SAP unicode system.

**Comment by guettli** [comment]
@bsrdjan yes, you are right. Up to now I still use Python2, but this will change soon. Then this bug does not affect me any more. I am already running a patched version since several months. Thank you for the support! I am closing this.
