### ISSUE TITLE
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#96]
If I build a wheel, there is one warning:

===> python setup.py bdist_wheel
....
....
/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -DSAPwithTHREADS -DSAPonLIN -I/usr/include/python2.7 -c src/pyrfc/_pyrfc.cpp -o build/temp.linux-x86_64-2.7/src/pyrfc/_pyrfc.o -Wall -O2 -fexceptions -funsigned-char -fno-strict-aliasing -Wall -Wno-uninitialized -Wcast-align -fPIC -pthread -minline-all-stringops -I/home/tguettler/projects/pyrfc-env/include
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

**cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++**

It complies fine, but it leaves a vague feeling. Maybe there is something wrong?

**Comment by bsrdjan** [comment]
The issue occurs with Python 2 only and reading the [stackoverflow#8106258](https://stackoverflow.com/questions/8106258/cc1plus-warning-command-line-option-wstrict-prototypes-is-valid-for-ada-c-o) discussion, it looks like a Python 2 bug. Considering the soon Python 2 sunset, I would rather not add and test additional workarounds in PyRFC setup.py, to fix the harmless warning.

**Comment by guettli** [comment]
@bsrdjan thank you very much for looking at it. Yes, if this is Python2 only, then I think it does need an action. I close this.
